### ISSUE TITLE
Modify flash to support clustering

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#1453]
Currently the flash implementation is entirely stored in the Application scope. This
makes it unclusterable. Make it so data stored in the flash is cluster friendly.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0.2]

**Comment by BalusC** [comment]
> [@javaserverfaces](https://github.com/javaserverfaces) Commented Marked as **incomplete** on Monday, December 10th 2012, 6:23:57 am

It shouldn't have been closed. It's now at least finally fixed via https://github.com/eclipse-ee4j/mojarra/pull/6025.
