### ISSUE TITLE
State saving synchronization on session object is erroneous

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#3738]
com.sun.faces.renderkit.ServerSideStateHelper synchronizes on a session object:

```
Map<String, Object> sessionMap = externalContext.getSessionMap();

//noinspection SynchronizationOnLocalVariableOrMethodParameter synchronized (sessionObj) {
```

There's no guarantee that the session object == the same instance during a lifetime of a session. And with Undertow this is not the case. A new HttpServletImpl object is created for each request. Thus ServerSideStateHelper's state handling is basically unsynchronized.
#### Environment
Wildfly 8.1.0.Final
#### Affected Versions
[2.2.8]

**Comment by VsevolodGolovanov** [comment]
> I've created [SERVLET_SPEC-122](https://java.net/jira/browse/SERVLET_SPEC-122), which contains some additional points.

It now can be found at https://github.com/jakartaee/servlet/issues/122
