### ISSUE TITLE
Component state is not restored inside ui:repeat

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#3837]
When an ajax request is triggered the ComponentStateHelper.restoreState is not called for components inside ui:repeat. This is a result of #3156 - UIRepeat.setIndex is not called, the components are not visited and there is no state to restore.

Allowing UIRepeat.setIndex to execute during the first call to UIRepeat.doVisitChildren (during Restore View Phase) will result in successfully restoring the state.
#### Affected Versions
[2.2.9]

**Comment by BalusC** [comment]
FYI: this change will be reverted in Mojarra 4.0.23 and onwards because it's incompatible with FSS. See also #5927.

That UIData worked fine without this work around should have been a big clue that actual bug was somewhere else in UIRepeat, not in the requiresRowIteration method.
