### ISSUE TITLE
faces flow "containing directory" convention correctness

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#3887]
Implement [JAVASERVERFACES_SPEC_PUBLIC-1371](https://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1371 "11.4.3.3 (Packaging Flows in Directories) ambiguity").
#### Affected Versions
[2.2.11]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
