### ISSUE TITLE
UIComponent passThroughAttributes implemented as ConcurrentHashMap. Why?

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4023]
From Kevin Jackson:

> KJ> 1) In UIComponentBase, PassThroughAttributesMap is a ConcurrentHashMap.
> KJ> I see several other maps in this class and they are all ordinary
> KJ> HashMaps. Since ConcurrentHashMaps are so much heavier than HashMaps,
> KJ> there must be something that I am missing here. Why did you use a
> KJ> ConcurrentHashMap for pass thru attributes? From what I understand, the
> KJ> component tree can only be accessed from one thread at a time.

**Comment by manfredriem** [comment]
Kevin, while you are right that one only should access the component tree from one thread unfortunately not all frameworks / users honor that, which is why the ConcurrentHashMap was used.
