### ISSUE TITLE
HtmlResponseWriter passThroughAttributes ivar is ConcurrentHashMap. Why?

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4024]
From Kevin Jackson:

> KJ> 3) When you make a copy of the pass thru attributes, you create another
> KJ> ConcurrentHashMap. Are ResponseWriters ever accessed concurrently? I
> KJ> don't think so.

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
