### ISSUE TITLE
Implicit EL resolver for #{component} erroneously makes resolved outcome conditionally

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4033]
<tt>ImplicitObjectELResolver</tt> sets the outcome of whether <tt>#{component</tt>} is resolved based on the value of the result.

This happens via the following code:

```
UIComponent c = UIComponent.getCurrentComponent(facesContext);
context.setPropertyResolved(c != null);
```

This doesn't seem to be correct. Property resolved should be set solely based on whether the resolver handles the property or not (it always does here, so should always be set to true).

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
