### ISSUE TITLE
<f:validateBean disabled="true" > seems to not be implemented

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4071]
While working on the implementation of [JAVASERVERFACES_SPEC_PUBLIC-1](https://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1 "multi-component validation"), I observed that the "disabled" attribute on <f:validateBean> seems to not be implemented.

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
