### ISSUE TITLE
f:validateWholeBean requires f:validateBean in each input

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4087]
f:validateWholeBean requires f:validateBean in each input -
f:validateBean should be indicated for each input even if there is no validation contrains, otherwise I get an "HV000028: Unexpected exception during isValid call." exception. I don't think this is pretty intuitive.
#### Environment
Payara 4.1
#### Affected Versions
[2.3.0-m04]

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
