### ISSUE TITLE
Media attribute not declared for outputStyleSheet tag

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4095]
The <font color="red">media</font> attribute is not declared in the tag

```
<h:outputStylesheet  />
```
#### Environment
Java 1.8, NetBeans 8.0.2
#### Affected Versions
[2.2.7]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
