### ISSUE TITLE
javax.faces.validator.ValueExpressionAnalyzer does not delegate method invokation if bean has a parameter like bean1.getAttribut(someParameter).someOther

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4100]
javax.faces.validator.ValueExpressionAnalyzer does not delegate method invokation if bean has a parameter like bean1.getAttribut(someParameter).someOther

Patch ist to add an invocation delegate to ValueExpressionAnalyzer

```
public Object invoke(ELContext context, Object base, Object method, Class<?>[] paramTypes, Object[] params)
{
	return delegate.invoke(context, base, method, paramTypes, params);
}
```
#### Affected Versions
[2.2.12]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
