### ISSUE TITLE
preRenderView of the multi hop forwarded page not getting executed in JSF - Mojarra 2.2.12

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4107]
Here is the scenario which is

Page A.xhtml
i. Click an ajax submit button
ii. above click navigates to Page B (not a redirect)

Page B.xhtml
i. There is a "preRenderView" event defined in under f:metadata.
ii. "preRenderView" listener under certain scenario's does a forward to next page i.e. Page C.xhtml
iii. This is used to do navigation - facesContext.getApplication().getNavigationHandler().handleNavigation(facesContext, null, outcome); (not a redirect)

So far so good

Page C.xhtml
i. There is a "preRenderView" event defined in this page under f:metadata - which never gets executed

Problem: Page C is rendered but its "preRenderView" never gets executed.

Note: I tested this scenario with WAS Liberty Server 8.5.5.8 - JEE7 compliant server with Apache MyFaces and it works perfectly fine there.

Thanks for looking into it.
#### Environment
Wildfly 9.0.2.Final, JDK 1.8.0_65, Windows 8
#### Affected Versions
[2.2.12]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
