### ISSUE TITLE
EL-Conditional operator ?: in composite component 

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4120]
If conditional operator ? : in composite component is used with a list in a c:foreach loop, its behavior is not correct.

Please see for more Details: [http://stackoverflow.com/q/36156345/2023524](http://stackoverflow.com/q/36156345/2023524)
#### Affected Versions
[2.2.11]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
