### ISSUE TITLE
Updating jsf separator char requires users to clear their browser cache

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4125]
The jsf.js file contains a line:
jsf.separatorchar = '-';

This appears to be generated from the separator value in the web.xml file of an application. However, because of the way the file is cached it seems that changing the separator value requires clients to clear their cache to pick up the new version of the jsf.js file.

While it is unlikely that we will change the separator char often, it seems that it should be something an application could do without requiring users to clear their cache (no application should ever force a user to clear their cache).

How to reproduce:

If I access the application I can see in the browser network logs an initial request with a 200 response for jsf.js and subsequent 304 (not modified) responses as I navigate around. This is expected.

If I modify the jsf separator char in the application's web.xml and redeploy the browser receives only 304s for the jsf.js resource, even though the jsf.js file has changed because it contains the separator char as a variable.

Forcing the browser to do a refresh will fetch the latest jsf.js file from the server and the application will work correctly.
#### Affected Versions
[2.2.12]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
