### ISSUE TITLE
passthrough is not handled correctly

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4140]
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:pt="http://java.sun.com/jsf/passthrough"
xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
<h:form pt:role="form">
<ui:include src="test.xhtml"/>
<h:inputText id="second" pt:placeholder="Test"/>
</h:form>
</h:body>
</html>

and the file test.xhtml:

<ui:composition
xmlns="http://www.w3.org/1999/xhtml"
xmlns:h="http://java.sun.com/jsf/html"
xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
xmlns:ui="http://java.sun.com/jsf/facelets">
<h:inputText id="first" pt:placeholder="Test"/>
</ui:composition>

calling the first facelet, its rendered like:

<input id="j_idt4:first" type="text" name="j_idt4:first" placeholder="Test" />
<input id="j_idt4:second" type="text" name="j_idt4:second" />

To me, it looks like a bug?
#### Affected Versions
[2.2.8-14, 2.2.13]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
