### ISSUE TITLE
Issue with escaping for selectOneMenu 

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4143]
I've found out that there is some issue with escaping for selectOneMenu when using selectItems and selectItem. It seems that escaping is not working for that container while it works fine i.e. for selectOneRadio.
By default there is no escape which I think should be as a standard option set to true.
For instance 2nd (f:selectItem) case from h:selectOneRadio uses already escaped characters with different flags showing correct result. The same example presented for h:selectOneMenu as a 2nd case doesn't escaped & and presents it in initial form.
3rd example in h:selectOneMenu when using (f:selectItems) has been broken on 4th record due to lack of escaping. Same sample (4th) for h:selectOneRadio works fine.
I wasn't also able to turn on/off escaping either for h:selectOneRadio (while using f:selectItems - 3,4,5 have the same result) or h:selectOneMenu (while using f:selectItems - 2 has the same result for each setting default/true/false, which shows the initial state of character).

JSF used: 2.1.29-01
Attached files:

*   escapeIssue_selectOneMenu.PNG (screen-shot from example)
*   escapeIssue_bean.txt (backing bean for example)
*   escapeIssue_xmlCodeSnipped.txt (page code for example)
#### Environment
JSF 2.1.29-01
#### Affected Versions
[2.1.29-01]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
