### ISSUE TITLE
XML update parsing error because of the 0x0C (Form Feed) control character

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4145]
<tt>com.sun.faces.util.HtmlUtils</tt> escapes the rendered text, but its <tt>isPrintableControlChar</tt> specifically allows the 0x0C character. This character causes AJAX updates to fail, because it's an invalid character in [XML 1.0](https://www.w3.org/TR/2008/REC-xml-20081126/#charsets):

```
Char	   ::=   	#x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]	/* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */
```
#### Environment
Wildfly 10
#### Affected Versions
[2.2.12]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
