### ISSUE TITLE
OutputLabel.for would not evaluate target correctly

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4176]
I talked about this problem here [http://stackoverflow.com/questions/38608286/poutputlabel-not-marked-as-required-when-target-input-is-inside-composite](http://stackoverflow.com/questions/38608286/poutputlabel-not-marked-as-required-when-target-input-is-inside-composite) and there [https://github.com/primefaces/primefaces/issues/1633](https://github.com/primefaces/primefaces/issues/1633). The problem is not from Primefaces. I just tried with native components like h:outputLabel and h:inputText.

Basically, after getting component referenced by "for" attribute, the component defined as required is not evaluated as such...
#### Affected Versions
[2.2.13, 2.3.0-m06]

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
