### ISSUE TITLE
2.2.1x: Facelet cache doesn't expire / refresh Facelets correctly (changes in composite components not caught for ages, even minutes, in large web apps)

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4184]
_Yes, at least 'major', and critical to me._

Spawned from the "FIXED" [JAVASERVERFACES-4107 Facelet cache doesn't expire / refresh Facelets correctly](https://java.net/jira/browse/JAVASERVERFACES-4107) because although 2.2.8-12 was given as one of the "affected" versions, the "FIX" seems only to have been applied to 2.3.0-m05 (which is not yet compatible with all JSF2 projects) and is (according to recent reports under #4182) still not implemented with correct facelet caching logic anyway.

The symptoms as I experience them with 2.2.8.17:

**On page reload in large JSF2 web apps that use lots of composite components, facelet reloading of composite components is getting "stuck" (in some even cases for minutes)**

Yes, for minutes, sometimes 10 minutes or more. That means do some other work, or make a coffee, or redeploy again and again and again each time the facelets refresh of composite components gets "stuck" in my large web app with lots of composite components. Making JSF2 development utterly painful.

Everything one needs to know about the problem is already reported under:

*   [https://java.net/jira/browse/JAVASERVERFACES-4107](https://java.net/jira/browse/JAVASERVERFACES-4107)

*   [https://java.net/jira/browse/JAVASERVERFACES-4178](https://java.net/jira/browse/JAVASERVERFACES-4178) (but reported for 2.3.0-m06 and for apparently new problems with the caching logic)

Therefore, please finally FIX as soon as possible this serious problem (by which I mean finally fix the facelets caching timing logic once and for all, so that it works for large web apps with many composite components) for the 2.2.8.1x stream (not just for 2.3.0-m0x) because:

*   The ability to use composite components together with the Facelets caching mechanism (i.e. to edit composite components and quickly see changes on page reload without having to redeploy) is absolutely crucial for complex JSF web app development.

*   It does not currently work properly with 2.2.8-17 (as [I've thoroughly tested](http://stackoverflow.com/questions/35680986/mac-jsf-why-are-development-stage-jsf-web-apps-not-always-catching-composite-c/38915829#38915829), and a quick diff shows no change in 2.2.8-18).

*   JSF2 users **should not have to use JSF2.3 milestones already** to get around fundamental problems in 2.2.8-x (and I seemingly can't anyway, lest I spend even more time diagnosing other unrelated problems in JSF2.3.0-m06).

_I remain a huge JSF2 (and Java) fan. But the developers need to take this most seriously; it is because of problems like this one that people turn to PHP._

I thank you all for the things that do work; this one doesn't (yet).
#### Environment
Mac OS X: Yosemite 10.10.5
NetBeans8.1beta or NetBeans8.1
Glassfish4.1 or Glassfish4.1.1
(Primefaces 5.3)
#### Affected Versions
[2.2.8-17, 2.2.8-18]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
