### ISSUE TITLE
Ajax redirect fails silently when extension is used

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4191]
Ajax redirects fail silently when the <tt><extension></tt> element is used in the partial response:

```
<?xml version='1.0' encoding='UTF-8'?>
<partial-response id="j_id1">
<changes>
<extension parameterNamespace="j_id1"></extension>
</changes>
<redirect url="/ajax-redirect-fails-silently-when-extension-is-used-reproducer-1.0-SNAPSHOT/faces/page2.xhtml"></redirect>
</partial-response>
```

If the extension element is removed, redirects work correctly:

```
<?xml version='1.0' encoding='UTF-8'?>
<partial-response id="j_id1">
<redirect url="/ajax-redirect-fails-silently-when-extension-is-used-reproducer-1.0-SNAPSHOT/faces/page2.xhtml"></redirect>
</partial-response>
```

### <a name="Stepstoreproduce%3A"></a>Steps to reproduce:

1\. Clone the reproducer project:

```
git clone https://github.com/stiemannkj1/ajax-redirect-fails-silently-when-extension-is-used-reproducer &&
    cd ajax-redirect-fails-silently-when-extension-is-used-reproducer
```

2\. Build the project with maven:

```
mvn clean install
```

3\. Deploy the project to tomcat:

```
cp target/ajax-redirect-fails-silently-when-extension-is-used-reproducer*.war $TOMCAT_HOME/webapps/
```

4\. Navigate to **<tt>index.xhtml</tt>** ([http://localhost:8080/ajax-redirect-fails-silently-when-extension-is-used-reproducer-1.0-SNAPSHOT/faces/index.xhtml](http://localhost:8080/ajax-redirect-fails-silently-when-extension-is-used-reproducer-1.0-SNAPSHOT/faces/index.xhtml)).

5\. Click on the _page2_ button.

If the bug still exists, an ajax POST will occur with a redirect, but the browser will stay on **<tt>index.html</tt>** instead of navigating to **<tt>page2.xhtml</tt>**.
#### Affected Versions
[2.1.29-06, 2.2.13]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue
