### ISSUE TITLE
DefaultFaceletContext does not override EL 3.0 methods from ELContext.

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4193]
com.sun.faces.facelets.impl.DefaultFaceletContext wraps and extends ELContext, delegating several method invocations to the wrapped ELContext instance.

Beside others EL3.0 methods, ELContext.getImportHandler() is not overridden and thus not delegated.

As a result, DefaultFaceletContext superclass ELContext creates a new ImportHandler and returns that, insted of the one I'd expect to be returned from the wrapped ELContext instance.
The ImportHandler from the wrapped ELcontext has been populated with import classes and packages by my ELContextListener following BalusCs' recipe from
[https://stackoverflow.com/questions/3732608/how-to-reference-constants-in-el#3735006](https://stackoverflow.com/questions/3732608/how-to-reference-constants-in-el#3735006)

Using EL-Expressions in JSF rendering phase seemes not to be concerned by this issue, but as soon as I want to resolve Enums from JSTL tags in my xhtml, like <c:if test="#

{someBean.test(My.ENUM)}

">...</c:if> the enum class My won't be resolved from an instance of DefaultFaceletContext.
#### Environment
Apache Tomcat 8.5.4, JDK 8u73
#### Affected Versions
[2.2.8-18, 2.3.0-m06]

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
