### ISSUE TITLE
Component id changes when an action modifies component tree

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4200]
We use <ui:decorate> to include our components into a form.

On included components we don't define ids just leverage on autogenerated component id for primefaces command button.

For a simplified example we start with 3 components with a <p:commandbutton> on them. Initially component 1 and 3 is included to the form with <ui:decorate> second component is not included. As a result commandbutton action on component 1 we update only the container of the second component and <ui:decorate> includes the component between the existing two components. Commandbutton on component 2 receives the same id as commandbutton on component 3, so there are two buttons in the browser with the same id and the two commandbuttons call the same action.

If we update the whole form after the action instead of the target component we can see the commandbutton 3 receives a new id as well, but partial update riuns the view.

How can we make partial update work with our component structure?
I attach our simplified example of the issue. We don't experience this issue on Websphere with myfaces.

Thanks
#### Environment
Wildfly 10.0.0 Final, Weblogic
#### Affected Versions
[2.2.8-12, 2.2.8-18, 2.3.0-m06]

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
