### ISSUE TITLE
[SIDEPORT 2.3.0] Bug 22666897 - ENABLE CLIENTSTATESAVINGPASSWORD BY DEFAULT IN JSF 1.2

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4211]
Port testcase.

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
