### ISSUE TITLE
JSF double inclusion of same while 

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4236]
Scenario:

1) TestBean with
1.1) List of listItem (only wraps Integer) initially filled with (0,1,2,3,4,5)
1.2) function which clears list and fills (6,7,8,9)
1.3) inner class listItem

public class listItem {
Integer x;

public listItem(Integer x)

{ this.x = x; }

public Integer getX() { return x; }

public void setX(Integer x) { this.x = x; }

}

2) index.xhtml with 2 ui:includes of loop.xhtml and submit button for bean action

3) loop.xhtml with
<c:forEach var="item" items="#

{testBean.list}

">
<h:outputText value="#

{item.x}

"/>
</c:forEach>

startup server
1) Load Page: Result
012345
012345
2) Press Button: Result
6789
6767
3) Press Refresh: Result
6789
6789
#### Affected Versions
[2.3.0-m10]

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
