### ISSUE TITLE
UIData#invokeOnComponent shouldn't proceed if the clientId doesn't start with the UIData clientId

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4262]
The new Search Expressions uses findComponent or invokeOnComponent (as fallback) to get a component by id.

I have a case, where the "value" attribute of the dataTable is not yet completely resolveable and it not yet rendered.

If i use invokeOnComponent to search a component, which is placed outside of the datatable, and it hits the datatable, the dataTable will throw a exception because of the unresolvable EL.
The best way to fix this would be if UIData#invokeOnComponent would check if the clientIdToSearch starts with the UIData clientId.
If it doesn't match, invokeOnComponent in the UIData can be completely skipped.

It's already implemented that way in MyFaces: http://grepcode.com/file/repo1.maven.org/maven2/org.apache.myfaces.core/myfaces-api/2.1.9/javax/faces/component/UIData.java#359

This is likely also a great performance improvement for some cases.

**Comment by larslorenzen** [comment]
Please fix this, it prevents us from migrating to java ee 8 because EL expressions in a datatable are executed even when the table itself is not rendered.

At least the scope of the try/finally (this.setRowIndex(savedRowIndex);) in the invokeOnComponent method should be greatly reduced to only cover the part where the index is set.

**Comment by tandraschko** [comment]
Still not fixed

**Comment by mnriem** [comment]
@tandraschko Can you supply a reproducer and/or fix?

**Comment by tandraschko** [comment]
i dont have time to provide a PR or example but the following IF is missing in Mojarra: https://github.com/apache/myfaces/blob/c891d43c7740dd40c206b0638d23a11b69a0d441/api/src/main/java/jakarta/faces/component/UIData.java#L383

**Comment by BalusC** [comment]
> If i use invokeOnComponent to search a component, which is placed outside of the datatable, and it hits the datatable, the dataTable will throw a exception because of the unresolvable EL.

A reproducer is welcome. I'm having difficulty understanding the issue.

**Comment by BalusC** [comment]
Closing off as stale.
