### ISSUE TITLE
New Component Search Expression keywords are not available in f:ajax when they are the only target

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4265]
The AjaxBehavior object attempts to reduce memory consumption for single-target values by keeping static lists in memory for the "@all", "@form", "@this", and "@none" keywords. However, it does not account for the newly added keywords (i.e. "@parent") in this mode.  For example, the first ajax behavior in the following example causes an exception while the second one is fine:

```xhtml
<h:inputText ...>
    <f:ajax render="@parent" />
    <f:ajax render="@parent @this" />
</h:inputText>
```

This appears to be because of an old check in AjaxBehavior#toSingletonList(...) that immediately threw an error if an unrecognized keyword was entered.

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
