### ISSUE TITLE
Conversion between string and enum not working properly when enum values are subclassed

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4304]
Using Mojarra 2.2.14.

Consider something like this:

    public enum MyEnum {
      ONE {
        public int getValue() { return 1; }
      },
      TWO {
        public int getValue() { return 2; }
      };

      public abstract int getValue();
    }

And a facelet like this:

    <p:selectOneRadio value="#{myBean.myEnumValue}">
      <f:selectItem itemLabel="First" itemValue="ONE" />
      <f:selectItem itemLabel="Second" itemValue="TWO" />
    </p:selectOneRadio>

where `myBean.myEnumValue` is a property of type `MyEnum`. This fails with a conversion error ("value is not valid"), just because the `MyEnum` enumeration values are indeed subclasses of `MyEnum` type. 
I tried to debug to find the root cause and I identified it being in `javax.faces.component.SelectUtils.coerceToModelType(FacesContext, Object, Class)`, which uses the supplied class parameter to try to convert a String like `"ONE"` and `"TWO"` to the corresponding enum value. The problem is that `javax.faces.component.SelectUtils.doConversion(FacesContext, UIComponent, SelectItem, Object, Converter)` is passing the other method, as the target type, the `SelectItem.getValue().getClass()`, which in this case is something like `MyEnum$1` or `MyEnum$2`, and not just `MyEnum`. In fact, `javax.el.ExpressionFactory.coerceToType(Object, Class<?>)` throws an `ELException` saying something like this: "Cannot convert ONE of type class java.lang.String to class com.example.MyEnum$1".

**Comment by mauromol** [comment]
Unless some activity has been done on this, I believe it still stands.

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue
