### ISSUE TITLE
JSF 2.3 fails to support WebSocket with Jetty 9.4.7

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4306]
I tried to test new WebSocket feature with JSF 2.3.3(Glassfish implementation). I used Jetty 9.4.7 as web server and followed this guide(https://javaserverfaces.github.io/whats-new-in-jsf23.html) 

I created a managed bean:

```
    @Named
    @ApplicationScoped
    public class Controller {
    
    	@Inject @Push
        private PushContext cityChannel;
    
    	public void send() {
    		cityChannel.send("test");
    	}
    }

```
updated index.xhtml:

```
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/WEB-INF/layout/standard.xhtml">

	<ui:define name="content">
		<f:websocket channel="cityChannel"
			onmessage="function(message){alert(message)}" />
	</ui:define>
</ui:composition>


```
updated web.xml:

```
    <context-param>
    	<param-name>javax.faces.ENABLE_CDI_RESOLVER_CHAIN</param-name>
    	<param-value>true</param-value>
    </context-param>
    <context-param>
    	<param-name>javax.faces.ENABLE_WEBSOCKET_ENDPOINT</param-name>
    	<param-value>true</param-value>
    </context-param>

```
And created fake endpoint:

```
public class FakeEndpoint extends Endpoint {
    @Override
    public void onOpen(Session session, EndpointConfig config) {}
}

```
Jetty starts up properly but when I open index.xhtml I get a lot of error messages like that:

java.lang.NullPointerException
	at com.sun.faces.cdi.CdiUtils.getBeanReferenceByType(CdiUtils.java:222)
	at com.sun.faces.cdi.CdiUtils.getBeanReference(CdiUtils.java:205)
	at com.sun.faces.push.WebsocketSessionManager.getInstance(WebsocketSessionManager.java:240)
	at com.sun.faces.push.WebsocketEndpoint.onOpen(WebsocketEndpoint.java:88)

So the issue is that WebsocketSessionManager bean cannot been found. And WebSocket feature is not available.

Thanks.

**Comment by Edwardiv1** [comment]
I also have this exact problem using Tomcat 8.5 and JSF 2.3.

**Comment by sergey-morenets** [comment]
> 
> 
> I also have this exact problem using Tomcat 8.5 and JSF 2.3.

@Edwardiv1  The next month Jakarta EE 9 (with JSF 3.0) will be released. I guess we can try to check this issue on the latest RC.

**Comment by arjantijms** [comment]
As per the above comment, the activation of WebSocket was problematic. At the time Tomcat just seemed to did the right thing, but maybe something changed here. For Tyrus (Eclipse WebSocket implementation) I kinda hacked support for it in as per this code:

https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/com/sun/faces/config/FacesInitializer.java#L190

For EE 10 we have the first opportunity to handle this in a spec compliant way. For Mojarra, if needed, we would have to resort to extra hacks.

**Comment by Edwardiv1** [comment]
Is there any update on how to handle this? Does JSF 3.0 work?
I'm still having this issue, now with Tomcat 9.0 and JSF 2.3

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
