### ISSUE TITLE
Multiple browser tabs or windows with the same ViewScoped bean class

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4312]
Using Payara Server  4.1.2.174 with mojarra 2.2.15.

I have a simple Named Bean with scope _javax.faces.view.ViewScoped_.
    
    private String name;
    public String getName()
    {
        return name;
    }
    public void setName(String name)
    {
        this.name = name;
    }
    public String action()
    {
        logger.log(Level.SEVERE, "{0}.action()", this);
        logger.log(Level.SEVERE,"====================");
        logger.log(Level.SEVERE, "name: {0}", getName());
        logger.log(Level.SEVERE,"====================");
        return "submit";
    }
    @PostConstruct
    private void init()
    {
        logger.log(Level.SEVERE, "{0}.init()", this);
    }

So I have a simple _index.xhtml_ page with form.

    <h:form>
      <h:inputText value="#{simpleBean.name}"></h:inputText>
      <h:link value="To submit" outcome="submit"/>
      <h:commandButton value="Welcome Me" action="#{simpleBean.action()}"/>
    </h:form>

I can open _index.xhtml_ in two different browser tabs or windows. So, I have the following log:

> Severe:   solvo.ee.beans.SimpleBean@2adafd68.init()
> Finest:   Handling PostConstructViewMapEvent
> Finest:   Handling PreDestroyViewMapEvent
> Finest:   Destroying @ViewScoped beans from view map: {simpleBean=solvo.ee.beans.SimpleBean@2adafd68}
> Severe:   solvo.ee.beans.SimpleBean@49a86248.init()
> Finest:   Handling PostConstructViewMapEvent
> Finest:   Handling PreDestroyViewMapEvent
> Finest:   Destroying @ViewScoped beans from view map: {simpleBean=solvo.ee.beans.SimpleBean@49a86248}

As we can see there are two different instances of SimpleBean. After that I submit the form of the first tab. 

> Severe:   solvo.ee.beans.SimpleBean@2adafd68.action()
> Severe:   ====================
> Severe:   name: First tab
> Severe:   ====================
> Finest:   Handling PreDestroyViewMapEvent
> Finest:   Destroying @ViewScoped beans from view map: {simpleBean=solvo.ee.beans.SimpleBean@2adafd68}
> Finest:   Handling PreDestroyViewMapEvent
> Finest:   Destroying @ViewScoped beans from view map: {}

If I try to submit form of the second tab the stored earlier instance of SimpleBean (solvo.ee.beans.SimpleBean@49a86248) won't be used, instead the ViewScopeContextManager will create a new instance of SimpleBean class, as we can see in log:

> Severe:   solvo.ee.beans.SimpleBean@4797f115.init()
> Severe:   solvo.ee.beans.SimpleBean@4797f115.action()
> Severe:   ====================
> Severe:   name: Second tab
> Severe:   ====================
> Finest:   Handling PreDestroyViewMapEvent
> Finest:   Destroying @ViewScoped beans from view map: {simpleBean=solvo.ee.beans.SimpleBean@4797f115}
> Finest:   Handling PreDestroyViewMapEvent
> Finest:   Destroying @ViewScoped beans from view map: {}
> 

I have checked the code of the _com.sun.faces.application.view.ViewScopeContextManager.copyViewScopeContextsFromSession_ method and as I understand this behavior is normal.
However If i store request parameters or another important data in my bean I will loose it because the instance will be lost after submitting the first form.

Is there a solution to keep bean associated with the second tab primarily (in my example solvo.ee.beans.SimpleBean@49a86248)?

**Comment by VsevolodGolovanov** [comment]
Just discovered this too after updating to a newer Mojarra version.
ViewScopeContextManager#copyViewScopeContextsFromSession seems broken - it leaks bean instances between different view scopes without trying to identify if it's the same viewmap, without cloning the instances. ViewScoped beans are required to be passivation capable - why would it copy instances instead of serializing and deserializing?
We don't even have cluster failover or session saving. Gonna have to hack a fixed version of ViewScopeContextManager into Mojarra somehow...

**Comment by arjantijms** [comment]
@VsevolodGolovanov I think this one was fixed here: https://github.com/eclipse-ee4j/mojarra/commit/20b85f4a806385bca349974aed5b4292a4aaf1ed

**Comment by VsevolodGolovanov** [comment]
@arjantijms, thanks, that seems to have fixed our problem.

**Comment by arjantijms** [comment]
@VsevolodGolovanov thanks a lot for the confirmation. The fix went through several branches and multiple issues were opened for the bug, so I missed this still open issue.
