### ISSUE TITLE
Make websocket bidirectional

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4356]
I suggest to add a "source" attribute to websocket

 <f:websocket channel="events" source="mySourceId" ...

If source is declared and it refers to an input element, then on every change (or blur?) event of that element it's content will be submitted to the server via the websocket channel.

Using an additional attribute "onSourceEvent" may specify a different event (e.g. key press) to trigger the sending.

**Comment by ggam** [comment]
Can somebody please reopen this issue to revisit it? Indeed the feature proposed by @ren-zhijun-oracle can be easily easily by `f:ajax`, but I'd like to send arbitrary messages from the client to the server using the same channel.

The `f:websocket` component only needs to add a `var` attribute that defines a JS variable to hold the WebSocket connection. In Java, strings would be parsed via JSON-B, and binaries as InputStream. Would be absolutely great if this could be integrated with CDI events that are only listened by the correct bean (view scoped) instance.
