### ISSUE TITLE
Where Can I Report Security Vulnerability?

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4364]
I found a vulnerability in the latest version of Mojarra (vulnerable by default). But I can't find any security related mail from websites. 

Where can I report my finding?

**Comment by orangetw** [comment]
Hi, @ren-zhijun-oracle Could you confirm that I can send the vulnerability report to ren.zhijun@oracle.com?

Thanks!

**Comment by orangetw** [comment]
@ren-zhijun-oracle 
Hi, I have send the report to above email! Thanks :)
