### ISSUE TITLE
The latest version of JSF should have all the new features enabled by default

### ISSUE THREAD

**Issue by manorrock** [eclipse-ee4j/mojarra#4378]
Currently a code snippet like the one below is necessary to get all the features of JSF 2.3. In the next revision of JSF all new behavior should be enabled by default.

    @ApplicationScoped
    @FacesConfig(version = FacesConfig.Version.JSF_2_3)
    public class Jsf23Activator {
        /* 
         * FIXME - Note this class should not be necessary. An issue should be filed 
         *         to make JSF 2.3 mode the default mode of operation.
         */
    }

**Comment by manorrock** [comment]
Any news on this one?

**Comment by arjantijms** [comment]
All features are now enabled by default indeed. The "fake 2.2" mode has been removed.

**Comment by manorrock** [comment]
So this issue can be closed?

**Comment by arjantijms** [comment]
Sure, thx!
