### ISSUE TITLE
Enable Automated Tests to Run With TomEE

### ISSUE THREAD

**Issue by edburns** [eclipse-ee4j/mojarra#4393]

**Comment by arjantijms** [comment]
Good issue!

I've looked at this before. Part of the challenge would be strictly splitting out the JSF universal tests from those that are Mojarra dependent in some way. Partially this has already been done, but partially not. The cactus (unit) tests have some very deep Mojarra implementation dependencies (some are so dependent on a specific implementation of Mojarra that one wonders if it's actually a good test)
