### ISSUE TITLE
Remove JSP support

### ISSUE THREAD

**Issue by manfredriem** [eclipse-ee4j/mojarra#4402]

**Comment by ngriffin7a** [comment]
IMO, removing the JSP feature would necessitate a major bump to JSF 3.0.

**Comment by ngriffin7a** [comment]
@manfredriem @arjantijms IMO, removing the JSP feature would necessitate a major bump to JSF 3.0.

**Comment by bshannon** [comment]
+1

**Comment by arjantijms** [comment]
@ngriffin7a 
>removing the JSP feature would necessitate a major bump to JSF 3.0.

Of course, hence this being targeted at 3.0 (see Milestone in the sidebar of this issue) ;)
