### ISSUE TITLE
Mojarra 2.3 regression: Component rendered in wrong DOM level

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [eclipse-ee4j/mojarra#4407]
I already reported in PrimeFaces side [issue 1](https://github.com/primefaces/primefaces/issues/3859) and [issue 2](https://github.com/primefaces/primefaces/issues/3800) but @tandraschko said it maybe a Mojarra 2.3 problem: "maybe the responsewriter does something wrong or some characters are filtered on rendering"

## Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<h:head>

</h:head>

<h:body>

	<h:form>

		<p:selectOneMenu id="presidio">

			<f:selectItem itemLabel="Nenhum" noSelectionOption="true" />

		</p:selectOneMenu>

	</h:form>

	<h:form id="form">

		<p:commandButton process="@this"
			oncomplete="PF('dlgFolha').show('#{component.clientId}')"
			value="Folha de Ponto" ajax="true" />

	</h:form>

	<p:overlayPanel widgetVar="dlgPdf">
		<h:form id="dlgPdfIn">
			<p:outputPanel>
				<p:panelGrid columns="2" columnClasses="label,value">

					<p:commandButton value="Movimentações" process="@this" />

				</p:panelGrid>
			</p:outputPanel>
		</h:form>
	</p:overlayPanel>
	<p:overlayPanel widgetVar="dlgFolha">
		<h:form id="dlgfolhaIn">
			<p:outputPanel>

				<p:commandButton value="Gerar" ajax="false" />

			</p:outputPanel>
		</h:form>
	</p:overlayPanel>
</h:body>
</html>
```

**Comment by tandraschko** [comment]
As i already said, the overlaypanels should be rendered on the same DOM level but somehow the second overlaypanel is rendered inside the first.
That does not occur in 2.2.

**Comment by erickdeoliveiraleal** [comment]
fixed in https://github.com/primefaces/primefaces/issues/4122

**Comment by VsevolodGolovanov** [comment]
Encountered this problem with PF6.1 and Mojarra 2.3.3.SP1: had a bunch of p:panelGrids in a form, and the hidden ViewState input bizarrely ended up inside two divs:

![image](https://user-images.githubusercontent.com/8070317/66602636-36a58000-ebb3-11e9-8d89-94edc0c0e1ec.png)

And the form tag was actually being rendered unclosed. In the above image Firefox compensated for it, logging actual server response demonstrates the missing closing tag:
![image](https://user-images.githubusercontent.com/8070317/66602817-90a64580-ebb3-11e9-917c-e8f2bd68e137.png)
