### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/mojarra#4439]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by arjantijms** [comment]
Project CI environment has been requested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538674

**Comment by arjantijms** [comment]
@m0mus 

I've been looking at the GPG signing, but I don't quite get one thing. The bugzilla comment said this:

>Note to do that, you will need to follow instructions over here https://wiki.eclipse.org/EE4J_Build

But the instructions there talk about adding "Inject settings-security.xml file into .m2 directory" via the Jenkins job and adding "--pinentry-mode" to the GPG plugin in pom.xml.

But you mention none of that on the wiki here: https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job and your screenshot there shows the json-p job doing something completely different.

Should I ignore https://wiki.eclipse.org/EE4J_Build or should I ignore https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job

Shouldn't one of them be removed since they are so different, or am I missing something?

**Comment by bshannon** [comment]
I agree, this information needs to be consolidated in one place.

**Comment by m0mus** [comment]
@arjantijms

The approach Tomas described on Jsonp page works with old Eclipse infra. The document on Eclipse wiki is related to new Eclipse infra (CloudBees). Configuration of these environments is different. Which infra are you using?

**Comment by m0mus** [comment]
@arjantijms

I agree. I'll update the docs with a statement that it works only with old Eclipse infra. 

Do you want to write a wiki about how to configure ci/cd jobs on the new infra? It would save time for people working on other projects.

**Comment by arjantijms** [comment]
@m0mus 

I'd like to do that, but I'm still struggling myself. The difficulty is that there are only bits and pieces of 
information available, and it's still not clear (to me) what should exactly be done.

The latest revision of https://wiki.eclipse.org/EE4J_Build is a bit clearer already, so thanks to all involved with that.

I'm still not sure what to do with the following script:

```
#!/bin/bash -e

# Execution environment
TOOLS_PREFIX='/shared/common'
MVN_HOME="${TOOLS_PREFIX}/apache-maven-latest"
JAVA_HOME="${TOOLS_PREFIX}/jdk-8_x64-latest"
PATH="${MVN_HOME}/bin:${JAVA_HOME}:/bin:${PATH}"
# Maven plugins
HELP_PLUGIN='org.apache.maven.plugins:maven-help-plugin:2.1.1'

# Check whether top level pom.xml contains SNAPSHOT version
if ! grep '<version>' pom.xml | grep 'SNAPSHOT' ; then
  echo '-[ Missing SNAPSHOT version in POM! ]-------------------------------------------'
  exit 1
fi

# Compute release versions
SNAPSHOT_VERSION=`mvn -B ${HELP_PLUGIN}:evaluate -Dexpression=project.version 2> /dev/null | grep -E '^[0-9]+(\.[0-9]+)+-SNAPSHOT$'`

if [ -z "${RELEASE_VERSION}" ]; then
  if [ -z ${SNAPSHOT_VERSION} ]; then
    echo '-[ Missing required snapshot version number! ]----------------------------------'
  fi
  RELEASE_VERSION=`echo ${SNAPSHOT_VERSION} | sed -e 's/-SNAPSHOT//'`
fi

if [ -z "${NEXT_VERSION}" ]; then
  NEXT_VERSION=`echo ${RELEASE_VERSION} | sed -e 's/\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
  set -f
  NEXT_COMPONENTS=(${RELEASE_VERSION//\./ })
  LAST_INDEX=$((${#NEXT_COMPONENTS[@]} - 1))
  NEXT_COMPONENTS[${LAST_INDEX}]=$((${NEXT_COMPONENTS[${LAST_INDEX}]} + 1))
  NEXT_VERSION=`echo ${NEXT_COMPONENTS[@]} | tr ' ' '.'`'-SNAPSHOT'
fi

RELEASE_TAG="${RELEASE_VERSION}-RELEASE"

echo "Current version: ${SNAPSHOT_VERSION}"
echo "Release version: ${RELEASE_VERSION}"
echo "Next version:    ${NEXT_VERSION}"
echo "Release tag:     ${RELEASE_TAG}"

if [ -z "${SNAPSHOT_VERSION}" -o -z "${RELEASE_VERSION}" -o -z "${NEXT_VERSION}" ]; then
  echo '-[ Missing required version numbers! ]------------------------------------------'
  exit 1
fi

if [ ${DRY_RUN} = 'true' ]; then
  echo '-[ Dry run turned on ]----------------------------------------------------------'
  MVN_ARGS='-DdryRun=true'
else
  MVN_ARGS=''
fi

echo '-[ Prepare branch ]-------------------------------------------------------------'
GIT_ORIGIN=`git remote`
if [[ -n `git branch -r | grep "${GIT_ORIGIN}/${RELEASE_VERSION}"` ]]; then
  if [ "${OVERWRITE}" = 'true' ]; then
    echo "${GIT_ORIGIN}/${RELEASE_VERSION} branch already exists, deleting"
    git push --delete origin "${RELEASE_VERSION}" && true
  else
    echo "Error: ${GIT_ORIGIN}/${RELEASE_VERSION} branch already exists"
    exit 1
  fi
fi
# Always delete local branch if exists
git branch --delete "${RELEASE_VERSION}" && true
git checkout -b ${RELEASE_VERSION}

echo '-[ Release tag cleanup ]--------------------------------------------------------'
if [[ -n `git tag | grep "${RELEASE_TAG}"` ]]; then
  if [ "${OVERWRITE}" = 'true' ]; then
    echo "${RELEASE_TAG} tag already exists, deleting"
    git push --delete origin "${RELEASE_TAG}" && true
  else
    echo "Error: ${RELEASE_TAG} tag already exists"
    exit 1
  fi
fi
# Always delete local tag if exists
git tag --delete "${RELEASE_TAG}" && true

java -version
mvn -version
echo $JAVA_HOME

echo '-[ Run maven release plugin ]---------------------------------------------------'
#    -Dspec_version=${SPEC_VERSION} \
#    -Dimpl_version=${RELEASE_VERSION} \
#    -Dnew_spec_version=${SPEC_VERSION} \
#    -Dnew_impl_version=${RELEASE_VERSION} \
#    -DpushChanges=false \
# Prepare release
mvn -U -C -s /opt/public/hipp/homes/genie.jsonp/.m2/settings-deploy-ossrh.xml \
    ${MVN_ARGS} \
    -Preleasel \
    -DskipTests \
    -Drelease.arguments="-s /opt/public/hipp/homes/genie.jsonp/.m2/settings-deploy-ossrh.xml -Prelease -DskipTests -Dspec_version=${SPEC_VERSION} -Dimpl_version=${RELEASE_VERSION}" \
    -DreleaseProfiles='release' \
    -Dtag="${RELEASE_TAG}" \
    -DreleaseVersion="${RELEASE_VERSION}" \
    -DdevelopmentVersion="${NEXT_VERSION}" \
    -Dspec_version=${SPEC_VERSION} \
    -Dimpl_version=${RELEASE_VERSION} \
    release:prepare release:perform
```

I just copied that from the old example, but is it still needed or not?

And there's all these things like `RELEASE_VERSION` and `NEXT_VERSION` that were in the JSON-P example, but they are not mentioned in https://wiki.eclipse.org/EE4J_Build anymore.

I'd also like to, of course, prevent to accidentally release something to Maven central for real. Or is the job only ever doing a deploy to Sonatype/staging? I didn't find any details about that really, so I'm extra careful there.

Probably it's all not that difficult really, but it's just the not-knowing what's exactly going to happen and what needs to be done that makes it somewhat of a difficult task.

**Comment by arjantijms** [comment]
@m0mus 

It looks like there's a new EE4J master pom now (1.0.2) that targets the new infrastructure, so that at least addresses the question if the master pom is suited for the new infra.

Your "old" script does fail on the new infra;

Given this script:

```
#!/bin/bash -e

echo "STARTING"

# Execution environment
TOOLS_PREFIX='/shared/common'
MVN_HOME="${TOOLS_PREFIX}/apache-maven-latest"
JAVA_HOME="${TOOLS_PREFIX}/jdk-8_x64-latest"
PATH="${MVN_HOME}/bin:${JAVA_HOME}:/bin:${PATH}"

# Maven plugins
HELP_PLUGIN='org.apache.maven.plugins:maven-help-plugin:2.1.1'

# Compute release versions
SNAPSHOT_VERSION=`mvn -B ${HELP_PLUGIN}:evaluate -Dexpression=project.version 2> /dev/null | grep -E '^[0-9]+(\.[0-9]+)+-SNAPSHOT$'`
```

That last line failed. Maybe that's because the new infra has new paths for MVN_HOME etc?

**Comment by arjantijms** [comment]
This task is now almost complete. Just one less failure, which is seemingly a permission issue:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=538674#c17

**Comment by arjantijms** [comment]
And now, finally, it's actually complete.

Job created and executed. Branch https://github.com/eclipse-ee4j/mojarra/tree/2.3.9 created by mojarra bot.

**Comment by pzygielo** [comment]
Please note, despite that [#32](https://jenkins.eclipse.org/mojarra/job/mojarra-release-build/32) completed successfully, the [2.3.9-RELEASE](https://github.com/eclipse-ee4j/mojarra/releases/tag/2.3.9-RELEASE) cannot be built from scratch (starting with empty maven repo) as https://github.com/eclipse-ee4j/mojarra/blob/a784ab28e929a33fe3c43cddcf3ad65fb00d5c64/api/pom.xml#L47 refers to version which isn't produced this time.

**Comment by arjantijms** [comment]
Good catch, I'll address that. Thx!

**Comment by pzygielo** [comment]
Wouldn't it be better if `NEXT_VERSION` was suffixed with `-SNAPSHOT`?

The snippet of script presented [in comment](https://github.com/eclipse-ee4j/mojarra/issues/4439#issuecomment-427449994) seems to care about that, yet [#32](https://jenkins.eclipse.org/mojarra/job/mojarra-release-build/32), [#33](https://jenkins.eclipse.org/mojarra/job/mojarra-release-build/33) bumped version to `2.3.10` directly ([as result of build 32](https://github.com/eclipse-ee4j/mojarra/commit/5acdb66b#r30933175)).
