### ISSUE TITLE
Remove API classes from implementation JAR

### ISSUE THREAD

**Issue by ggam** [eclipse-ee4j/mojarra#4457]
From Java 9 onwards, split packages are not allowed. The API classes should ideally be moved to a different artifact. Since some API classes are implementation specific, Mojarra will need its own API jar for runtime, while users will compile against the standard API artifact.

**Comment by manfredriem** [comment]
Unfortunately what you are asking for is not possible as the packages you are referring to as API classes are NOT API classes. In JSF each vendor is required to deliver their own implementation of the entire stack. Which is why since JSF 2.3 Mojarra has not been delivering an "API" jar.

**Comment by ggam** [comment]
I understand that but I can't see why the implementation jar needs to have
the API classes inside. Does that a Mojarra module would export javax.*
classes to the outside?

If I'm not mistaken, JPA has the exact same situation. Vendors provide
their own version of the API, but the classes are noy inside the
implementation's jar. The same is true on MyFaces as far as I could see.

Besides personal preferences I see problems with a Java module exporting
packages that are from another module.

**Comment by arjantijms** [comment]
@ggam The API in JSF unfortunately contains a lot of code. That code would require copy pasting recurring bits (something which actually happened before, be it in an automated way). So now the Mojarra implementation of the "api" can directly use implementation utility classes.

There's an API generated to compile against though, see the /api folder.

**Comment by arjantijms** [comment]
@ggam Thinking about the exporting of packages. Is it really an issue? Compile time one compiles against the (non functioning) API artefact, while at runtime that API artefact is not there and there's only the Mojarra jar which exports the API packages (whether we also need an artefact that exports impl packages I don't know yet)

**Comment by ggam** [comment]
Thorntail as an example. They don't plan to directly support JSF and
encourage users to pull in the dependency (which is indeed better, since
you can use the latest version).

I will put JSF API and Mojarra as dependencies, with the idea of compiling
against the "official" API. That doesn't work on the module path, since two
different modules have the same packages *exported or not*. So I remove the
JSF API artifact to solve the split packages problem.

But then I go to the next problem: I don't have a "java.faces" module on my
module path anymore. I only have a "org.glassfish.mojarra" module, which
has the same classes (plus some more I think). Now I can't code against an
API, I have to code against Mojarra.

The solution is for that specific Mojarra package of the API to be
distributed on a different artifact, but with the same "java.faces" module
name. That way I will be able to exclude the "javax.faces-api" artifact
while still having a "java.faces" module.

If I need to change to MyFaces, I will only swap Mojarra for MyFaces and it
will download the MyFaces package for the "java.faces" module.

It's the same we have today, but just distributed as a separated artifact.

**Comment by arjantijms** [comment]
One of the problems at the moment is classes like `javax.faces.component.UIData` that contain a lot of non-trivial code like this:

```
private void setRowIndexWithoutRowStatePreserved(int rowIndex){
        // Save current state for the previous row index
        saveDescendantState();

        // Update to the new row index
        //this.rowIndex = rowIndex;
        getStateHelper().put(PropertyKeys.rowIndex, rowIndex);
        DataModel localModel = getDataModel();
        localModel.setRowIndex(rowIndex);

        // if rowIndex is -1, clear the cache
        if (rowIndex == -1) {
            setDataModel(null);
        }

        // Clear or expose the current row data as a request scope attribute
        String var = (String) getStateHelper().get(PropertyKeys.var);
        if (var != null) {
            Map<String, Object> requestMap =
                  getFacesContext().getExternalContext().getRequestMap();
            if (rowIndex == -1) {
                oldVar = requestMap.remove(var);
            } else if (isRowAvailable()) {
                requestMap.put(var, getRowData());
            } else {
                requestMap.remove(var);
                if (null != oldVar) {
                    requestMap.put(var, oldVar);
                    oldVar = null;
                }
```

We need to think how we can put that in the impl without `UIData` having to reference it, and then put in the work to actually do it.

**Comment by ggam** [comment]
I think we are not following each other. That code will still live on the UIData class, but only on the Mojarra's version of it. In the end, there would be 3 artifacts on Maven central:

| Maven Artifact                 |  Java Module |
|--------------------------------|--------------|
| jakarta.faces:javax.faces-api | java.faces   |
| org.glassfish:javax.faces-api  | java.faces   |
| org.apache.myfaces:jsf-api     | java.faces   |

Each artifact will contain their own version. Mojarra will keep that UIData as it's today, while MyFaces will have their version. For compiling, I will use the Jakarta version that can be the same as Mojarra or even have empty methods.

There will just be multiple Maven artifacts providing the same Java module. Of course it would be great to get rid of that need to create different artifacts, but I don't think that's feasible nor that it would provide any value for end users or implementations.
