### ISSUE TITLE
Make the code compile on Java 10+

### ISSUE THREAD

**Issue by ggam** [eclipse-ee4j/mojarra#4461]
At the moment the project doesn't compile with Java 10. Since the build system is still being cleaned up, drastically simplifying it, this is a reminder that at some point this task will need to be accomplished.

**Comment by arjantijms** [comment]
By the time we'll get to this, it's probably going to be JDK 11.

**Comment by ggam** [comment]
Yes, we are in a hurry if we want to make this before Java 11 http://www.java-countdown.xyz/
But hopefully fixing it for Java 10 will still work on the next versions.

**Comment by lasombra** [comment]
I got it working locally with this PR. Hope it's enough to close this issue. :)
