### ISSUE TITLE
binding cause duplicate ID when used in combination of nested inclusion and children component.

### ISSUE THREAD

**Issue by xqvier** [eclipse-ee4j/mojarra#4495]
Hello,

First of all, it maybe a mistake on my part so don't hesitate to correct me.

# The issue

I'm encountering an issue with the following method : `com.sun.faces.facelets.impl.DefaultFaceletContext.generateUniqueId(String)`
I have a particular use case where binding attribute cause some duplicate ID exception :
> java.lang.IllegalStateException: Component ID myNestComponent has already been found in the view.

This issue has been found using version `2.1.28.SP11-redhat-1` (provided by `jboss eap 6.4.14.GA`) but the source code doesn't look any different on the master

# Use case

Here is the use case (In attachment [binding_issue.zip](https://github.com/eclipse-ee4j/mojarra/files/2478702/binding_issue.zip) there is the sample to reproduce it - in the following statement, they will be referenced in parenthesis) :

All of these requirements must be met to encounter the issue :
 - 2 facelet calling each other (`startingPage.xhtml` and `landingPage.xhtml`)
 - Both of them have a `ui:include` to the same facelet (`includedOnBoth.xhtml`)
 - The `landingPage.xhtml` must have a `ui:include` to an other facelet (`includedOnLandingPage.xhtml`)
 - The `includedOnLandingPage.xhtml` must have a `ui:include` to an other facelet (`nestedInclusion.xhtml`)
 - The `includedOnBoth.xhtml` must have component which can have children (`h:panelGrid`) and this component's binding attribute should be set(`binding="#{testBean.panel}"`)
 - The component must have a children (`h:outputText`) with a fixed id (`id="nestedComponent"`)
  
 
The issue then appear when going from `startingPage.xhtml` to `landingPage.xhtml`.

# Into the code 

This is where you have to double check what I'm writing.
After some code searching, i found out that the method `com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(FaceletContext, UIComponent)` rely on `com.sun.faces.facelets.impl.DefaultFaceletContext.generateUniqueId(String)` and `com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.findChild(FaceletContext, UIComponent, String)` to see if the component was already in the tree and shouldn't be added to the parent again.
It appears that the `generateUniqueId` method is based on the `faceletHierarchy.size()` which in this aforementioned case is different between the 2 facelets.

So what happens is that in `javax.faces.event.PhaseId.RESTORE_VIEW`, the `startingPage.xhtml` view is built and a uniqueId is generated for the `h:outputText` with a prefix based on its `faceletHierarchy` (ie `startingPage.xhtml` + `includedOnBoth.xhtml`).
At this time, the component is not in the tree yet so there is no issue, it will be added as it should.

Then, in the `javax.faces.event.PhaseId.RENDER_RESPONSE` the `landingPage.xhtml` view is built and a uniqueId is generated for the `h:outputText` with a prefix based on its faceletHierarchy (ie `landingPage.xhtml` + `includedOnLandingPage.xhtml` + `nestedInclusion.xhtml`)
At this time, the `h:panelGrid` (aka the parent in the `apply`method) is not in the tree but already has its children because of the binding mechanism (method `com.sun.faces.application.ApplicationImpl.createComponentApplyAnnotations(FacesContext, ValueExpression, String, String, boolean)` found the component and didn't create it)

Thus making the `findChild` method not matching both generated uniqueId and adding again the component to the parent. 

# Workaround

For the time being, as i won't be able to update to a later version once fixed (if it is a legit bug and fixed), I'll try to find a workaround to not use binding but I'm open to suggestion.

Regards,

**Comment by BalusC** [comment]
Duplicate re-reported as https://github.com/eclipse-ee4j/mojarra/issues/6001 and fixed over there.
