### ISSUE TITLE
NPE on POST to same ViewId in different tabs

### ISSUE THREAD

**Issue by codylerum** [eclipse-ee4j/mojarra#4509]
I'm been running into an occasional NPE in production with JSF after migrating from Wildfly 11 to Wildfly 14.0.1 ( Mojarra 2.2.13.SP4 -> 2.3.5.SP2 ) and I believe I've tracked down a small demo project that duplicates the issue. I've set the project to JSF 2.2 so it will deploy on both WF 11 and WF 14.

The basic problem is that when two pages with the same view id are loaded in separate tabs. From there is one of the tabs is posted and the result navigates to a different view id all references to that view id are removed from the view map. If the post does not navigate to a different view id then all works normally.

My assumption is that when the post navigates away to a new view id any reference to any page with the same view id is removed from the view map. This did not occur in Wildfly 11.

Additional clue is that even though the viewmap reference is removed the view scoped beans referencing it are not destroyed.

Demo project at https://github.com/codylerum/demos/tree/ee7/jsf-npe

Also Filed with Wildfly @ https://issues.jboss.org/browse/WFLY-11275

To Reproduce:

1. Deploy to Wildfly 14.0.1.Final
2. Browse to http://localhost:8080/demo
3. Click on the order 1 and order 2 links to open in seperate tabs.
4. Click on the check order status from either tab. Works Fine.
5. Click on the other check order status from the other tab. This will result in an NPE.

If the same steps are repeated on Wildfly 11 (Mojarra 2.2.13.SP4) there will be no issues.

**Comment by arjantijms** [comment]
This very much sounds like this problem: https://github.com/payara/Payara/issues/2506

If you want, can you test on the latest Payara 5.184 release?

**Comment by codylerum** [comment]
@arjantijms I can confirm that this works correctly in Payara 5.1.84

I'm not clear which Mojarra version should contain this fix? I know things are still in flux.

**Comment by codylerum** [comment]
@arjantijms Can you shed some light on if this is fixed in any version of mojarra 2.3? If not I would like to help move that along so Wildfly can get this rolled into their upcoming Wildfly 16 release

**Comment by arjantijms** [comment]
@codylerum it's fixed in the Mojarra 2.3 version that ships with Payara, so indeed it's only in that patched version. 

Because of the 2.3.9 release and various difficulties around it, I didn't push this change upstream yet, but it's one of the first things planned for 2.3.10. Of course the WildFly maintainers can always cherry pick this single fix and incorporate it in their (patched) version of Mojarra.

The fix can be found here: https://github.com/payara/patched-src-mojarra/commit/6914e34cddc3437c22c4b99fb4043e25b5e4cfd3#diff-9227212e21a5831a6e82023e8d621b21R181

**Comment by codylerum** [comment]
Thanks. I've created https://github.com/jboss/mojarra/pull/26 for jboss to pull into their patched mojarra

**Comment by erickdeoliveiraleal** [comment]
this issue was fixed in Payara https://github.com/payara/Payara/pull/3104 but not in official mojarra?

**Comment by erickdeoliveiraleal** [comment]
@manfredriem can you reopen this?

**Comment by melloware** [comment]
I am looking at the source code of 2.3 and it looks like this fix was implemented so this issue can be closed.
