### ISSUE TITLE
Run Mojarra tests via Eclipse Jenkins

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/mojarra#4520]

**Comment by manfredriem** [comment]
What is the URL for the Jenkins for Mojarra?

**Comment by edbratt** [comment]
https://jenkins.eclipse.org/mojarra/

**Comment by manfredriem** [comment]
I have tried multiple times, but I keep getting Gateway Timeout errors so I am reassigning it to Arjan, hopefully you will have more success
