### ISSUE TITLE
CTS Test failures in javax.faces.webapp package

### ISSUE THREAD

**Issue by anajosep** [eclipse-ee4j/mojarra#4525]
01-06-2019 17:28:46:  SVR: ********** BEGIN VALIDATE PACKAGE 'javax.faces.webapp' **********

01-06-2019 17:28:46:  SVR: ********** VALIDATE IN STATIC MODE - TO CHECK CONSANT VALUES ****
01-06-2019 17:28:46:  SVR: Static mode supports checks of static constants values 
01-06-2019 17:28:46:  SVR: ********** Status Report 'javax.faces.webapp' **********

01-06-2019 17:28:46:  SVR: SignatureTest report
Base version: 2.3_se8
Tested version: 2.3_se8
Check mode: src [throws normalized]
Constant checking: on

Warning: /vi/glassfish5/glassfish/modules/jakarta.json.jar specified twice in the classpath.

Added Methods
-------------

javax.faces.webapp.FacesServlet:        method public final void javax.faces.webapp.FacesServlet.initializeAllowedKnownHttpMethods(java.util.List<java.lang.String>)

01-06-2019 17:28:46:  SVR: ********** Package 'javax.faces.webapp' - FAILED (STATIC MODE) **********
01-06-2019 17:28:46:  SVR: 

01-06-2019 17:28:46:  SVR: ********** VALIDATE IN REFLECTIVE MODE  ****
01-06-2019 17:28:46:  SVR: Reflective mode supports verification within containers (ie ejb, servlet, etc)
01-06-2019 17:28:46:  SVR: ********** Status Report 'javax.faces.webapp' **********

01-06-2019 17:28:46:  SVR: SignatureTest report
Base version: 2.3_se8
Tested version: 2.3_se8
Check mode: src [throws normalized]
Constant checking: on

Warning: /vi/glassfish5/glassfish/modules/jakarta.json.jar specified twice in the classpath.

Added Methods
-------------

javax.faces.webapp.FacesServlet:        method public final void javax.faces.webapp.FacesServlet.initializeAllowedKnownHttpMethods(java.util.List<java.lang.String>)

**Comment by arjantijms** [comment]
@m0mus These two were fixed quite some time ago. Wonder how they could have come back, but I'll fix again. Thx!

**Comment by arjantijms** [comment]
Looked it up, they were fixed in Master and not in EE4J_8:

* https://github.com/eclipse-ee4j/mojarra/commit/1b434748d9239f42eae8aa7d37d7a0930c061e24
* https://github.com/eclipse-ee4j/mojarra/commit/93a580d093e3bc6ff0bb5f314544baa73c0fe0a2

**Comment by arjantijms** [comment]
Rebuild and restaged:

* https://oss.sonatype.org/content/repositories/staging/org/glassfish/jakarta.faces/2.3.9/
* https://oss.sonatype.org/content/repositories/staging/jakarta/faces/jakarta.faces-api/2.3.1/

**Comment by arjantijms** [comment]
@anajosep @m0mus Can you run the TCK/CTS again?

**Comment by edbratt** [comment]
Does Mojarra have a process for running Mojarra against the stand-alone 
JSF TCK?

For CTS, the staged update with JSF changes needs to be picked up in an 
Eclipse GlassFish Build.

@romain-grecourt what's the best way to track that?

**Comment by romain-grecourt** [comment]
It's not easily trackable since the artifacts are re-released. There is no source code change in GF.
The only way I can think off is to look at the checksum of the modules inside the GF distribution and compare it with what's in OSSRH.
