### ISSUE TITLE
In the JSF application, when "reset" or "button" (except "submit") is specified in the "type" attribute of the <h:commandButton> tag, "submit" processing is executed. 

### ISSUE THREAD

**Issue by micRo-wlY** [eclipse-ee4j/mojarra#4536]
In the HTML style, when the reset button and the generic button (press the click/enter key) are executed, the submit processing is not executed.
However, in the JSF mounting of glassfish, if the above conditions are met, the submit processing will be executed when the reset button and the button (press the click/enter key) are executed.
Specifically, when the following conditions are met.

●Condition 1

1. The <h:form> element contains child elements that match <h:commandButton> below.
    a) In the "type" attribute, "reset" or "button" (*1) is specified.
    b) There are <f:param> elements in the child elements.
2. The <h:form> element and the element of the HTML form do not contain the <f:ajax> element.
3. Click link or the button corresponding to the element of 2) (or press the enter key).

●Condition 2

1. The <h:form> element contains child elements that match <h:commandButton> below.
    a) In the "type" attribute, "reset" or "button" (*1) is specified.
    c) There are <f:param> elements in the child elements.
2. The <h:form> element and the element of the HTML form contain the <f:ajax> element.
3. Click link or the button corresponding to the element of 2) (or press the enter key).

*1) When there is no attribute, it is judged that "submit" is specified.

[testjsf.zip](https://github.com/eclipse-ee4j/mojarra/files/2811059/testjsf.zip)
I made a test app that contains the above conditions.

After investigation, I carried out the following amendments. By testing the test app, after the correction, it can avoid this problem.

Amendments：
●Condition 1
1.Class to be corrected

> com.sun.faces.renderkit.RenderKitUtils

2.Method to be corrected

> getChainedHandler

3.Specific modification
```
    private static String getChainedHandler(FacesContext context,
                                            UIComponent component,
                                            List<ClientBehavior> behaviors,
                                            Collection<ClientBehaviorContext.Parameter> params,
                                            String behaviorEventName,
                                            String userHandler,
                                            String submitTarget,
                                            boolean needsSubmit) {
        ...
        boolean  submitting = appendBehaviorsToChain(builder,
                                                     context,
                                                     component, 
                                                     behaviors, 
                                                     behaviorEventName,
                                                     params);

        boolean hasParams = ((null != params) && !params.isEmpty());
+       String type = (String) component.getAttributes().get("type");  //Get the "type" attribute of the button

        // If we've got parameters but we didn't render a "submitting" 
        // behavior script, we need to explicitly render a submit script.

-       if (!submitting && (hasParams || needsSubmit){
+       if (!submitting && (hasParams || needsSubmit) && "submit".equals(type)) { //Add the judgment whether the "type" attribute is "submit"

            String submitHandler = getSubmitHandler(context, 
                                                    component,
                                                    params,
                                                    submitTarget,
                                                    false);
```
																							
●Condition 2
1.Class to be corrected

> com.sun.faces.renderkit.html_basic.AjaxBehaviorRenderer

2.Method to be corrected

> buildAjaxCommand

3.Specific modification

```
    private static String buildAjaxCommand(ClientBehaviorContext behaviorContext,
                                           AjaxBehavior ajaxBehavior,
                                           boolean namespaceParameters) {

        // First things first - if AjaxBehavior is disabled, we are done.
        if (ajaxBehavior.isDisabled()) {
            return null;
        }        

        UIComponent component = behaviorContext.getComponent();

+       String type = (String) component.getAttributes().get("type");  //Get the "type" attribute of the button
+       if (!"submit".equals(type)) {                                  //Add the judgment whether the "type" attribute is "submit"
+           return null;
+       } 

        String eventName = behaviorContext.getEventName();
```

**Comment by micRo-wlY** [comment]
After we corrected it according to our amendment, we reproduced it according to the reproduction step, and found that we could avoid the problem.
I hope someone can confirm this question and judge the rationality of this amendment.
Is there anyone who can respond as quickly as possible, thanks very much. :)

**Comment by micRo-wlY** [comment]
After we corrected it according to our amendment, we reproduced it according to the reproduction step, and found that we could avoid the problem.
I hope someone can confirm this question and judge the rationality of this amendment.
Is there anyone who can respond as quickly as possible, thanks very much. :)

**Comment by micRo-wlY** [comment]
After we corrected it according to our amendment, we reproduced it according to the reproduction step, and found that we could avoid the problem.
I hope someone can confirm this question and judge the rationality of this amendment.
Is there anyone who can respond as quickly as possible, thanks very much. :)

**Comment by micRo-wlY** [comment]
After we corrected it according to our amendment, we reproduced it according to the reproduction step, and found that we could avoid the problem.
I hope someone can confirm this question and judge the rationality of this amendment.
Is there anyone who can respond as quickly as possible, thanks very much. :)

**Comment by micRo-wlY** [comment]
After we corrected it according to our amendment, we reproduced it according to the reproduction step, and found that we could avoid the problem. I hope someone can confirm this question and judge the rationality of this amendment. Is there anyone who can respond as quickly as possible, thanks very much. :)

**Comment by micRo-wlY** [comment]
After we corrected it according to our amendment, we reproduced it according to the reproduction step, and found that we could avoid the problem. 
I hope someone can confirm this question and judge the rationality of this amendment.
Is there anyone who can respond as quickly as possible, thanks very much. :)

**Comment by 141801** [comment]
hope someone can solve the problem ,thanks very much!
