### ISSUE TITLE
ViewParam field is Null after click primefaces commandbutton (Mojarra 2.2 dont)

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [eclipse-ee4j/mojarra#4550]
## 1) Environment
Wildfly 16
Mojarra 2.3 not working
Mojarra 2.2 works
using javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL in web.xml
I opened PrimeFaces issue, but they told me this is Mojarra 2.3 bug.

## 2) Expected behavior

Value should remain, even with javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL set to true

## 3) Actual behavior
value is null

## 4) Steps to reproduce
access: http://localhost:8080/primefaces-test/?tipo=U&test=Bah
click first button, click second button

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">
<f:metadata>

	<f:viewParam name="test" value="#{testView.testString}" />
	<f:viewAction action="#{testView.inicializar}" />

</f:metadata>
<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

	<h:form id="cadastro">
		<h:commandButton value="click me"
			action="#{testView.inserirNaLista()}">
			<f:ajax execute="@form" render="@form" />
		</h:commandButton>
		<p:commandButton
			value="click me - 2 (this button causes the null value)"
			action="#{testView.inserirNaLista()}" />

	</h:form>


</h:body>
</html>
```

## 6) Sample bean
```
package org.primefaces.test;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {
	private String testString;

	public void inicializar() {
		System.out.println("initializing: " + testString);

	}

	public void inserirNaLista() {
		System.out.println(testString);
	}

	public String getTestString() {
		return testString;
	}

	public void setTestString(String testString) {
		this.testString = testString;
	}

}

```

https://github.com/erickdeoliveiraleal/primefaces-test/tree/update
https://github.com/primefaces/primefaces/issues/4635

**Comment by soul2zimate** [comment]
Hi @arjantijms, Is this be planned for a fix ? 
It seems that this happens due to the fix made for UIViewParameter.java in https://github.com/javaserverfaces/mojarra/commit/4c74d1f8cff1a60dafcb4df805ab2de935e7404f in Mojarra 2.3

**Comment by arjantijms** [comment]
> javaserverfaces/mojarra@4c74d1f in Mojarra 2.3

Oh wow, that's a long time ago. I remember that one as a rather nasty edge case. I'll talk to Bauke first about this then.

**Comment by soul2zimate** [comment]
I have looked at the commit mentioned in my last comment. 
Basically, javaserverfaces/mojarra@4c74d1f  changed `submittedValue` from `null` to `""` if `javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL` is configured to true
```
            if (myConsiderEmptyStringNull(context)) {
                // JAVASERVERFACES_SPEC_PUBLIC-1329: If the EMPTY_STRING_SUBMITTED_VALUES_AS_NULL
                // config is set, ensure that logic gets a chance to be executed
                // in UIInput.processValidators().
                if (null == submittedValue) {
                    setSubmittedValue("");
                }
            }
```
And it essentially makes a difference in `validate` [method](https://github.com/eclipse-ee4j/mojarra/blob/2.3.14-RELEASE/impl/src/main/java/javax/faces/component/UIInput.java#L982-#L991) in UIInput.java 

```
        // Submitted value == null means "the component was not submitted
        // at all".
        Object submittedValue = getSubmittedValue();
        if (submittedValue == null) {
            if (isRequired() && isSetAlwaysValidateRequired(context)) {
                // continue as below
            } else {
                return;
            }
        }
```
If `submittedValue` is null, it returns immediately as it considers `the component was not submitted at all`.

However, `submittedValue` becomes `""`, so it continues to executed in order to validate and set the new values.

**Comment by soul2zimate** [comment]
@BalusC Would you mind to take a look on my comments ?

**Comment by soul2zimate** [comment]
Hi, Is there any plan to fix this issue in later version?

**Comment by erickdeoliveiraleal** [comment]
Finally I can migrate my project to 2.3, thank you @soul2zimate
