### ISSUE TITLE
Resoures#encodeAll doesn't work anymore since 2.3.x

### ISSUE THREAD

**Issue by tandraschko** [eclipse-ee4j/mojarra#4553]
Original ticket: https://github.com/javaserverfaces/mojarra/issues/4354

In the PF HeadRenderer, we get all resources and call #encodeAll on them, to render the script/style tag.
This worked fire in every Mojarra and MyFaces version but it seems that Mojarra 2.3 doesn't render the tags when you are in ajax request with update=@ALL.
The weird thing is that viewRoot#getComponentResources delivers all correct resources but #encodeAll does nothing.

It's probably related to the dynamic resource handling and the behavior is ok from mojarra perspective.
The difference is that update=@all in mojarra doesn't replace the head content but we do in PF to fully implement the update=@all.

It would be a great enhancement to restore the old behavior that a direct call to #encodeAll still renders the style/script tags.
Also it doens't hurt....

**Comment by bmaxwell** [comment]
Does Mojarra consider this issue a bug in Mojarra? Or were other component frameworks such as PrimeFaces doing something they should not?  And is there a fix or enhancement coming to restore the 2.2 behavior?
