### ISSUE TITLE
Lost component value after validation failure with multiple forms

### ISSUE THREAD

**Issue by matinh** [eclipse-ee4j/mojarra#4562]
I reported [PrimeFaces issue #4765](https://github.com/primefaces/primefaces/issues/4756), which turned out to happen only with Mojarra and not with MyFaces. So PrimeFaces guys asked me to report the issue at Mojarra, what is what I'm doing now.

All details, including a complete reproducer, can be found at the specified PrimeFaces issue.

**Comment by matinh** [comment]
There is also https://github.com/primefaces/primefaces/issues/4771 which might be related and has also a reproducer example linked to it.

**Comment by kguelzau** [comment]
Is there Workaround for this?

**Comment by melloware** [comment]
Updated reproducer:
[pf-4771.zip](https://github.com/eclipse-ee4j/mojarra/files/8774514/pf-4771.zip)

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
