### ISSUE TITLE
Rename packages javax.* to jakarta.*

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/mojarra#4564]
Negotiations between Eclipse and Oracle have unfortunately not resulted in a workable agreement. As a result we can't publish any changed type in the `javax` namespace.

The package that we -can- use is `jakarta`, so we should move to that ASAP.

See https://eclipse-foundation.blog/2019/05/03/jakarta-ee-java-trademarks/

**Comment by tandraschko** [comment]
@arjantijms AFAICS it's still not sure whats the target JakartaEE version in generell. So still unsure if we need to deliver a 2.3 with jakarta namespaces or we can just do it in 3.x?

**Comment by chkal** [comment]
> So still unsure if we need to deliver a 2.3 with jakarta namespaces or we can just do it in 3.x?

Jakarta EE 8 will be compatible with Java EE 8. So Jakarta EE 8 will still use the (unmodified) `javax` package namespace.

**Comment by tandraschko** [comment]
Not sure whats the official statement but there are many discussions on the web which makes a JakartaEE8 with jakarta* namespace the better way.
