### ISSUE TITLE
JSF 3.x: API enhancements for Java8

### ISSUE THREAD

**Issue by tandraschko** [eclipse-ee4j/mojarra#4568]
It's a ticket for a colletion of small API improvements for Java8 programming style:

1) StateHelper: public Object eval(Serializable key, Object defaultValue);
    Allow a Supplier as defaultValue

2) PhaseListener
    Make afterPhase and beforePhase optional with default methods
    Most of the times only 1 of both is used

3) make Renderer generic/parametrized, to avoid ensless casts of the UIComponent in e.g. decode and encode

**Comment by tandraschko** [comment]
@arjantijms are you ok with those 2 small improvements? I would prototype it in MyFaces first and then provide a PR for Mojarra later

**Comment by arjantijms** [comment]
They look very good, especially the default methods in PhaseListener should be a given yes.

**Comment by tandraschko** [comment]
creates in the spec issue tracker
