### ISSUE TITLE
Prepare Jakarta Server Faces for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/mojarra#4582]
### Instructions

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Submit a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by arjantijms** [comment]
PR for Javadoc updates: https://github.com/eclipse-ee4j/mojarra/pull/4602

**Comment by arjantijms** [comment]
[Staging release](https://oss.sonatype.org/content/repositories/staging/org/glassfish/jakarta.faces/2.3.13/)

**Comment by arjantijms** [comment]
[tmp TCK results](https://jenkins.eclipse.org/mojarra/job/2_mojarra-run-tck-against-staged-build/lastSuccessfulBuild/artifact/faces-tck/bin/summary.txt/*view*/)

**Comment by arjantijms** [comment]
[GH pages active](https://eclipse-ee4j.github.io/mojarra)

**Comment by arjantijms** [comment]
[PR1](https://github.com/jakartaee/specifications/pull/82)
[PR2](https://github.com/jakartaee/specifications/pull/83)
