### ISSUE TITLE
JSF 3.x: add "release" method to ExternalContext

### ISSUE THREAD

**Issue by tandraschko** [eclipse-ee4j/mojarra#4622]
simple enhancement, would remove some annoying internal MyFaces API and it's usefull (FaceContext should then call ExternalContext#release on it's own #release)

@arjantijms 
please ping me if i can provide a PR
also for #4568

All other JSF 3.x needs some dicussions before

**Comment by arjantijms** [comment]
Sounds good, indeed for ExternalContext.

ps

I have heard people ask whether we should really need an External context, and whether this level of abstraction should not be moved elsewhere (like to Portlet), but for the time being it's in Jakarta Faces of course.

**Comment by tandraschko** [comment]
yep, i see
but thats a bigger change then
i will provide a PR for the release method later :)

**Comment by tandraschko** [comment]
@arjantijms 
i will do it for MyFaces now
if you decided to rebase the Mojarra master, please let me know
i will create a PR for Mojarra then

**Comment by tandraschko** [comment]
moved to spec issue tracker
