### ISSUE TITLE
Memory leak in FlashScope - expired elements are not cleared

### ISSUE THREAD

**Issue by spyrkob** [eclipse-ee4j/mojarra#4631]
Objects in FlashScope is not cleared and keep accumulating even if POST-REDIRECT-BACK is completed.

If we put a huge object to FlashScope continuously as the following code, Java heap space will be exhausted soon.

```
@Model
public class Action {

    private static final int oneHundredMB = 1024 * 1024 * 100;

    public String next() {
        Flash flash = FacesContext.getCurrentInstance().getExternalContext().getFlash();
        flash.putNow("huge", new byte[oneHundredMB]);
        return "index.xhtml?faces-redirect=true";
    }
}

```
When OutOfMemoryError is happened, flashInnerMap field in com.sun.faces.context.flash.ELFlash is bloated.

```
Class Name                                                             | Ref. Objects | Shallow Heap | Ref. Shallow Heap | Retained Heap
-----------------------------------------------------------------------------------------------------------------------------------------
java.lang.Thread @ 0xeea24380  default task-1 Thread                   |            1 |          120 |                64 |        20,800
'- <Java Local> com.sun.faces.context.flash.ELFlash @ 0xee9e4608       |            1 |           40 |                64 |            64
   '- flashInnerMap java.util.concurrent.ConcurrentHashMap @ 0xee9e4630|            1 |           64 |                64 |   314,574,048
-----------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by spyrkob** [comment]
One solution I found is expiring the 'previous' map at the end of ResponseRender phase.
If I understand the code right, at this point 'previous' map is either no longer needed - the values to pass to next cycle are in 'next' map at this point.
I tried to write some simple tests and I didn't see any regressions, but I don't know if there are any cases I missed.

**Comment by arjantijms** [comment]
To be absolutely honest, none of the current Mojarra developers really dares to touch that code :(

It's all just utterly weird and seems to have been coded for something else initially, then somehow re-used to implement The Flash.

**Comment by spyrkob** [comment]
@arjantijms it does look confusing :) 

I found my initial idea was wrong and it caused some regression. Instead less invasive fix might be making sure the 'next' map is removed from innerMaps during cookie decoding. Currently it's just set to null which means it's never properly cleared up.
Updated the PR

**Comment by erickdeoliveiraleal** [comment]
please, merge it into 2.3 branch
