### ISSUE TITLE
The @FacesValidator, @FacesComponent, @FacesConverter and @FacesBehavior injection is not supported

### ISSUE THREAD

**Issue by caim2015** [eclipse-ee4j/mojarra#4645]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number):V5.1
* JDK version:8
* OS:windows or linux
* Database:none

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
I referenced the following link to build a java test.
https://github.com/javaserverfaces/mojarra/blob/2.2.7/jsf-ri/systest/src/com/sun/faces/annotation/AnnotatedValidator.java

The test code is shown as following.
<pre>
<code class="java">
@FacesValidator(value = "AnnotatedValidator")
public class AnnotatedValidator implements Validator {

    public void validate(FacesContext context, UIComponent component, Object value) throws ValidatorException {
        return;
    }

    @Resource(name = "welcomeMessage")
    private String welcomeMessage;      

    public String getWelcomeMessage() {
        return "AnnotatedValidator " + welcomeMessage;
    }

    @PostConstruct
    public void preInit() {
        System.out.println("@PostConstruct from AnnotatedValidator");    
    }

}
</code>
</pre>

I run the test code in GlassFish4.1(JSF 2.2.7), and turns out that it can get the value of "welcomeMessage" which is defined in web.xml by using the @Resource.
However, I run the same code in GlassFish5.1(JSF 2.3.9), there is no value setted for the "welcomeMessage"."welcomeMessage" becomes null.

It's the same result when I use @FacesComponent, @FacesConverter or @FacesBehavior annotation in java test code.

Now that, I have the question:
Why the @FacesValidator, @FacesComponent, @FacesConverter and @FacesBehavior injection is not supported in GlassFish5.1?

**Comment by tandraschko** [comment]
You need @FacesValidator(..., managed=true). If that works, please close the issue here.

**Comment by caim2015** [comment]
> 
> 
> You need @FacesValidator(..., managed=true). If that works, please close the issue here.

Thank you for your reply! 
I hava tried it.It doesn't work.

**Comment by caim2015** [comment]
Hi,I think I found the reason.
Starting from the JSF2.2.8-04, the following code is deleted.
<pre>
https://github.com/javaserverfaces/mojarra/commit/93011dc57a07063094d70906dae12ec760904614#diff-92a6ce2db2d9b6ac520aea86b4fcaf84
com/sun/faces/application/ApplicationImpl.java

if (map.hasAnnotations(key)) {
            InjectionProvider injectionProvider = associate.getInjectionProvider();
            try {
                injectionProvider.invokePostConstruct(result);
            } catch (InjectionProviderException ex) {
               LOGGER.log(Level.SEVERE, "Unable to invoke @PostConstruct annotated method on instance " + key, ex);
               throw new FacesException(ex);
            }

            try {
                injectionProvider.inject(result);
            } catch (InjectionProviderException ex) {
               LOGGER.log(Level.SEVERE, "Unable to inject instance" + key, ex);
               throw new FacesException(ex);
            }
        }
</pre>
But,I'm not sure why it was deleted .
Please give some thoughts on this.

**Comment by chris21k** [comment]
There is the (old) open bug entry #4245 about that. This thread also contains a workaround (Jul 30, 2017). However, it would be nice to have a real fix.

Chris

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
