### ISSUE TITLE
Fix for false positive warnings "Unable to safely determine which FactoryManager instance to use" was lost during migration to eclipse-ee4j repo

### ISSUE THREAD

**Issue by spyrkob** [eclipse-ee4j/mojarra#4660]
It seems fix from https://github.com/javaserverfaces/mojarra/commit/6864ca0c10abb2a193dc2c31f47af440e5070140 has been lost during migration to eclipse repositories.

**Comment by BalusC** [comment]
It's in 2.3/3.0/4.0 now.
