### ISSUE TITLE
Removing Facets should be reapplied as dynamic action correctly

### ISSUE THREAD

**Issue by gndrm** [eclipse-ee4j/mojarra#4664]
As of today, one cannot write components, that remove a facet from the component tree without adding it back.

Removing a facet does not take the facet name into account (see DynamicAddRemoveListener#handleRemove). The ComponentStruct Object is created without the facet name, so reapplying this remove action in FaceletViewHandlingStrategy#reapplyDynamicRemove results in the following line to be executed:
`parent.getChildren().remove(child)`
clearly this line returns false, since child is a facet and cannot be removed from the children list.

So to fix this:
- ComponentStruct for delete actions has to be extended 
- FaceletViewHandlingStrategy#reapplyDynamicRemove should check, whether facetName is not null and try to remove a facet in this case

**Comment by BalusC** [comment]
All tests passed.

**Comment by BalusC** [comment]
Upmerged into 3.0/4.0 as well. Closing off.

Thank you for your contribution!
