### ISSUE TITLE
IdMapper can create repeated ids in clustered environments

### ISSUE THREAD

**Issue by rmartinc** [eclipse-ee4j/mojarra#4677]
We have a complicated issue using clustered env. I'm going to attach a `test-jsf.war` with a simple `view1.jsf` page. The problem is the following:

1. Initially the user goes to node1 and the view is created. As it's the first time all the elements are created new and the IdMapper uses a new cache starting from 0. So the elements are t1, t2,... For example with that simple view:

```
id:j_id1
type:javax.faces.component.UIViewRoot
value = null
  id:j_idt1
  type:com.sun.faces.facelets.compiler.UIInstructions
  value = null
  attr = com.sun.faces.facelets.MARK_ID : -1475365623_57f04af7
  id:j_idt2
  type:javax.faces.component.UIOutput
  value = null
  attr = com.sun.faces.facelets.MARK_ID : -1475365623_57f04afc
    id:j_idt3
    type:com.sun.faces.facelets.compiler.UIInstructions
    value = null
    attr = com.sun.faces.facelets.MARK_ID : -1475365623_57f04aed
  id:j_idt4
  type:javax.faces.component.html.HtmlBody
  value = null
  attr = com.sun.faces.facelets.MARK_ID : -1475365623_57f04ad2
    id:j_idt5
    type:javax.faces.component.html.HtmlForm
    value = null
    attr = com.sun.faces.facelets.MARK_ID : -1475365623_57f04ab8
      id:j_idt6
      type:javax.faces.component.html.HtmlInputText
      expression/value = #{testBean.param} : null
      attr = com.sun.faces.facelets.MARK_ID : -1475365623_57f04aae
      id:j_idt7
      type:javax.faces.component.html.HtmlCommandButton
      value = null
      attr = com.sun.faces.facelets.MARK_ID : -1475365623_57f04a9f
  id:j_idt8
  type:com.sun.faces.facelets.compiler.UIInstructions
  value = null
  attr = com.sun.faces.facelets.MARK_ID : -1475365623_57f04af7_1
```
2. You can interact some time with that node. When node1 is stopped (or disabled) the access goes to the node2. Node2 also initializes the IdMapper so its cache is empty at first and starting from 0. But the view is in the session and replicated OK. So it receives the previous view (except the transient elements). So, when it creates the UIIinstructions again, it gives new IDs starting from 0. And the following issue happens:

```
2020-02-26 14:20:06,569 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-1) +id: j_id1
 type: javax.faces.component.UIViewRoot@41415225
  +id: j_idt1
   type: <html xmlns="http://www.w3.org/1999/xhtml">


  +id: j_idt2  <===============
   type: javax.faces.component.UIOutput@2a85a487
    +id: j_idt2  <===============
     type:
    <title>test-jsf</title>

  +id: j_idt4
   type: javax.faces.component.html.HtmlBody@4a3022df
    +id: j_idt5
     type: javax.faces.component.html.HtmlForm@276fdc0
      +id: j_idt6
       type: javax.faces.component.html.HtmlInputText@7edb84a5
      +id: j_idt7
       type: javax.faces.component.html.HtmlCommandButton@79fdb665
  +id: j_idt3
   type:
</html>

2020-02-26 14:20:06,578 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-1) Error Rendering View[/view.xhtml]: java.lang.IllegalStateException: Component ID j_idt2 has already been found in the view.
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1145)
```

So the problem is that the IdMapping and its cache is not replicated and therefore if new elements are created they can collide with existent elements in the current view (because they were created in another node of the cluster before). In the sample the PARTIAL_STATE_SAVING is set to false to magnify the issue, but the issue is possible in general (for example I could reproduce the same with PARTIAL_STATE_SAVING=true and a jstl c:forEach that creates new elements in the view).

We have been playing with two ideas:

1. If the option `com.sun.faces.enableDistributable` is defined the IdMapper checks the ID is not repeated when it creates a new one. It means that each call to the `newInstance` needs to check current view to not duplicate ids. But with this idea the IdMapper and its cache is different in each node, and I'm not sure if this is dangerous (but now it works this way, with this idea only the duplication is avoided).
2. If the option `com.sun.faces.enableDistributable` is defined the IdMapper does nothing, just the facelet id (a long one) is returned. This option just removes the IdMapper and the cache and uses plain facelet ids. We can use a different context param to do this (this was just a test).

Both ideas work with simple apps but I need some help here. I'm not sure if we are missing something. What do you think? Is option 1 valid (two nodes can have different caches for the IdMapper) or better going directly for the second option (maybe using a different param)? Any other idea?

@arjantijms Please take a look to this when you have time. We need some hint to start the coding.

Thanks in advance!

**Comment by rmartinc** [comment]
test-jsf.war

**Comment by rmartinc** [comment]
Sample war, rename to test-jsf.war.

[test-jsf.zip](https://github.com/eclipse-ee4j/mojarra/files/4268010/test-jsf.zip)

**Comment by rmartinc** [comment]
We have tested both options and option 1 can fail if there are changes in the number of components in the view (for example components being added and removed by jstl). The main reason is the de-synchronization of the caches. In this first option the factory in the IdMapper checks the ID when it's created, when the factory is called the ID is checked to not exists in the current view. But different caches can assign the same ID to two different elements (because that element is transient and not in the view received by the other node). And that can trigger the issue again. So maintaining the coherence of the two IdMappers/caches is going to be complicated and tedious.

The second option works OK. WDYT? How do you see adding a context parameter (for example "com.sun.faces.useFaceletsID") to make the IdMapper return the same long facelet ID?

**Comment by rmartinc** [comment]
Hi, please any feedback on this would be much appreciated. 

Is the solution commented above OK (using a context param to use facelet ID and doing no mapping)? Can we start preparing a PR for that?

**Comment by rmartinc** [comment]
Created PR for the idea: https://github.com/eclipse-ee4j/mojarra/pull/4695

**Comment by BalusC** [comment]
I've backported the PR from master to 2.3.

Running all tests as we speak, if they all pass, then I'll merge.

**Comment by BalusC** [comment]
All tests have passed :+1:
