### ISSUE TITLE
Problem indicating ajax request after update of form

### ISSUE THREAD

**Issue by tdtappe** [eclipse-ee4j/mojarra#4678]
Because I thought it was a Primefaces problem it is all explained here:

https://forum.primefaces.org/viewtopic.php?f=3&t=61225

But it's more probably a mojarra problem. I provided a sample project there which can be run with mojarra 2.2 and mojarra 2.3 (selected by a maven profile).  It works with 2.2 but not with 2.3.

Can anybody help?

**Comment by melloware** [comment]
@tdtappe Please attach a zip of your project here (without target folder) and provide instructions on how to run it.

**Comment by tdtappe** [comment]
Start it using

mvn jetty:run -Pmojarra22 OR mvn jetty:run -Pmojarra23

Call URL: http://localhost:8080/primefaces-test/

Turn on the browser console.

Press the button twice. With mojarra 2.3 there will be no console output on the second time you press the button.

[primefaces-deferred-ajax.zip](https://github.com/eclipse-ee4j/mojarra/files/4281389/primefaces-deferred-ajax.zip)

**Comment by erickdeoliveiraleal** [comment]
I also have a problem related to ajax in a datatable https://github.com/eclipse-ee4j/mojarra/issues/4734

**Comment by melloware** [comment]
OK created new reproducer:
[primefaces11-deferred-ajax.zip](https://github.com/eclipse-ee4j/mojarra/files/8774369/primefaces11-deferred-ajax.zip)

It works with PF 11.0 and Mojarra 2.2 and 2.3 so I think this ticket can be closed.
