### ISSUE TITLE
c:forEach Incorrect Behavior

### ISSUE THREAD

**Issue by melloware** [eclipse-ee4j/mojarra#4680]
**Versions Tested:** 2.2.19 and 2.3.13

**Description:**
Attached is a project that shows the problem I’m encountering with c:forEach.  I am trying to create a generic dialog that lets users add, remove, and reorder columns in a datatable.  Basically, it’s like <p:columnToggler>, but more advanced.  I am using a choose/when method for displaying the columns, instead of <p:columns>, because our columns are very complicated.  This was a method recommended [by BalusC on StackOverflow](https://stackoverflow.com/questions/37660444/is-it-possible-to-do-dynamic-column-ordering-on-a-pdatatable-without-using-pco).

The problem is that the datatable seems to get disconnected between its internal state and the JSF page.  Here are two scenarios that don’t work:

_Refresh the test page.  Click on the Sort Columns button._
        **Expected:**  The columns are sorted alphabetically (Color, Make, Model, Year).
        **Actual:**   The data is sorted correctly, but the column headers are Year, Color, Make, Model.

_Refresh the test page.  Click on the Hide Model button.  Then click on the Sort Columns button._
        **Expected:**  The visible columns are sorted alphabetically (Color, Make, Year).
        **Actual:**      The data is in the wrong column, and the column headers are Year, Color, Make.

Reproducer is attached here: 
[mojarra-4680.zip](https://github.com/eclipse-ee4j/mojarra/files/8709540/mojarra-4680.zip)

Run `mvn clean jetty:run-exploded -Pmojarra23` and navigate to http://localhost:8080/primefaces-test/test.xhtml

As a note it fails with Mojarra 2.2.19 and 2.3.13 but works with MyFaces 2.2 and 2.3.

`mvn clean jetty:run-exploded -Pmojarra22` **(fails)**

`mvn clean jetty:run-exploded -Pmojarra23` **(fails)**

`mvn clean jetty:run-exploded --Pmyfaces22` **(passes)**

`mvn clean jetty:run-exploded --Pmyfaces23`  **(passes)**

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
