### ISSUE TITLE
JSF: selectOneMenu required+disabled true

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [eclipse-ee4j/mojarra#4716]
Submitin selectOneMenu required=true+disabled=true result in validation error message.

Regression in WildFly 20, clicking button fires a message.
WildFly 19 it's ok.

**Steps to reproduce**
Clone project https://gitlab.com/erickdeoliveiraleal/simpleproject
Access http://localhost/project-0.0.1-SNAPSHOT/text.xhtml
Click the button
[project.zip](https://github.com/eclipse-ee4j/mojarra/files/4748925/project.zip)

WildFly issue: https://issues.redhat.com/browse/WFLY-13571

**Comment by erickdeoliveiraleal** [comment]
@soul2zimate maybe it is related to previous fix? if you can look, please.

**Comment by soul2zimate** [comment]
https://github.com/eclipse-ee4j/mojarra/pull/4717 should fix it.

**Comment by codylerum** [comment]
I believe I have hit this same issue which also causes an NPE when a disabled h:selectOneCheckbox is submitted. I've commented on https://issues.redhat.com/browse/WFLY-13571 with the stacktrace.

I'm trying to build and create a test but I'm running into build issues based on the readme instructions #4721
