### ISSUE TITLE
Update ParseConfigResourceToDOMTask for https://jakarta.ee/xml/ns/jakartaee/web-facesconfig_3_0.xsd (for Jakarta EE 9).

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/mojarra#4725]
Please add https://jakarta.ee/xml/ns/jakartaee/web-facesconfig_3_0.xsd support to Mojarra. 

As @smillidge mentioned on the Platform TCK ml, it looks like [ParseConfigResourceToDOMTask.java#L224](https://github.com/eclipse-ee4j/mojarra/blob/21f91d4aef9deac350786a4a37308f03be239f7f/impl/src/main/java/com/sun/faces/config/manager/tasks/ParseConfigResourceToDOMTask.java#L224) needs to allow the 3.0 schema.  The code change, should be consumed by GlassFish 6.0.

This should help address a Jakarta EE 9 Platform TCK failure with to [jsf/spec/render/secret/faces-config.xml](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jsf/spec/render/secret/faces-config.xml).  

The test [exception is shown here.](https://gist.github.com/scottmarlow/15c1782fc441091144c470bc86dcd792#file-jsf-ise-L55)

CC @arjantijms

**Comment by arjantijms** [comment]
Thanks Scott, I'm on it. I'll take a look at this first thing tomorrow.

**Comment by tandraschko** [comment]
@arjantijms 
We also need to make a facelet-taglib 3.0 with jakarta namespace, right?

**Comment by gerdogdu** [comment]
@scottmarlow @arjantijms I have add PR for this for 3.0 branch. Now, TCK tests are running succesfully. Here is the PR, https://github.com/eclipse-ee4j/mojarra/pull/4726

**Comment by scottmarlow** [comment]
Thanks @gerdogdu!

**Comment by scottmarlow** [comment]
Closed since the pr is merged.

**Comment by alwin-joseph** [comment]
Just for clarification, @gerdogdu @arjantijms Can you please help confirm if all the references of http://xmlns.jcp.org/xml/ns/javaee has been replaced with the latest https://jakarta.ee/xml/ns/jakartaee/. 
I found the old schema referenced in below files and some others: 
./impl/src/main/resources/com/sun/faces/facelets1_0-2_0toSchema.xsl
./impl/src/main/resources/com/sun/faces/metadata/taglib/jstl-fn.taglib.xml
./impl/src/main/resources/com/sun/faces/metadata/taglib/html_basic.taglib.xml
./impl/src/main/resources/META-INF/mojarra_ext.taglib.xml

I found 8 test failures in jsf tck when the remaining old schema references were replaced using https://github.com/eclipse-ee4j/jakartaee-tck/pull/481 , and wanted to confirm if anything more is pending here. Thanks
