### ISSUE TITLE
3.0.0-RC2 not available from Central?

### ISSUE THREAD

**Issue by manovotn** [eclipse-ee4j/mojarra#4729]
Recently I worked on enabling some Weld testing and needed to update `org.glassfish:jakarta.faces`.
Looking at [Central](https://repo1.maven.org/maven2/org/glassfish/jakarta.faces/), I only found CR1 version so I thought I would bring this up in case it wasn't intentionally left out.

**Comment by manovotn** [comment]
@arjantijms seeing you issued the release, was this intentional?
The absence of this artifact makes it imposible for me to execute all Weld servlet tests since RC2 apparently has some bugfixes that I need (tried installing artifact locally, so I know RC2 helps).

**Comment by arjantijms** [comment]
@manovotn Sorry I missed the original issues. Indeed, doing only a staging was intentionally. These artefacts were first and foremost a quick release to build GlassFish 6. Many other (non-API) artefacts for the GlassFish release train have also only been released in staging.

I'll check if there's any implementation jar that Mojarra depends on also only in staging, and if not will try to push out RC2 to Central.

**Comment by manovotn** [comment]
Are there any news about this @arjantijms?

**Comment by fjuma** [comment]
@arjantijms Any updates on this one?

**Comment by arjantijms** [comment]
@fjuma not yet, but I'll give it a shot. Note that a RC in Maven central is not really necessary in order to run tests. Adding the staging repos to a pom or e.g. settings.xml should be enough:

```
           <repositories>
                <repository>
                    <id>sonatype-nexus-staging</id>
                    <name>Sonatype Nexus Staging</name>
                    <url>https://jakarta.oss.sonatype.org/content/repositories/staging/ </url>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>sonatype-nexus-staging</id>
                    <name>Sonatype Nexus Staging</name>
                    <url>https://jakarta.oss.sonatype.org/content/repositories/staging/ </url>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
```

**Comment by fjuma** [comment]
Thanks, @arjantijms!

**Comment by arjantijms** [comment]
@fjuma Mojarra RC3 (which is the latest now) is released here: https://repo1.maven.org/maven2/org/glassfish/jakarta.faces/3.0.0-RC3/

I still think it's not technically necessary, but if it helps you, then why not ;)

**Comment by fjuma** [comment]
Thanks very much, @arjantijms.
