### ISSUE TITLE
GlassFish needs an RC3

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/mojarra#4731]
GlassFish needs an RC3 including https://github.com/eclipse-ee4j/mojarra/pull/4726 as this currently prevents deployment of JSF applications using the new descriptors and is blocking progress on TCK testing. 

See https://github.com/eclipse-ee4j/glassfish/issues/23106

**Comment by arjantijms** [comment]
It has now been staged: https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/jakarta.faces/3.0.0-RC3/
