### ISSUE TITLE
The default value for com.sun.faces.clientStateTimeout is invalid

### ISSUE THREAD

**Issue by vsvetoslavov** [eclipse-ee4j/mojarra#4743]
The constructor in ``WebConfiguration`` for the ``ClientStateTimeout`` value defines the default value as ``""``.
The ``init()`` method of ``ClientSideStateHelper``, however, contains the following:

   ```java
     stateTimeoutEnabled = webConfig.isSet(ClientStateTimeout);
        if (stateTimeoutEnabled) {
            String timeout = webConfig.getOptionValue(ClientStateTimeout);
            try {
                stateTimeout = Long.parseLong(timeout);
            } catch (NumberFormatException nfe) {
                stateTimeout = Long.parseLong(ClientStateTimeout.getDefaultValue());
            }
        }
```

So if the value in the _web.xml_ is invalid, an attempt is made to read ``""`` as ``Long``, which in turn results in ``NumberFormatException``.
The above behaviour is present in _2.3.9.SP03_ (WildFly 18.0.0). The code for _2.3.9.SP11_ seems like that as well but I haven't tested with that version.
Browsing further I realized that there is no way to define a value for clientStateTimeout such that there will be no timeout (similar to the behaviour if there is no value defined in web.xml). This also seems wrong - it would be good if one is able to explicitly disable the timeout.
The same issue is described also here: 
https://github.com/jboss/mojarra/issues/78

**Comment by BalusC** [comment]
Reproduced.

Catch block should actually set `stateTimeoutEnabled = false` rather than attempting to parse the default.

**Comment by BalusC** [comment]
Fixed. It will now:
- disable the client state timeout when resolved context param has a negative value
- disable the client state timeout and log a warning when resolved context param is not parseable as long
