### ISSUE TITLE
The first websocket that gets triggered from any deployed war file on server prevents all websockets in all other deployed war files from working

### ISSUE THREAD

**Issue by scsynergy** [eclipse-ee4j/mojarra#4799]
**Two** war files are deployed on the same Wildfly instance and both use websockets. The **first** page with f:websocket that gets loaded by the browser works perfectly well. Any websocket on any other page of the **same** war file also works perfectly well. Yet, any websocket of the **second** war file will not work until the server is restartet. Then the first page with a websocket that gets loaded determines which war file's websockets will work.

Example:
1. WS**1**/index.xhtml    --> websocket works
2. WS**2**/index.xhtml    --> websocket does not work (because it seems to be closed on the server side?)
3. restart Wildfly
4. WS**2**/index.xhtml    --> websocket works
5. WS**1**/index.xhtml    --> websocket does not work (because it seems to be closed on the server side?)
6. if we had a WS**3**/index.xhtml its websockets would also not work

issue found on: Mojarra 2.3.9.SP11 on WildFly Full 20.0.1.Final (WildFly Core 12.0.3.Final)

Example war files attached for you to easily confirm this issue:
[ws1.tar.gz](https://github.com/eclipse-ee4j/mojarra/files/5530303/ws1.tar.gz)
[ws2.tar.gz](https://github.com/eclipse-ee4j/mojarra/files/5530305/ws2.tar.gz)

**Comment by scsynergy** [comment]
Created the same bug report here because I cannot tell whether the bug is in Mojarra or the Wildfly integration of Mojarra: 
https://issues.redhat.com/browse/WFCORE-5234

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
