### ISSUE TITLE
Resources: set cache-control-header instead of expires-header

### ISSUE THREAD

**Issue by christophs78** [eclipse-ee4j/mojarra#4800]
https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/com/sun/faces/application/resource/ResourceImpl.java#L184 currently set´s expires-header.

IMO it´s today state-of-the-art to set `cache-control: max-age=XXX` instead of `expires` for resources which should be cached. And set `cache-control: no-cache` for resources which should not be cached.

Details: https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Cache-Control

This would also simplify code a bit.

**Comment by BalusC** [comment]
Already in 2.3.15.
