### ISSUE TITLE
RESTORE_PHASE is slow on Mojarra 2.3

### ISSUE THREAD

**Issue by wafa-ogh** [eclipse-ee4j/mojarra#4811]
Hello All,

After upgrading from Mojarra 2.2.13 to Mojarra 2.3.9, RESTORE_PHASE becomes slow. In my case, the response time of requests from views with at least 5000 components, has increased 12 times compared to 2.2, an ajax action that used to take ~600 to ~800 milliseconds, takes now several seconds to complete :(    
From looking at the differences on the two versions, it was the ComponentSupport.findChildByTagId() method that caused the issue on 2.3.
![image](https://user-images.githubusercontent.com/35977998/99955851-50892e80-2d85-11eb-9c7e-209d5cdc9a59.png)
On 2.2, ComponentSupport.findChildByTagId() does not perform a tree search If the phase Id is equal to RESTORE_PHASE or if the request is not a postback.
The method has undergone 2 changes :

1. The first change removed the check on the phase Id
        The commit description point this bug https://java.net/jira/browse/JAVASERVERFACES-4124 (Ajax file upload fails when 
        com.sun.faces.namespaceParameters is set to true)

2. The second change removed the check on the request type, the related commit description point to these bugs : 
	https://java.net/jira/browse/JAVASERVERFACES-4142 "ENABLE CLIENTSTATESAVINGPASSWORD BY DEFAULT IN JSF 1.2"
	track bugdb bug#23126505: JSF ERRORS AFTER APPLYING WLS 12.1.3 PSU5/PSU6 also fix: Bug 22879626 - REGRESSION IN 
        JSF PAGE RENDERING IN GLASSFISH 3.1.2.12

Although the fix could be to stay on the 2.2.13 version right now, but as Mojarra user and interested on knowing about the updates, I wanted to better understand these changes in the 2.3.9 version : Are they really related to changes for "com.sun.faces.ClientStateSavingPassword" to be enabled by default (4142) and the "Ajax issue when com.sun.faces.namespaceParameters is set to true" (4124) or did I misunderstood the commits comments ?
Also, will the ComponentSupport.findChildByTagId() stay as is on next releases especially because it has impacted Mojarra performance when handling big component trees  ? Could this be considered a bug on 2.3 ?

Environment : JSF 2.3.9 SP06 / Wildfly 19.0.0

**Comment by BalusC** [comment]
It has caused a public API leak. A few new public methods have been added to `UIComponent` while they should not have become part of the public API. I could make the `addToDescendantMarkIdCache()` and `removeFromDescendantMarkIdCache()` package-private, but the `getDescendantMarkIdCache()` method really couldn't be made package-private.

Hence I opted to store the `Map<String, UIComponent> descendantMarkIdCache` local variable into the `getTransientStateHelper()` instead.

Could you please re-run your performance tests against this branch https://github.com/eclipse-ee4j/mojarra/pull/4905?

I've at least run the entire integration test suite at my machine and all tests passed.

**Comment by BalusC** [comment]
It's now merged nonetheless.

**Comment by wafa-ogh** [comment]
Hello, Thank you  @BalusC and sorry for the late reply. I ran the tests on #4934 and the performance issue of the RESTORE_VIEW phase is fixed :)
These are the results, The application server used is Wildfly 19.0.0, and the page used for test contains more than 20 000 JSF components (21662)
**On JSF 2.2** (jsf-impl-2.2.13.SP4) before the upgrade, response time of the ajax requests was :
![image](https://user-images.githubusercontent.com/35977998/120940562-d06d5980-c715-11eb-8845-aaad4e3b5c15.png)

The average response time by phase is :
RESTORE_VIEW 1 : 333 ms 
APPLY_REQUEST_VALUES 2 : 7 ms 
PROCESS_VALIDATIONS 3 : 5 ms 
UPDATE_MODEL_VALUES 4 : 7 ms 
INVOKE_APPLICATION 5 : 0 ms 
RENDER_RESPONSE 6 : 303 ms 

After upgrade to **JSF 2.3** (jsf-impl-2.3.9.SP06)
Response time of the ajax requests is :
![image](https://user-images.githubusercontent.com/35977998/120940769-d1eb5180-c716-11eb-8bb9-3b4aad59fce3.png)

The average response time by phase is :
RESTORE_VIEW 1 : 8768 ms 
APPLY_REQUEST_VALUES 2 : 1 ms 
PROCESS_VALIDATIONS 3 : 0 ms 
UPDATE_MODEL_VALUES 4 : 0 ms 
INVOKE_APPLICATION 5 : 1 ms 
RENDER_RESPONSE 6 : 307 ms 

After applying the **#4934 fix** (I applied the fix for both Wildfly modules jsf-impl-2.3.9.SP06.jar and jboss-jsf-api_2.3_spec-3.0.0.SP01.jar)
Response time of the ajax requests is :
![image](https://user-images.githubusercontent.com/35977998/120940825-0d861b80-c717-11eb-9418-7c6cdfeaea34.png)

The average response time by phase is :
RESTORE_VIEW 1 : 367 ms 
APPLY_REQUEST_VALUES 2 : 0 ms 
PROCESS_VALIDATIONS 3 : 0 ms 
UPDATE_MODEL_VALUES 4 : 1 ms 
INVOKE_APPLICATION 5 : 1 ms 
RENDER_RESPONSE 6 : 348 ms
