### ISSUE TITLE
New WARNING error message on undeploy when there are duplicate registrations of ConfigureListener

### ISSUE THREAD

**Issue by rmartinc** [eclipse-ee4j/mojarra#4812]
Mainly the same issue fixed in #3801 but with a new second message. The new severe message was introduced by the change in #4587 with this commit https://github.com/jboss/mojarra/commit/b45a4e4a7dda21b0a0c8b30d43e249e44a5b1f2a.

This new [line](https://github.com/jboss/mojarra/commit/b45a4e4a7dda21b0a0c8b30d43e249e44a5b1f2a#diff-3f75b18a1a7fd1e67a74dc03b9b8ef4a6987c6429e3211134ed55f60be6737a9R363) displays again the same error not checking if the context was destroyed before.

I'm going to send a PR for 2.3 branch with the same fix that was already done for the previous #3801 but for the new line.

**Comment by BalusC** [comment]
Already in 2.3.15.
