### ISSUE TITLE
[2.3.14] <h:dataTable>: Dependency to JSTL

### ISSUE THREAD

**Issue by ThexXTURBOXx** [eclipse-ee4j/mojarra#4818]
# Scenario
Add a <h:dataTable> listing a (custom) Iterable to a Facelet.

# Expected behavior
The dataTable should render the custom Iterable in a dataTable.

# Current behavior
Crash with the Exception below

# Exception
java.lang.NoClassDefFoundError: javax/servlet/jsp/jstl/sql/Result

# Reason/Solution
In this line: https://github.com/eclipse-ee4j/mojarra/blob/2.3.14/impl/src/main/java/javax/faces/component/UIData.java#L1860 there is a dependency to JSTL. If the iterated Object is e.g. an Iterable, but no List/Collection/..., then there is a crash without JSTL, because the other branches can't be loaded after the interface `javax/servlet/jsp/jstl/sql/Result` from jstl couldn't be found.

I would suppose a removal of this branch due to JSTL being an artifact of the past or doing a try-catch. Another option would be a assignable-test by reflection, but this would slow down performance too much for my taste.

# Version
Mojarra 2.3.14

**Comment by arjantijms** [comment]
It has already been removed in master ;)

See https://github.com/eclipse-ee4j/mojarra/commit/3beb869ce2789058ad71da68a1c49a142f52f747#diff-35ff9862219e1852cc4f7bff0b3c9d12f2842b7993aa365c38cdef22bb58e794

**Comment by ThexXTURBOXx** [comment]
Oh, I see, sorry and thank you!

Will there be another 2.x release in the near future with this "fix" (or rather change) applied? We are using JSF currently in a university project and are required to use 2.x and hand in until the end of January 2021 :)

**Comment by BalusC** [comment]
Closing off.

FYI: JSTL is provided out the box by normal Java EE servers. Most probably you was using a barebones servletcontainer such as Tomcat. In that case you'd indeed need to manually install JSTL along with JSF. Note that JSF has also (optional) dependency requirements on CDI and JSONP and Bean Validation and that these are also not per definition provided by a barebones servletcontainer.
