### ISSUE TITLE
Faces 3.0 Does Not Support JavaEE NameSpace in Flow.xml Files

### ISSUE THREAD

**Issue by volosied** [eclipse-ee4j/mojarra#4820]
**UPDATE:  Sorry for the numerous comments. It's been a discovery process.**

https://github.com/eclipse-ee4j/mojarra/blob/1c904bfeb193530624f95628a66da029f270bb1d/impl/src/main/java/com/sun/faces/config/processor/FacesFlowDefinitionConfigProcessor.java#L281-L282

`xpath.setNamespaceContext(new FacesConfigNamespaceContext());`
should be changed to handle both https://jakarta.ee/xml/ns/jakartaee and http://xmlns.jcp.org/xml/ns/javaee

FacesConfigNamespaceContext only handles the Jakarta Namespace.

The code later runs into parsing errors since the namespaces don't' match (Using Javaee on the newer Jakartaee 3.0 version) 

____________

I  noticed that the flows misbehave when exiting a flow (through the return button). 

I tested this failing scenario with the 3.0.0 jar bundled in the  [javaee6web/basicFlow app](https://github.com/eclipse-ee4j/mojarra/tree/master/test/javaee6web/basicFlow) on Open Liberty with the facesContainer-3.0 feature. 

Steps to reproduce: 

1. Go to test-javaee6web-basicFlow/faces/index.xhtml 
2. Click "start flow on valid entry node"
3. Click Next
4. Enter value
5. Click Next
6. Click Return 

The return just reloads the page, and doesn't display "Page navigated to upon return from bounded-task-flow" as expected (when using the 2.4.0 release) 

In another application, I noticed the following error:

    Unable to find matching navigation case with from-view-id '/simple/simple-2.xhtml' for action 'goReturn' with outcome 'goReturn' 

Something may be off with the navigation case handling?

**Comment by volosied** [comment]
For the other application I tested, I see that the behavior changed between the RC3 and RC4 releases.

Looks it it narrows it down to these commits: https://github.com/eclipse-ee4j/mojarra/compare/3.0.0-RC3-RELEASE...3.0.0-RC4-RELEASE 

I've add this second application here: https://github.com/volosied/sample-apps/tree/main/flows-failure

The pom uses the RC3 jar but the additional war contains the RC4 jar (I don't see the maven coordinates for RC4) 

Clicking next (exit flow) on /flow-failure-rc4/simple/simple-2.xhtml just refreshes the page when it shouldn't.

**Comment by volosied** [comment]
Actually, I tested test-javaee6web-basicFlow on Tomcat and it's not working with RC3 either. Not sure what's occurring here.

Feel free to test yourself: https://github.com/volosied/sample-apps/tree/main/test-javaee6web-basicFlow

**Comment by volosied** [comment]
Closing as the *flow.xml needs  to use the new jakarta schema.  Otherwise, the returns are not identified when processing the xml:

https://github.com/eclipse-ee4j/mojarra/blob/1c904bfeb193530624f95628a66da029f270bb1d/impl/src/main/java/com/sun/faces/config/processor/FacesFlowDefinitionConfigProcessor.java#L453

Problematic schema: 
https://github.com/volosied/sample-apps/blob/main/flows-failure/src/main/webapp/simple/simple-flow.xml#L11-L14

**Comment by volosied** [comment]
Reopening as I think the old 2.2/2.3 namespaces  should still be accepted?

**Comment by hussainnm** [comment]
I found a similar issue with empty flow-definition file and raised it on the mailing-list
https://www.eclipse.org/lists/mojarra-dev/msg00144.html

Quoting text from email:

> The simple-flow example in jakartaee-tutorial-examples[1] repo does not produce the expected output when run on GlassFish 6.0.0 with Mojarra 3.0.0
> 
> https://eclipse-ee4j.github.io/jakartaee-tutorial/jsf-configure004.html#sthref82
> 
> In the second flow page, when the Return button is clicked, it gives the following error:
> * Unable to find matching navigation case with from-view-id '/simple-flow/simple-flow-page2.xhtml' for action 'simple-flow-return' with outcome 'simple-flow-return'
> 
> Other things, I have tried are:
> 
> 1. Change action from “simple-flow-return” to “/simple-flow-return”
> This redirects to the Return Page but the flowScope.value is not blank (expectation is flowScope.value should become empty)
> 
> From the specification https://jakarta.ee/specifications/faces/3.0/jakarta-faces-3.0.html#a6236
> 
> In the case of a zero length flow definition file, the following also applies:
> 
> * There is one return node in the flow, whose id is the id of the flow with the string “-return” (without the quotes) appended to it. For example, if flowId is shopping, the return node id is shopping-return.
> 
> * The from-outcome of the return node is a string created with the following formula:
> "/" + flowId + "-return".
> 
> The same code works when deployed with MyFaces-4.0.0.
> 
> [1] https://github.com/hussainnm/jakartaee-tutorial-examples/tree/jakartaee9/web/jsf/simple-flow

**Comment by hussainnm** [comment]
In my scenario, the empty flow.xml is getting created with **JAVAEE_XMLNS** and most likely running into the namespace conflict issue you have reported.

https://github.com/eclipse-ee4j/mojarra/blob/955c69197773e348186a7a24bb5abb55586e548d/impl/src/main/java/com/sun/faces/config/processor/FacesFlowDefinitionConfigProcessor.java#L120-L156

**Comment by melloware** [comment]
@arjantijms this looks like it was merged and can be closed.
