### ISSUE TITLE
NullPointerException in DemuxCompositeELResolver

### ISSUE THREAD

**Issue by jbescos** [eclipse-ee4j/mojarra#4832]
This is the cause in the version 1.2_15:
```
Caused By: java.lang.NullPointerException
    at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:173)
    at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:200)
    at com.sun.faces.el.ChainTypeCompositeELResolver.getValue(ChainTypeCompositeELResolver.java:91)
    at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:147)
    at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:147)
    at com.sun.el.parser.AstIdentifier.getValue(AstIdentifier.java:116)
    at com.sun.el.parser.AstValue.getBase(AstValue.java:150)
    at com.sun.el.parser.AstValue.getValue(AstValue.java:199)
    at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
```
Null pointer is happening in this line, the ELResolver is null in the index i:
`Object localObject = paramArrayOfELResolver[i].getValue(paramELContext, paramObject1, paramObject2);`

After some investigation in the code, that class DemuxCompositeELResolver does not allow to insert null ELResolver. The index is increased after a new ELResolver is inserted. This means that every time the 'i' should be consistent with a not null ELResolver.

My conclusion is that it is impossible that exception could happen, except for the case DemuxCompositeELResolver is accessed concurrently. That class is not designed to be thread safe.

Do you know what could be the reason?, is it possible that instance is accesed by multiple threads in parallel?.

**Comment by jbescos** [comment]
It looks possible to invoke com.sun.faces.application.ApplicationImpl#performOneTimeELInitialization() from multiple threads.

There are 3 ways to invoke this:
```
com.sun.faces.application.ApplicationImpl#getELResolver()
com.sun.faces.application.ApplicationImpl#getPropertyResolver()
com.sun.faces.application.ApplicationImpl#getVariableResolver()
```
Only getELResolver() synchronizes:
```
    public ELResolver getELResolver() {

        if (compositeELResolver == null) {
            synchronized(this) {
                if (compositeELResolver == null) {
                    performOneTimeELInitialization();
                }
            }
        }

        return compositeELResolver;

    }
```
The other two checks it is not null, but there is no synchronization:
```
    public PropertyResolver getPropertyResolver() {
        if (compositeELResolver == null) {
            performOneTimeELInitialization();
        }
        return propertyResolver;
    }
    public VariableResolver getVariableResolver() {       
        if (compositeELResolver == null) {
            performOneTimeELInitialization();
        }

        return variableResolver;
    }
```

Then it makes it possible to invoke performOneTimeELInitialization() more than 1 time.

**Comment by manorrock** [comment]
@jbescos This version of Mojarra only maintains 2.3 and later. If you need support on any version earlier you are recommend to contact your vendor.
