### ISSUE TITLE
AjaxExceptionHandlerImpl logs stacktrace as message

### ISSUE THREAD

**Issue by RagingCactus** [eclipse-ee4j/mojarra#4839]
I am currently integrating [Sentry application monitoring](https://sentry.io) into a JSF application that is running on Mojarra 2.3. Events for Sentry are captured by integrating a `java.util.logging.Handler` into the logging stack. This handler then takes every logged error event and sends the corresponding message and stacktrace to Sentry where it is processed, for example by grouping stacktraces together.

While monitoring Sentry events for my application I noticed that `com.sun.faces.context.AjaxExceptionHandlerImpl` formats exceptions into the message field of the log entry instead of using the `Throwable` parameter. This messes up grouping in Sentry and probably most other log monitoring software that uses log handlers to capture events.

This behavior was observed in Mojarra 2.3, but seems to be present in `master` as well. The following code formats the stacktrace into the log message:
https://github.com/eclipse-ee4j/mojarra/blob/559f09126f63d955e07548724788bc649e1354f3/impl/src/main/java/com/sun/faces/context/AjaxExceptionHandlerImpl.java#L180-L184

Curiously, just a few lines further down in a `catch` block, another exception is logged "properly" by using the `Throwable` parameter:
https://github.com/eclipse-ee4j/mojarra/blob/559f09126f63d955e07548724788bc649e1354f3/impl/src/main/java/com/sun/faces/context/AjaxExceptionHandlerImpl.java#L188-L191

Is there a reason for formatting the stacktrace into the log message instead of using the `Throwable` parameter? And if this is not the case, can you consider changing it?

**Comment by manorrock** [comment]
Feel free to create a PR with the change and some tests around it
