### ISSUE TITLE
Empty lists are discarded during state-saving

### ISSUE THREAD

**Issue by christophs78** [eclipse-ee4j/mojarra#4881]
.. so this state is not saved and EL is re-evaluated during the next request-cycle.

This causes following issues:
https://github.com/primefaces/primefaces/issues/7026
https://github.com/primefaces/primefaces/issues/7181
https://github.com/primefaces/primefaces/issues/6427

MyFaces preserves emtpy lists.

**Comment by melloware** [comment]
Nice work @christophs78

**Comment by melloware** [comment]
Shouldn't this fix be ported to 3.0 and 4.0 as well?

**Comment by christophs78** [comment]
Yes, we should port it.

**Comment by BalusC** [comment]
Please don't PR/merge this one yet.

The 3.0 and 4.0 are currently not fully up to date with recent 2.3 changes.

Among others https://github.com/eclipse-ee4j/mojarra/commit/57932b88d44a408ed16e7cf6025d5ebe8e55e17e is still not in 3.0/4.0 and overlapping your changes.

I'll sort out it.

**Comment by BalusC** [comment]
Everything is in 2.3 / 3.0 / 4.0 now and I've made sure that 2.3 is synced into 3.0 and then into 4.0.

Thank you for your contribution!
