### ISSUE TITLE
The new xmlns jakarta.faces in Facelets is working in the  Mojarra 3.0?

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/mojarra#4893]
These days I am trying to create another template project for the Servlet 5.0 container, In the first stage, I want to add Weld, Mojarra, Jersey to it and make it run on Tomcat 10.0.x.

Please check here:

https://github.com/hantsy/jakartaee9-servlet-starter-boilerplate/

I followed the readme doc of this repository to add Mojarra, found the *hello.xhtml* did not work. Finally, I checked the `test2` folder in this repo, and also saw the namespaces `jakarta.faces.XXXX` in the examples.

But unfortunately it did not work.  I spent hours on it but did not found the reason, not sure if I need to add extra config for it.

Finally, I changed to the jsf 2.3 namespace , worked. Check this commit:
https://github.com/hantsy/jakartaee9-servlet-starter-boilerplate/commit/206b4d0a2a250977f25b4a218f5fe96849d1344a

**Comment by christophs78** [comment]
3.0 has the old xmlns, 4.0 the new one
See https://github.com/eclipse-ee4j/mojarra/pull/4867

**Comment by hantsy** [comment]
@christophs78 Thanks.

But please add a note to `hello.xhtml` code fragment, and explain the supported version. Originally when I read the info, I thought it is already supported in version 3.0.
