### ISSUE TITLE
The xmlns in facelets not update to jakarta.ee?

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/mojarra#4894]
I have not written Faces applications in the past months,  today when I created the sample facelets xhtml. 

And check the vdl docs: https://jakarta.ee/specifications/faces/3.0/vdldoc/

The xmlns in the facelets still used the old jcp.

In Jakarta EE 9, all namespaces are changed to jakarta.ee, these are not changed?

**Comment by christophs78** [comment]
Maybe the same like your other issue?
3.0 has the old xmlns, 4.0 the new one
See #4867
