### ISSUE TITLE
Release monthly milestone for Mojarra 4.0

### ISSUE THREAD

**Issue by manorrock** [eclipse-ee4j/mojarra#4901]
To allow folks to start testing Mojarra 4.0 I propose we do a milestone release monthly on a specific day of the month. I propose we do it on the 11th of every month to honor the release of the JSF 1.0 specification on 2004-03-11.

**Comment by manorrock** [comment]
Please like this issue if you think this should be done!

**Comment by arjantijms** [comment]
Okay, so then let's do the first milestone, `4.0.0-M1` on 11 April ;)

**Comment by manorrock** [comment]
Looks like you create the 4.0.0-M1 milestone. Closing this.
