### ISSUE TITLE
Continous increase in number of DefaultFaceletFactory.idMappers entries

### ISSUE THREAD

**Issue by fdelsert** [eclipse-ee4j/mojarra#4912]
I have a JSF component that dynamically adds composite components to its children.
To do so, I use the method described here: https://stackoverflow.com/a/15884546/1001248
Everything works fine but after several days of use with many users, I end up with a full heap.

By opening a heap-dump with _mat_, it turns out that the instance of _DefaultFaceletFactory.Cache<String,IdMapper>_ (_idMappers_) takes more than 70% of the heap :

![Capture d’écran 2021-04-12 à 17 35 06](https://user-images.githubusercontent.com/2428794/114871034-23ebb700-9df9-11eb-96fc-60544776a232.jpg)

From what I understood while debugging, components are turned into temporary jsp and the jsp ids are shortened and cached in _idMappers_. The problem is that in my case, the composite components are recreated each time so this cache is never reused and it slowly fills up the heap. 

I saw that it was possible to customize the cache policy with a _FaceletCacheFactory_ but it does not allow to manipulate _DefaultFaceletFactory#idMappers_ which is instantiated directly in the constructor of _DefaultFaceletFactory_ (_init_ method).  I tried to declare my own _FaceletFactory_ but it doesn't seem possible.  I would have liked to use a LRU cache as workaround.

Minimal reproductible example :  https://github.com/fdelsert/mojarra-4912

Do you agree with my analysis?

**jakarta.faces 2.3.14**

**Comment by BalusC** [comment]
Reproduced. This indeed causes a memory (and temp file) leak.

**Comment by BalusC** [comment]
Can you test your case against this branch https://github.com/eclipse-ee4j/mojarra/tree/fix-mojarra-issue-4912_memory-leak-in-ViewDeclarationLanguage-createComponent and let me know if it solves it for you?

**Comment by fdelsert** [comment]
It works like a charm ! Thank you.

**Comment by BalusC** [comment]
OK, upmerged into 3.0/4.0 as well.
