### ISSUE TITLE
Add back Performance-optimized version of ComponentSupport.findChildByTagId()

### ISSUE THREAD

**Issue by BalusC** [eclipse-ee4j/mojarra#4924]
#4808 has been reverted for 2.3.15 as per #4922

This needs to be added back but first we need to identify the failing TCK test and replicate the test in Mojarra project.

@arjantijms can you do this? Then I can take a second look at the impl.

**Comment by arjantijms** [comment]
Yes, I'll look at adding the test in 2.3 first, and then move it to 3.0 and 4.0 as well.

**Comment by BalusC** [comment]
Merged and upmerged in 3.0 and 4.0 as well.

https://github.com/eclipse-ee4j/mojarra/commit/77e0e04a3027c73bc62383a2ac3cde3b86fe3f32
https://github.com/eclipse-ee4j/mojarra/commit/7ebc063432f58f8a5fb0d9fea565f46ed44a29b5
