### ISSUE TITLE
Faces 4.0 Release Date

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#4980]
Is there an official release date?

**Comment by arjantijms** [comment]
Not a super official release date but soon-ish for sure, as in the next month. Hopefully we can do a 4.0-M2 within the next few days, which should be very complete.

**Comment by pizzi80** [comment]
good!! thanks for the update

**Comment by arjantijms** [comment]
4.0.0-M2 was released in December to Maven Central. I just updated the project page too:

https://github.com/eclipse-ee4j/mojarra/releases/tag/4.0.0-M2-RELEASE
