### ISSUE TITLE
Change Mojarra implementation artifactId to mojarra

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/mojarra#5000]
Currently the maven coordinates of mojarra are:

```xml
<groupId>org.glassfish</groupId>
<artifactId>jakarta.faces</artifactId>
```

The comes from the RI days where the naming pattern was `[spec]-api` for the API jar, and `[spec]` for the implementation jar. As Mojarra is no longer the RI (there is no RI concept in Jakarta EE), implementations have been asked to move away from this pattern.

I would like to propose to use:

```xml
<groupId>org.glassfish.mojarra</groupId>
<artifactId>mojarra</artifactId>
```

**Comment by lukasj** [comment]
the convention for the `jakarta.faces` artifact is that it includes the API _and_ some (default/fallback?) implementation; with the move to the different artifact id, I expect that the API goes away from that jar as well. Is that the case here?

**Comment by arjantijms** [comment]
Good point, unfortunately the API is still there.

@mnriem what do you think?

**Comment by lukasj** [comment]
> unfortunately the API is still there.

then I see no reason for the move.

I'm doing following with mail:
* jakarta.mail:jakarta.mail-api - API only (module name jakarta.mail)
* org.eclipse.angus:jakarta.mail - API + impl (module name jakarta.mail) where the impl is used if no other impl is found
* org.eclipse.angus:angus-mail - impl only (module name com.sun.mail)

**Comment by arjantijms** [comment]
I see your point.

We could split the implementation, as we currently do for the API, but Faces / Mojarra doesn't have the flexibility to choose an implementation. So the API split off from the full jar and the implementation split off from the full jar would always have to be used together, and exactly together (not with any other API like eg the Jakarta EE api artefact).

Maybe we therefore do need to postpone this.

There's also the org.glassfish vs org.eclipse, which is perhaps somewhat unfortunate too.

**Comment by lukasj** [comment]
it is absolutely fine - for the runtime - to require that API and IMPL have to be used together. But does the same have to be true at the compile time?

wrt org.glassfish vs org.eclipse - I'd probably postpone this till there is a standalone artifact of the implementation to help people (and us) during transition - one will have a fallback to "old" jars in case of issues

**Comment by mnriem** [comment]
There is a lot that needs to be moved to make it a true API JAR. Several things will have to be marked deprecated and done differently (in a CDI way) before this API / implementation split is done.

**Comment by arjantijms** [comment]
There's quite a number of things to take into consideration there.

One option, for e.g. the FacesServlet could be:

```java
@MultipartConfig
public final class FacesServlet implements Servlet {

Servlet implementationFacesServlet = getServlet();

@Override
    public void service(ServletRequest req, ServletResponse resp) throws IOException, ServletException {
        implementationFacesServlet(req, resp);
  }
ik bedoel:

@MultipartConfig
public final class FacesServlet implements Servlet {

Servlet implementationFacesServlet = getServlet();

@Override
    public void service(ServletRequest req, ServletResponse resp) throws IOException, ServletException {
        implementationFacesServlet.service(req, resp);
  }

}
```

Where `getServlet()` could do either a services lookup OR use CDI for that instead.

**Comment by mnriem** [comment]
@arjantijms Did this get resolved?

**Comment by melloware** [comment]
And is `org.glassfish` really the owner of this shouldn't it be `org.eclipse-ee4j` or something?

**Comment by BalusC** [comment]
LGTM. 

Wondering if we should keep com.sun.faces.* as-is or migrate it to org.glassfish.mojarra.*.
