### ISSUE TITLE
Composite component's child rendered with wrong (non-reparented) clientId if its getClientId is called on PostAddToViewEvent

### ISSUE THREAD

**Issue by VsevolodGolovanov** [eclipse-ee4j/mojarra#5023]
Tested with: Mojarra 2.3.5.SP2 (WildFly 15) and 3.0.0.SP04 (WildFly 26.0.0.Beta1 (EE 9.1 Preview)).
Set PARTIAL_STATE_SAVING=false.

[Reproducer](https://github.com/eclipse-ee4j/mojarra/files/7705539/mojarra-remembers-wrong-client-id-jsf3.zip)

Have a composite with a form inside:
```
<cc:implementation>
	<div id="#{cc.clientId}">
		<div>This is the composite component</div>
		<h:form id="cc_form">
			<cc:insertChildren />
		</h:form>
	</div>
</cc:implementation>
```
And a view:
```
<h:body>
	<h:form id="form">
		<p:commandButton id="call" value="Update composite" process="@this" update="composite" />
	</h:form>
	<sys:composite id="composite">
		<!-- cc's immediate child should be autoUpdated and it's clientId somehow referenced (demonstrated here by
			p:ajax's process below) -->
		<p:outputPanel id="panel">
			<p:autoUpdate />
			<!-- this is not specific to commandButton or action - any component's behavior referencing the
				autoUpdated panel in its process or update would result in a wrong clientId rendered -->
			<p:commandButton id="call2" value="Call action from composite"
				process="panel" action="#{bean.notifyAction}" update="growl">
			</p:commandButton>
		</p:outputPanel>
	</sys:composite>

	<p:growl id="growl" />
</h:body>
```
Deploy and open the page.
Click "Call action from composite". See the growl message appear:
![image](https://user-images.githubusercontent.com/8070317/145855141-f811d405-7df2-414f-bd3f-05fd1aa744c0.png)
Now click "Update composite" and then "Call action from composite" again.
Now the growl message doesn't appear.

Compare the resulting HTML before and after the AJAX update:
![image](https://user-images.githubusercontent.com/8070317/145856038-eb98985d-9544-4ed5-8d40-356d23c8341c.png)
The h:form's id piece is gone from the panel's clientId.

The `p:autoUpdate` is key here - this binds the org.primefaces.component.autoupdate.AutoUpdateListener, that calls the panel's getClientId (which is legal according to PostAddToViewEvent's javadoc). Except during the AJAX update this panel was not yet inserted into it's final place, the h:form - instead it has the composite component as it's parent. getClientId then proceeds to remember this wrong clientId in the component's clientId field.

**Comment by VsevolodGolovanov** [comment]
#4696 could be relevant.

**Comment by BalusC** [comment]
> Tested with: Mojarra 2.3.5.SP2 (WildFly 15) and 3.0.0.SP04 (WildFly 26.0.0.Beta1 (EE 9.1 Preview)).

Reproduced with those versions but norepro anymore in 2.3.17 / 3.0.1.

Please upgrade.
