### ISSUE TITLE
All inputs inside composite component executed when using <f:ajax> execute="@this"

### ISSUE THREAD

**Issue by codylerum** [eclipse-ee4j/mojarra#5032]
After upgrading from Wildfly 24 to Wildfly 26 have run into a regression in mojarra. This was an upgrade from mojarra 2.3.14 to 2.3.17

What is happening is that I'm using a simple composite component as a layout.

```
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:cc="http://xmlns.jcp.org/jsf/composite">
    <cc:interface>
        <cc:attribute name="header" required="true"/>
    </cc:interface>
    <cc:implementation>
        <div class="card">
            <div class="card-header">
                #{cc.attrs.header}
            </div>
            <div class="card-body">
                <cc:insertChildren/>
            </div>
        </div>
    </cc:implementation>
</ui:composition>
```

This has worked fine up until now. However now I am seeing that if I have a <f:ajax anywhere within the inserted children then an execute value of `@this` means the entire contents of the composite component. For example

```
<demo:card header="This is a composite component">
      <div class="col-md-4">
          <h:outputLabel for="compositeFirstName"
                         styleClass="form-label">First Name</h:outputLabel>
          <h:inputText id="compositeFirstName" value="#{backingBean.firstName}"
                       styleClass="form-control" required="true"/>
          <div class="invalid-feedback d-block">
              <h:message for="compositeFirstName"/>
          </div>
      </div>
      <div class="col-md-4">
          <h:outputLabel for="compositejob"
                         styleClass="form-label">Job</h:outputLabel>
          <h:selectOneMenu id="compositejob" value="#{backingBean.job}"
                           styleClass="form-control"
                           required="true">
              <f:selectItem itemValue="Butcher"/>
              <f:selectItem itemValue="Baker"/>
              <f:selectItem itemValue="Candlestick Maker"/>
              <f:ajax execute="@this" render="@form"/>
          </h:selectOneMenu>
          <div class="invalid-feedback d-block">
              <h:message for="compositejob"/>
          </div>
      </div>
</demo:card>
```

When a value is selected in the `selectOneMenu` it executes both `compositejob` and `compositeFirstName` which may cause things to fail if `compositeFirstName` is required=true and unset.

I've prepared a repo project at https://github.com/codylerum/execute-this which shows the issue. If you deploy this on Wildfly 24 both pages will work and if you deploy it on Wildfly 26 then the composite version will fail.

I'm assuming this is a result of https://github.com/eclipse-ee4j/mojarra/pull/4915

@BalusC is what I'm seeing the expected behavior, or should it only apply to all the contents of the composite if the `f:ajax` is a direct child of the composite, like 

```
<my:inputLocalTime>
    <f:ajax execute="@this" />
</my:inputLocalTime>
```

**Comment by BalusC** [comment]
Point taken. This should indeed not happen.

**Comment by BalusC** [comment]
While implementing the IT, I noticed that a work around is to simply omit the `execute="@this"`. It will then be correctly implied.

**Comment by codylerum** [comment]
@BalusC Thanks for the quick response.

If anyone else runs in to this you can also just directly reference the client id that would be the correct `@this`

```
<h:selectOneMenu id="compositejob" value="#{backingBean.job}" styleClass="form-control" required="true">  
    <f:selectItem itemValue="Butcher"/>
    <f:selectItem itemValue="Baker"/>
    <f:selectItem itemValue="Candlestick Maker"/>
    <f:ajax execute="compositejob" render="@form"/>
</h:selectOneMenu>
```

**Comment by BalusC** [comment]
All merged now.

**Comment by BalusC** [comment]
FYI impl has been further improved in https://github.com/eclipse-ee4j/mojarra/pull/5294
