### ISSUE TITLE
Allow configuration of com.sun.faces.application.view.activeViewMapsSize via web.xml

### ISSUE THREAD

**Issue by codylerum** [eclipse-ee4j/mojarra#5038]
Currently this value is set in the ViewScopeManager when in looks in the session map to see if a value exists for `com.sun.faces.application.view.activeViewMapsSize`

https://github.com/eclipse-ee4j/mojarra/blob/b07e005e2fab03ebee0f686c40e57d7367b011af/impl/src/main/java/com/sun/faces/application/view/ViewScopeManager.java#L268

However, even if you define this `com.sun.faces.application.view.activeViewMapsSize` value in the web.xml it does not end up getting loaded into the `facesContext.getExternalContext().getSessionMap()` so the value is always 25.

Is it possible to allow this value to be configured via the web.xml? If so I'll start working up a PR to make this happen.

This appears to previoulsy be [#4019](https://github.com/eclipse-ee4j/mojarra/issues/4019) which got closed.

**Comment by BalusC** [comment]
+1

Note that the original session attribute needs to be maintined for some sort of backwards compatibility for the rest of 2.3. It can be removed in 4.0.

**Comment by BalusC** [comment]
I've added new context param named `com.sun.faces.numberOfActiveViewMaps` (to be in line with existing naming for `com.sun.faces.numberOfViewsInSession` and `com.sun.faces.numberOfLogicalViews`)

**Comment by codylerum** [comment]
@BalusC Perfect. Thanks!
