### ISSUE TITLE
jsf.js | Remove FrameTransport + Remove IE6-7-8-9 support

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5040]
Please remove FrameTransport and use FormData for ajax

I think it's also time to remove check for IE9 and all the relative hacks in the code...

https://caniuse.com/mdn-api_formdata

https://github.com/omnifaces/omnifaces/issues/656

there is already a PR that implement FormData 

https://github.com/eclipse-ee4j/mojarra/pull/4626

**Comment by mnriem** [comment]
Because this is asking for removal it needs to be the next cycle around as we will add a deprecation notice for it as part of the upcoming 4.0 release

**Comment by pizzi80** [comment]
deprecate it on v3.0.3 and remove it on 4.0 that is not yet released ...

**Comment by BalusC** [comment]
In big favor of this but I'd rather await for ALL existing JSF 2.x tests to be migrated for Faces 4 before I make serious changes to faces.js.

**Comment by pizzi80** [comment]
Thanks!
In the meantime it could be possible to deprecate all the old functions?

This way it will be possible to implement it on v4.x after tests' migration...

**Comment by arjantijms** [comment]
The spec process would only allow deprecation in a major new version, which is 4.0.

**Comment by pizzi80** [comment]
Ok ...

it's only a matter of performance and size of jsf.js (or faces.js) ... 

The main point is to use FrameTransport only when 

` isIE() && context.form.enctype === "multipart/form-data" `

and then implement the FormData logic inside the sendRequest function ...

so there is nothing to deprecate or remove, it's an implementation that 
can be made even in v2.3 

Then in Faces v5 we can raise the level of the JS to standard ES6 
and remove half the lines of code of faces.js

**Comment by mnriem** [comment]
Closing as this issue has been separated into 2 separate issues, one for deprecation for 4.0 and one for using FormData for 5.0.

**Comment by BalusC** [comment]
Will be fixed via https://github.com/eclipse-ee4j/mojarra/pull/5141
