### ISSUE TITLE
BUG | 3.0.1 and 3.0.2 | Validation failed clear input value

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5043]
Release 3.0.0 works as expected

After the release 3.0.1 there is a bug on form validation: the input value is cleared when it's not valid

**Input value**: 'a'

**Expected h:input value after submit**: 'a'  

**Actual h:input value after submit**: '' 

```
<h:form id="validation">
    <h:messages id="messages" />
    <h:outputLabel for="name" value="Name" />
    <h:inputText id="name" value="#{testJsfValidation.name}" required="true" >
        <f:validateLength minimum="2" maximum="5" />
    </h:inputText>
    <h:commandButton id="submit" action="#{testJsfValidation.submit}" value="Submit" />
</h:form>
```

```
@Named
@RequestScoped
public class TestJsfValidation {

    private static final Logger log = Logger.getLogger(TestJsfValidation.class.getName());

    //@Length(min=2,max=5) // <-- same bug with annotation based validation
    private String name;
   
    public void submit() {
        log.log( Level.INFO,"submitted value: {0}" , name );
    }

    public String getName() {return name;}
    public void setName(String name) {this.name = name;}

}
```

**Comment by BalusC** [comment]
Norepro in 3.0.1 / 3.0.2 with CDI bean and empty web.xml and faces-config.xml. The value is not cleared for me.

- What package did you import `@RequestScoped` from?
- Any `<context-param>` in `web.xml`?
- Any handlers and/or factories in `faces-config.xml`?

**Comment by pizzi80** [comment]
my fault,
I've tried again and now 
it's all working as expected

At first time I upgraded both mojarra and hibernate validator to the latest version and even after 
a lot of maven  reload+clean + tomcat restart
there were (probably) wrong or multiple versions of jsf or hibernate validator

Sorry for the waste of time!

Just because You asked about my jsf config inside web.xml, I think that there are 2 or 3 parameters
that coud lead to ambigous or not expected results, my usual conf is the following

```
<context-param>
    <param-name>jakarta.faces.ALWAYS_PERFORM_VALIDATION_WHEN_REQUIRED_IS_TRUE</param-name>
    <param-value>true</param-value>
</context-param>
<context-param>
    <param-name>jakarta.faces.VALIDATE_EMPTY_FIELDS</param-name>
    <param-value>true</param-value>
</context-param>
<context-param>
    <param-name>jakarta.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL</param-name>
    <param-value>true</param-value>
</context-param>
```

Why a developer should want them to be 'false' ?

Probably I should open a new issue about that

**Comment by BalusC** [comment]
Okay then :) 

As to the params, the `jakarta.faces.VALIDATE_EMPTY_FIELDS` already defaults to `true` and the other two have indeed an unfortunate default of `false` in name of strict backwards compatibility. Although I'm personally not against flipping the defaults .. Feel free to open a new issue specifically on that.

**Comment by pizzi80** [comment]
Just for the record:

I've fixed the problem by removing  jakarta.validation-api dependency from pom.xml
