### ISSUE TITLE
Remove FrameTransport and use FormData

### ISSUE THREAD

**Issue by mnriem** [eclipse-ee4j/mojarra#5045]
See issue https://github.com/eclipse-ee4j/mojarra/issues/5040 for background

**Comment by BalusC** [comment]
First: https://github.com/eclipse-ee4j/mojarra/issues/5044#issuecomment-1046246568

**Comment by mnriem** [comment]
I am closing this one as I have not found anyone to pick it up or found time to work on it myself.

**Comment by BalusC** [comment]
Will be fixed via https://github.com/eclipse-ee4j/mojarra/pull/5141
