### ISSUE TITLE
Describe steps necessary to help out with TCK

### ISSUE THREAD

**Issue by mnriem** [eclipse-ee4j/mojarra#5046]
The maintainers of the Mojarra project need your help as they are also maintainers of the underlying Faces 'spec' project.

 Filing here for visibility, awareness and a plea to help out!

**Comment by arjantijms** [comment]
Fork https://github.com/jakartaee/faces/

Open test class at https://github.com/jakartaee/faces/tree/master/tck/faces40

Add comment

Commit, create pr

**Comment by arjantijms** [comment]
For starters just add some reasonably detailed comment that explains what the test is testing. Bonus if that explanation can reference a phrase from javadoc or the spec document.

**Comment by codylerum** [comment]
@arjantijms Can you reference an example PR fixing one of these? That would give me a better idea of what you are looking for.

**Comment by arjantijms** [comment]
@codylerum yes, a good example is this one from Manfred:

https://github.com/jakartaee/faces/commit/e3e73a90c4de4b096eda8b34ad566c4e18abe631

**Comment by arjantijms** [comment]
Copy pasting the change here to easily see the example:


***Before***

```java
    @Test
    public void testInjectViewMap() throws Exception {
        HtmlPage page = webClient.getPage(webUrl + "faces/injectViewMap.xhtml");
```


***After***

```java
    /**
      * Validate that the ViewMap is available using CDI.current using the
      * ViewMap.Literal.
      * 
      * See jakarta.faces.annotation.ViewMap.Literal.
      */
     @Test
     public void testInjectViewMap() throws Exception {
         HtmlPage page = webClient.getPage(webUrl + "faces/injectViewMap.xhtml");
```

**Comment by BalusC** [comment]
Shouldn't that be @see? That allows automation.

**Comment by arjantijms** [comment]
Steps have been described and people have helped. Lots of thanks to all!
