### ISSUE TITLE
Improve unresolved navigation case log message

### ISSUE THREAD

**Issue by codylerum** [eclipse-ee4j/mojarra#5055]
Currently if a h:link/h:button outcome is invalid the user is logged the following message

`JSF1090: Navigation case not resolved for component j_idt363.`

Where `j_idt363` is the id of the component with the invalid outcome. Unfortunately for large applications with 10s or 100s of pages when a message like this is found in the server logs it is impossible to know what page or what component has the issue.

https://github.com/eclipse-ee4j/mojarra/blob/8a2124c7a5c66642f898ff32924887f55990bc5b/impl/src/main/java/com/sun/faces/renderkit/html_basic/OutcomeTargetRenderer.java#L130

We should update this message to include the ViewId which the component is on as well as the referenced outcome so the invalid code can be easily tracked down and corrected.

**Comment by mnriem** [comment]
@codylerum I labeled it 5.0, but feel free to create a PR and apply it to earlier versions

**Comment by codylerum** [comment]
@mnriem Since this is a log template that has been translated to a lot of languages is it ok just to add the new parameters on to the end of the existing patterns for other languages.

https://github.com/eclipse-ee4j/mojarra/blob/f3764b8553ccb3a0ad4fee37ac5a14c159a46751/impl/src/main/resources/com/sun/faces/LogStrings.properties#L116


For instance for English it could be

`JSF1090: Navigation case not resolved for outcome {0} on component {1} in view-id {2}`

but for german

`Navigations-Fall wurde f\u00fcr Komponente {0} nicht aufgel\u00f6st. {1} {2}`

and then people can update the translations as they are able to? Or do I just remove the translations for the other languages so they fall back to english?

**Comment by codylerum** [comment]
I created #5060

I believe if componentId stays as the first parameter the other languages should just show as they do today until someone updates the translation to include the 2 new params

**Comment by mnriem** [comment]
@codylerum  Can you verify that indeed the other languages still work with this change? Thanks!

**Comment by codylerum** [comment]
@mnriem I realie things are in an odd place right now in developemnt but following the README I cannot `mvn clean install` looks like it is looking for `jakarta.servlet:jakarta.servlet-api:jar:6.0.0` which doesn't exist in public repos.

```
[ERROR] Failed to execute goal on project jakarta.faces: Could not resolve dependencies for project org.glassfish:jakarta.faces:jar:4.0.0-SNAPSHOT: The following artifacts could not be resolved: jakarta.servlet:jakarta.servlet-api:jar:6.0.0, jakarta.websocket:jakarta.websocket-api:jar:2.1.0, jakarta.websocket:jakarta.websocket-client-api:jar:2.1.0, jakarta.el:jakarta.el-api:jar:5.0.0, jakarta.enterprise:jakarta.enterprise.cdi-api:jar:4.0.0, jakarta.json:jakarta.json-api:jar:2.1.0, jakarta.persistence:jakarta.persistence-api:jar:3.1.0, jakarta.xml.ws:jakarta.xml.ws-api:jar:4.0.0, jakarta.annotation:jakarta.annotation-api:jar:2.1.0: jakarta.servlet:jakarta.servlet-api:jar:6.0.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

I did verify that when using the MessageFormat extra params do not cause an issue as would be the case with the other lanaguages.

Missing params just print their placeholder so 
```
String result = MessageFormat.format("This {0} {1} {2}", new Object[]{"foo", null});
```
results in `This foo null {2}`

**Comment by mnriem** [comment]
Write a unit test that takes the message and pushes it through MessageFormat and set the Locale?

**Comment by codylerum** [comment]
@mnriem Simple test added

**Comment by codylerum** [comment]
Would anything different need to happen on this PR to target it to 4.0?

**Comment by arjantijms** [comment]
p.s. note that it's still on the roadmap to remove i18n from the log messages.
