### ISSUE TITLE
Redundant JSP checks in Mojarra 3.0

### ISSUE THREAD

**Issue by larsgrefer** [eclipse-ee4j/mojarra#5061]
The `com.sun.faces.config.ConfigureListener` in Mojarra 3.0.2 still contains checks for JSP 2.0 vs 2.1 and Tomcat 6

https://github.com/eclipse-ee4j/mojarra/blob/2fef22d9b3e5537279f5644f3f8a309cf9e51b66/impl/src/main/java/com/sun/faces/config/ConfigureListener.java#L613-L641

This should be redundant since Mojarra 3.x uses the `jakarta.*` packages and therefore requires at least JSP 3.0 and Tomcat 10.

**Comment by arjantijms** [comment]
This check should be removed in master already (4.0).

**Comment by larsgrefer** [comment]
I think even for Mojarra 2.3.x (which contains the same code) some of these checks are redundant.
Even the very old Tomcat 6 already contained JSP 2.1

I noticed this while experimenting with Mojarra on some embedded Servlet Containers.
The above code gives interesting errors when there is no JSP implementation present at all.

**Comment by arjantijms** [comment]
Yes that's true. It just happens that I came across some of these (and others) in 4.0 ;)

There were tons of other checks as well, regarding Servlet 3, CDI 1.1, etc. Partially having to do with the Mojarra/faces "rule" of always supporting the previous Java EE version as well. I.e. JSF/Mojarra for EE 7 still had to support EE 6, while simultaneously taking advantage of EE 7 features.

**Comment by larsgrefer** [comment]
Even going as low as Java EE 6 would still mean Servlet 3+, JSP 2.2+ and Tomcat 7+

**Comment by larsgrefer** [comment]
For this check do make sense you'd need to run on Tomcat 5 or Glassfish 2:
```java
     try { 
         JspFactory.class.getMethod("getJspApplicationContext", ServletContext.class); 
     } catch (NoSuchMethodException | SecurityException e) { 
         return false; 
     } 
```

**Comment by mnriem** [comment]
@larsgrefer Feel free to create a PR that Arjan can merge to get rid of these checks :)

**Comment by mnriem** [comment]
Note I labeled it 5.0 in case it does not make it for 4.0.

**Comment by larsgrefer** [comment]
@mnriem The `isJspTwoOne()` would then collapse to `isJsp()` and only check if there is a JSP implementation available at all.

What should happen, if there is no JSP implementation?
There seem to be two possible code paths for "no JSP" at the moment:

https://github.com/eclipse-ee4j/mojarra/blob/ae638f9169e9b53a79b6a5679d4e162e0178e83d/impl/src/main/java/com/sun/faces/config/ConfigureListener.java#L660-L662
https://github.com/eclipse-ee4j/mojarra/blob/ae638f9169e9b53a79b6a5679d4e162e0178e83d/impl/src/main/java/com/sun/faces/config/ConfigureListener.java#L699-L701

In the first case a `com.sun.el.ExpressionFactoryImpl` would be instantiated and registered in `com.sun.faces.application.ApplicationAssociate#setExpressionFactory`, but in the second case there would be no `ExpressionFactory` available at all.

**Comment by larsgrefer** [comment]
> Note I labeled it 5.0 in case it does not make it for 4.0.

This issue only affects Mojarra 2.3 and 3.0 since the all the JSP related code was removed for 4.x in 96757f39d47bf05060103b67933eb6afe9fd9278

**Comment by mnriem** [comment]
@larsgrefer Great work!
