### ISSUE TITLE
FacesConverter Lifecycle / Scope

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5068]
I found that a lot of people (me included) are confused 
about the default scope of FacesConverter 
or if it is even possible to define a Scope

https://stackoverflow.com/questions/15956072/jsf-converter-scope-when-using-cdi-seam-3-view-scoped

https://stackoverflow.com/questions/4268179/generic-jsf-entity-converter

https://stackoverflow.com/questions/19180457/jsf-custom-converter-life-cyle

https://stackoverflow.com/questions/59457133/application-scoped-bean-for-converter-for-pselectonemenu

Now that we are finally in the CDI world shouldn't be the case to 
clarify this point ?

Also for 'stateless' converters like for example a LongConverter 
which is basically something like  

`return isBlank(value) ? null : Long.valueOf(value)`

It should be more scalable to define them `@ApplicationScoped` ... isn't it?

**Comment by mnriem** [comment]
@pizzi80 Sounds like a spec change/clarification. Probably should be filed at the API project?

**Comment by pizzi80** [comment]
> @pizzi80 Sounds like a spec change/clarification. Probably should be filed at the API project?

absolutely, but I don't know where to submit this or other changes that time to time comes to my mind ...

Jakarta EE has too many github's projects with API specs and implementations ... :exploding_head:

**Comment by arjantijms** [comment]
The spec tracker is at https://github.com/jakartaee/faces

Maybe the explanation here helps: https://arjan-tijms.omnifaces.org/p/jsf-23.html#1316b

**Comment by pizzi80** [comment]
> The spec tracker is at https://github.com/jakartaee/faces

thanks ...

> Maybe the explanation here helps: https://arjan-tijms.omnifaces.org/p/jsf-23.html#1316b

Yes, I remember I've read your blog many years ago, maybe it was around 2015 ~ 2017 ... more than 5 years ago ;)

Rereading your post, this is the incriminated part:

> It then wraps the bean returned by CDI in a delegating converter instance. This wrapper then delegates to the bean returned by CDI. This wrapper can be state-saved, but since the CDI bean is stored in a transient field it won't save&restore that. Instead, it will only save&restore the converterId or forClass. The restored wrapper will then use the JSF Application instance to ask for a converter with said converterId or forClass (which will go to CDI again, and will do the wrapping again, so we have a double wrapped converter at this point).

A CDI Bean wrapper that delegate calls to a transient injected CDI Converter only to call 
a String to Long conversion seems to much to me, isn't it ?

Before going to the specs side which requires 2 years to remove a LOC 

Why in the meantime simply not set the   `java.lang.*`   FacesConverters  ApplicationScoped ?

Also the DateTime converter and the NumberConverter are very powerful 
but we should provider a "DefaultDateConverter" and "DefaultNumberConverter"
stateless and  ApplicationScoped 

In fact in Seam2 (...2010...) there was a reimplemented and simplified version of DateConverter

obviously my 2 cents

**Comment by mnriem** [comment]
@pizzi80 While I completely understand where you are coming from, you are asking for a behavior change. Those cannot be done on minor revisions as it would break existing applications. So if you and @arjantijms still have bandwidth to get it into 4.0 then go for it, otherwise you are looking at 5.0.

**Comment by arjantijms** [comment]
> A CDI Bean wrapper that delegate calls to a transient injected CDI Converter only to call
> a String to Long conversion seems to much to me, isn't it ?

If it's too much or not maybe needs some qualification. Too much in terms of internal complexity in Mojarra? Had it started from scratch it would probably just have requested the converter as bean from CDI, without any wrapping in the existing converter construct.



> Before going to the specs side which requires 2 years to remove a LOC

Not necessarily, though it does often take a little bit more time.

**Comment by pizzi80** [comment]
> Not necessarily, though it does often take a little bit more time.

LOL

thank you guys for all the clarifications :+1: :+1: 

I'm not able at the moment to provide a PR because I'm not an Eclipse registered contributor,
also there a lot of specs to respect that are time consuming to study 
and maintained only in the sake of backward compatibility 
so I don't know if my PRs will be accepted 

In the meantime I'll override the default FacesConverters 
with an ApplicationScoped version or I'll try to fork mojarra

**Comment by BalusC** [comment]
https://github.com/eclipse-ee4j/mojarra/issues/5068
