### ISSUE TITLE
Faces Validation config parameters default value and deprecation

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5069]
Talking with @BalusC on a previous issue he said to me that

[https://github.com/eclipse-ee4j/mojarra/issues/5043#issuecomment-1048086850](url)

> As to the params, the `jakarta.faces.VALIDATE_EMPTY_FIELDS` already defaults to `true` 
> and the other two have indeed an unfortunate default of `false` in name of strict backwards 
> compatibility. Although I'm personally not against flipping the defaults in a new major version .. 
> Feel free to open a new issue specifically on that.

So I'm asking if it is not better to set 

`jakarta.faces.ALWAYS_PERFORM_VALIDATION_WHEN_REQUIRED_IS_TRUE = true`

and 

`jakarta.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL = true `

Probably these two parameters should be deprecated and removed as they bring more confusion than value

[https://balusc.omnifaces.org/2015/10/the-empty-string-madness.html](url)

**Comment by mnriem** [comment]
@pizzi80 Can you please open this issue at the API project as it is a change in behavior. Thanks!

**Comment by BalusC** [comment]
https://github.com/jakartaee/faces/issues/1647
