### ISSUE TITLE
NullPointerException NPE from CompositeComponentStackManager

### ISSUE THREAD

**Issue by udengaardandersent-ELS** [eclipse-ee4j/mojarra#5070]
I see a NullPointerException happens when libraryName of the resource is null. (Running Mojarra 2.3)

https://github.com/eclipse-ee4j/mojarra/blob/6143ed8d9966b33fa202492005703b032692cb11/impl/src/main/java/com/sun/faces/component/CompositeComponentStackManager.java#L179
and here
https://github.com/eclipse-ee4j/mojarra/blob/6143ed8d9966b33fa202492005703b032692cb11/impl/src/main/java/com/sun/faces/component/CompositeComponentStackManager.java#L189

This is a valid usecase according to the documentation of Resource
```
    /**
     * <p class="changed_added_2_0">
     * Return the libraryName for this resource. May be <code>null</code>. The libraryName for a
     * resource is an optional String that indicates membership in a "resource library". All
     * resources with the same libraryName belong to the same "resource library". The "resource
     * library" concept allows disambiguating resources that have the same resourceName. See
     * {@link ResourceHandler} for more information.
     * </p>
     *
     * @return Return the libraryName for this resource. May be <code>null</code>.
     */
```

The error happens from within the string.contains method (Running OpenJDK 11)
```
    /**
     * Returns true if and only if this string contains the specified
     * sequence of char values.
     *
     * @param s the sequence to search for
     * @return true if this string contains {@code s}, false otherwise
     * @since 1.5
     */
    public boolean contains(CharSequence s) {
        return indexOf(s.toString()) >= 0;
    }
```

**Comment by BalusC** [comment]
Understood, but do you have a reproducer? Composite component resources cannot have a null library name in first place. They are by specification required to be placed in a subfolder of resources folder (that subfolder becomes the library name). So if a composite component library name turns out to be null then that would strongly suggest that there's something corrupted.

**Comment by udengaardandersent-ELS** [comment]
> Perhaps the composite was programmatically created in a wrong way?

I'm indeed working with dynamic composite components.
I'm working on migration an application to a newer version of mojarra, and these errors started to appear.

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
