### ISSUE TITLE
Composite components inside composite components

### ISSUE THREAD

**Issue by Exandra** [eclipse-ee4j/mojarra#5076]
**Describe the bug**

We’re using composite components inside composite components. E.g. we are using dataTables inside dataTables. (e.g. expanded dataTable with PrimeFaces p:rowExpansion). 

Since 2.3.17 (WildFly 26) we encounter the problem, that the inner components *var* value is empty (after an update), when both the inner and outer component are using the same ID. Prior 2.3.17 everything worked fine and myfaces implementations are not affected as well. I don’t think problem has been fixed by #5065, either. (at least branch 2.3 didn't work for me?)

**To Reproduce**

Steps to reproduce the behavior: (based on primefaces-test with h:dataTables and f:ajax)

1.	git clone https://github.com/Exandra/primefaces-test.git
2.	cd primefaces-test
3.	mvn clean jetty:run -Pmojarra23
4.	Open "http://localhost:8080/primefaces-test/"
5.	Click on the "Toggle Render Car Plates" button. The values oft the inner dataTables are empty (e.g. Acura => ERROR)
6.	Quit jetty ctrl + c
7.	mvn clean jetty:run -Pmojarra22
8.	Repeat steps 4 and 5. The result will be something like Acura => fd077c

As a workaround change the ID of the h:dataTable inside the dataTable component.

**Expected behavior**

The inner composite component should retain its values even after an update, while using the same id as the outer component.

**Screenshots**

* [Working example](https://github.com/Exandra/primefaces-test/blob/master/assets/images/working.png)
* [Not working](https://github.com/Exandra/primefaces-test/blob/master/assets/images/not_working.png)

**Additional context**

[Issue at Primefaces](https://github.com/primefaces/primefaces/issues/8575)

**Comment by erickdeoliveiraleal** [comment]
reproduced with 2.3.18

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)

**Comment by melloware** [comment]
@erickdeoliveiraleal @Exandra can ew verify this is still an issue with 4.0.3 and if so we can get this ticket re-opened or a new ticket created?

**Comment by BalusC** [comment]
Same issue as https://github.com/eclipse-ee4j/mojarra/issues/5214
