### ISSUE TITLE
UIRepeat: Dynamically added UIRepeat generates invalid clientID

### ISSUE THREAD

**Issue by fanste** [eclipse-ee4j/mojarra#5077]
**Describe the bug**

In our application we have a dynamicalle added `UIRepeat`. It is added in `PreRenderViewEvent`. The `UIRepeat` itself is contained in a column of a Primefaces DataTable.

When a not-null list is set as the value of the `UIRepeat`, its DataModel is normally intialized with `index = -1` and then overwritten by `setRowIndex(0)`. _(This could also be a 'bug' in my opinion. Why is the index not always `-1` for a newly created DataModel?)_
During Mojarras implementation of `reapplyDynamicActions`, the `UIRepeat` is visited in the method `locateComponentByClientId` for another component, that is removed from the view (just as an info: as the `ComponentStruct` has `parentClientId=null`, the whole tree is visited, and therefore also the `UIRepeat`).

In `UIRepeat#visitTree` [it will cache the old **row index**](https://github.com/eclipse-ee4j/mojarra/blob/02ea0f946cd354767fdd09b60ecb279ca1631490/impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java#L650) of the DataModel. Because of the not-null list, the `rowIndex` is `0` and not `-1`, while the `index` of the `UIRepeat` itself is `-1`.

When `UIRepeat#visitTree` completes, the `finally`-block will [restore the `index` of the `UIRepeat`](https://github.com/eclipse-ee4j/mojarra/blob/02ea0f946cd354767fdd09b60ecb279ca1631490/impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java#L691) by calling `setIndex` but with the previsouly cached `rowIndex` of the DataModel.

So, the state of the `UIRepeat` before `visitTree` is `index=-1, rowIndex=0`, and after `index=0, rowIndex=0`.

This is incorrect as `UIRepeat#getClientId` will now include the `index` if it is `>= 0` - e.g. `dataTable:uirepeat:0` instead of `dataTable:uirepeat`.

As soon as the child components of the `UIRepeat` should be restored by `reapplyDynamicActions`, it uses `invokeOnComponent` which does not expect the iteration index in the clientId and therefore is unable to resolve the `UIRepeat`. (This ends up in a fallback logik of the PrimeFaces DataTable, which thinks, that the ID of the `UIRepeat` must be an interation index of the DataTable which then throws a `NumberFormatException`)

**Expected behavior**

Compared to the MyFaces implementation of `UIRepeat`, the `index` of `UIRepeat` should be cached and not the `rowIndex` of the DataModel.

**Stacktrace off the wrong cached state:**
![image](https://user-images.githubusercontent.com/3531183/163157267-d2bf3391-fe60-416c-93cb-1b6c7eb8ec0b.png)

**Stacktrace of the wrong restored state:**
![image](https://user-images.githubusercontent.com/3531183/163157541-c8680213-6342-454a-933c-fdff2dc9e98a.png)

**Stacktrace on restore of a child of UIRepeat:**
![image](https://user-images.githubusercontent.com/3531183/163158431-d402a67d-c2d7-4107-b056-84e77b0e9bc7.png)

![image](https://user-images.githubusercontent.com/3531183/163158945-13527c2d-de8f-40fc-9511-0ef6369ece3b.png)

![image](https://user-images.githubusercontent.com/3531183/163156138-e9c954d2-a9b3-473b-a882-b26c07d62e7c.png)

Bug occurred with Mojarra 2.2.19 / API 2.2.19, but compared to the newer sources of 3.x, the bug should still be there.  I cannot test it, as I do not have any 3.x or newer infrastructure that I can use for that.

**Comment by fanste** [comment]
Additionally MyFaces has another difference in its implementation:

The method `getClientId` is not overridden and therefore never includes the iteration index. Instead the method `getContainerClientId` is used to get the client ID including the iteration index.

**Comment by melloware** [comment]
Excellent report!

**Comment by fanste** [comment]
I exchanged the UIRepeat with a custom/fixed implementation and until now statically and dynamically used UIRepeat is working just fine.

The only change is to cache `index` instead of `rowIndex`.

**Comment by melloware** [comment]
@fanste are you going to submit a PR or do you want me to?

**Comment by melloware** [comment]
Actually looking at your comments above maybe its best if you submit a PR for review?

**Comment by fanste** [comment]
PR https://github.com/eclipse-ee4j/mojarra/pull/5089

**Comment by BalusC** [comment]
FYI: I ran entire 2.3 test set against (which is way more complete than the Faces TCK in its current form) and all tests passed.

**Comment by BalusC** [comment]
All merged now, thank you very much for reporting this issue and the PR!

**Comment by melloware** [comment]
I believe this also fixed https://github.com/eclipse-ee4j/mojarra/issues/4261

**Comment by fanste** [comment]
As I currently have another bug regarding dynamically added components but this time with two static nested ui:repeat (static == xHTML), just a question regarding an observation:

Why is `SKIP_ITERATION` not set during `reapplyDynamicActions`?

Components are not data related but state related. The tree is always fully available but based on the data, a component is processed or not (like `rendered`, etc). In other words: The tree restore should not take the real data into account.

In my specific case:

```
<ui:repeat value="#{BEAN.list}" var="entryA">
    <ui:fragment rendered="#{entryA.property eq 0}">
        <ui:include ... />
    </ui:fragment>
    <ui:fragment rendered="#{entryA.property eq 1}">
        <ui:include ... />
    </ui:fragment>
</ui:repeat>
```

Include 1
```
does not contain another iterativ component
```

Include 2
```
<ui:repeat value="#{entryA.list}" var="entryB">
   ...
</ui:repeat>
```

The HINTS set is empty. Therefore:
`rendered` is not evaluated (visit all components) and data is applied (missing `SKIP_ITERATION`) -> the ui:repeat in Include 2 throws a PropertyNotFoundException for `entryA.list` as entryA is not of the expected type (ensured by `rendered`)
