### ISSUE TITLE
Dynamcially added UIInstruction (e.g. via Composite Component) not restored

### ISSUE THREAD

**Issue by fanste** [eclipse-ee4j/mojarra#5092]
Currently observed in 2.2.19, but code seems to be the same in newer versions.

**Description**
In our application we are using dynamically added composite components - those components are added in the RenderViewPhase.
Currently it seems like plain HTML is not supported in those dynamic scenarios and a later restore simply drops the plain HTML.

The root cause is, that the plain HTML is parsed as `UIInstructions` and the contents are not handled as child components to that UIInstructions. Instead a custom 'child' list is managed (`instructions`).

The tracking of dynamically added components does only consider UIComponents and its children.

Any chance that this could be enhanced?

**Kind of workaround**
A not fully functional workaround is to not use plain HTML or at least bind make it a JSF component by using e.g. `jsf:id`. But this has another problem:

- Composite components are naming containers
- To update a composite component via AJAX you need a plain HTML element like an `div` and add the the `clientID` of the composite component as the `id` of that HTML element.
- This plain HTML element could not be used as it will not exist anymore after the restore of the view.
- Instead all references on that CC must be adjusted to include the ID of a child component of that CC.

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)

**Comment by melloware** [comment]
@fanste can you verify this is still an issue in 4.0.3 so we can get a new ticket for 4.0.3 created?
