### ISSUE TITLE
In PROJECT_STAGE other than "Production", attributes are not being re-rendered after AJAX requests in some situations

### ISSUE THREAD

**Issue by jensberke** [eclipse-ee4j/mojarra#5094]
**Describe the bug**

When setting `javax.faces.PROJECT_STAGE` to another value than `Production` *and* the page contains a tag from a custom tag library *and*  some more standard components are near this custom tag, global attributes like `style` or `title` of these standard components are not being re-rendered after 2 AJAX requests. See the attached reproducer for more information about when this happens.

**To Reproduce**

1. Download the attached file and unpack it
1. Build the war file with `./gradlew war` and copy the war file to your application server
1. Open the main page of the web app and follow the instructions there

**Expected behavior**

If a component uses standard attributes like `style` or `title`, rendering of these attributes must not depend on the project stage.

**Desktop:**

 - OS: Linux
 - Browser: Firefox 100, Chrome 101, Edge 101

**Smartphone:**

not tested

[attribute-taglib-test.tar.gz](https://github.com/eclipse-ee4j/mojarra/files/8678942/attribute-taglib-test.tar.gz)

**Comment by melloware** [comment]
Interesting we have been using Mojarra for years with Jboss/Wildfly and we run Development Mode locally and Production Mode on our servers and have not noticed this behavior.  Very strange.

**Comment by arjantijms** [comment]
This is a strange one indeed. @BalusC any ideas?

**Comment by melloware** [comment]
Here is a much easier test case:
[mojarra-5094.zip](https://github.com/eclipse-ee4j/mojarra/files/8700188/mojarra-5094.zip)

Just run `mvn clean jetty:run -Pmojarra23` and navigate to http://localhost:8080/primefaces-test/test.xhtml

if you run with `-Pmyfaces23` it works fine but fails with Mojarra as described.

**Comment by BalusC** [comment]
Reproduced. 

Work around for now:
```
    <context-param>
        <param-name>javax.faces.PARTIAL_STATE_SAVING</param-name>
        <param-value>false</param-value>
    </context-param>
```

**Comment by BalusC** [comment]
As @melloware apparently (correctly) guessed, this was fixed in https://github.com/eclipse-ee4j/mojarra/issues/5059 which was only recently backported for 2.3: https://github.com/eclipse-ee4j/mojarra/pull/5095

Against the current 2.3 branch, the reported problem is not anymore reproducible, so closing off.
