### ISSUE TITLE
UIForm: Performance Improvement

### ISSUE THREAD

**Issue by melloware** [eclipse-ee4j/mojarra#5097]
Based on MyFaces fix: https://issues.apache.org/jira/browse/MYFACES-4283

In case when invokeOnComponent is used and the form has prependId=true, we can early skip the whole component tree if the baseClientId != form clientId.

I discovered this while working on this PFE issue: https://github.com/primefaces-extensions/primefaces-extensions/issues/799

```java
    @Override
    public boolean invokeOnComponent(FacesContext context, String clientId, ContextCallback callback) throws FacesException {
        if (isPrependId()) {
            String baseClientId = getClientId(context);

            // skip if the component is not a child of the UIForm
            if (!clientId.startsWith(baseClientId)) {
                return false;
            }
        }

        return super.invokeOnComponent(context, clientId, callback);
    }
```

**Comment by BalusC** [comment]
FYI: all 2.3 tests passed.
