### ISSUE TITLE
html code inside ui:decorate breaks ui:param evaluation

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5140]
**Describe the bug**

If you add normal static html inside an ui:decorate all the ui:param(s) are null!

One of the latest commits broken this ( 2 o 3 days ago )

**To Reproduce**

```
<ui:decorate template="decorate.xhtml">
    <ui:param name="inputId" value="testInputId" />
    <span class="clazz">span</span>
</ui:decorate>
```

**decorate.xhtml**

```
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:o="http://omnifaces.org/ui">

    <h:panelGroup layout="block" id="#{inputId}Field">
        <div>#{inputId}</div>
        <ui:insert/>
    </h:panelGroup>

</ui:composition>
```

**Actual result**

#{inputId} is null!

```
<div id="Field">
  <div></div>
  <span class="clazz">span</span>
</div>
```

**Expected result**

```
<div id="testInputIdField">
  <div>testInputId</div>
  <span class="clazz">span</span>
</div>
```

**Comment by melloware** [comment]
@pizzi80 this is against the 4.0 master code version or another branch?

**Comment by pizzi80** [comment]
the bug is in the current maste, 

so to better test my implementations I've created a branch in my forked mojarra
and then commit / push to master

no problem if I have to commit again, let me know

**Comment by pizzi80** [comment]
today I spent an hour finding the bug with no luck. :(

Maybe @BalusC knows more about what has changed in the last 2 days?

**Comment by melloware** [comment]
Reproducer:
[mojarra-5140.zip](https://github.com/eclipse-ee4j/mojarra/files/8994828/mojarra-5140.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

Issue: https://github.com/eclipse-ee4j/mojarra/issues/4281

Commit: https://github.com/eclipse-ee4j/mojarra/commit/1e187e88fe305352e786aeed5acb65b3d30e46bf

**Comment by BalusC** [comment]
> what has changed in the last 2 days?

Usually glancing over last commits is sufficient: https://github.com/eclipse-ee4j/mojarra/commits/master

**Comment by melloware** [comment]
@BalusC i verified the fix that caused it above and the ticket associated.

**Comment by pizzi80** [comment]
yes, I tried but didn't found the cause 😑

**Comment by melloware** [comment]
I am going to leave this one to @BalusC and @arjantijms to fix because I am hestitant to move that 1 line of code back where it was there might be a more elegant fix.

**Comment by BalusC** [comment]
Fixed it whereby both newly added ITs passed. Will now run entire TCK and see.

**Comment by BalusC** [comment]
TCK passed. Two PRs open now.

**Comment by pizzi80** [comment]
The current master seems ok now!  

it should be possible to close this ticket
