### ISSUE TITLE
Composite component does not reflect locale changes

### ISSUE THREAD

**Issue by cristof** [eclipse-ee4j/mojarra#5160]
**Bug**

According to VDL documentation ([2.3](https://jakarta.ee/specifications/faces/2.3/vdldoc/overview-summary.html), [3.0](https://jakarta.ee/specifications/faces/3.0/vdldoc/), and [4.0](https://jakarta.ee/specifications/faces/4.0/vdldoc/)), "_[t]he normal localization rules for ResourceBundle would apply_" for composite components localized with <composite_component_name>.properties files that uses #{cc.resourceBundleMap}. As such, when using a composite component named custom_button.xhtml and its associated custom_button.properties and custom_button_fr.properties, the change in locale definition should change the displayed messages.

In mojarra and myfaces (2.3, 2.3-next (myfaces), 3.0 and 4.0), the expected behaviour does not occur (as recognized by [BalusC in 2013](https://stackoverflow.com/questions/18134378/how-to-localize-jsf-composite-component).) His proposed hack still works for MyFaces, but I couldn't use it in recent versions of mojarra.

To reproduce

Example project [localized-components](https://github.com/cristof/localized-components) and [localized-web](https://github.com/cristof/localized-web)  are available to show the issue. Please install the first one into your local maven and then compile the second. 
You may deploy localized-web into a tomee-plume versions 8.0.13 (profile jakarta8) and 9.0.0-MX (profile jakarta9) and check the behavior. Go to [localhost:8080/localized-web](http://localhost:8080/localized-web) and change the language.

Expected behavior

The button label should change reflecting the desired language, but it doesn't.

Solution

I'm opening three pull requests that fixes the issue for branches 2.3.18, 3.0.2 and 4.0

**Comment by BalusC** [comment]
Quick review: I noticed that the `getLocalizedProperties()` method was copypasted into both `ClasspathResourceHelper` and `WebappResourceHelper`, which both extend from `ResourceHelper`. Can you please avoid code duplication and move up the method into `ResourceHelper`? See also https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

**Comment by cristof** [comment]
Moved the method as requested in all branches, changing the name to getLocalizedPaths because it will return a list of a single path even if the target path is not a properties resource - so it will be the one and only localized path.

**Comment by cristof** [comment]
Changed [localized-web](https://github.com/cristof/localized-web) project so it is easier to test the issue and the fix. Added readme with instructions there. As this is my first contribution to mojarra, I'm struggling on how I could add a test into the project.

**Comment by BalusC** [comment]
Tests should be added here https://github.com/jakartaee/faces/tree/master/tck

E.g.:
If you've fixed it in 2.3, then add to faces23, it'll also be used against 3.0 and 4.0.
If you've fixed it in 4.0 only, then add to faces40, it won't be used against 2.3 and 3.0.

**Comment by cristof** [comment]
Do I have to open another issue there, or I can use this one as reference for pull requests?

**Comment by melloware** [comment]
@cristof i think you are safe to refernence this issue and also the MyFaces issue you opened in the TCK test.  It would be a great addition since then MyFaces and Mojarra would have to pass the test!

**Comment by cristof** [comment]
Created the TCK test and made the [pull request](https://github.com/jakartaee/faces/pull/1721), as [previously asked](https://github.com/eclipse-ee4j/mojarra/issues/5160#issuecomment-1312483426).

**Comment by melloware** [comment]
Nice work!
