### ISSUE TITLE
ExternalContext.addResponseCookie does not support different properties

### ISSUE THREAD

**Issue by NicolaIsotta** [eclipse-ee4j/mojarra#5165]
**Describe the bug**
~~I've added SameSite to my app cookies using [Tomcat Cookie Processor](https://tomcat.apache.org/tomcat-10.0-doc/config/cookie-processor.html).~~ In some cases (eg. PrimeFaces filedownload) the page breaks beacuse of an IllegalArgumentException thrown by mojarra ExternalContextImpl at this line:
https://github.com/eclipse-ee4j/mojarra/blob/e6519892b9b17b268b7c112191da1ba4e56dd1be/impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java#L765

**To Reproduce**

~~1. Add `<CookieProcessor sameSiteCookies="strict" />` to the context.xml of your app~~
2. Deploy to Tomcat 10
3. Navigate to a page which has p:fileDownload
4. Try to download the file

**Expected behavior**
No exception.

**Screenshots**
![cookie error](https://user-images.githubusercontent.com/18428155/200803502-93923e29-82dd-4c49-902f-6a9257235e38.jpg)

**Additional context**
Tomcat 10.0.20
mojarra 4.0.0
primefaces 12.0.0

**Comment by melloware** [comment]
@NicolaIsotta here is what PrimeFaces code does...

```java
if (applicationContext.getEnvironment().isAtLeastJsf40()) {
       properties.put("SameSite", applicationContext.getConfig().getCookiesSameSite());
}

 context.getExternalContext().addResponseCookie(name, value, properties);
```

**Comment by NicolaIsotta** [comment]
Yeah, I just discovered that Tomcat Cookie Processor is not involved at all. In fact disabling it does not fix the issue.

@BalusC seems like PR #4991 does not work: the default case of the switch cannot be reached since an IllegalArgumentException is thrown by `PREDEFINED_COOKIE_PROPERTIES.valueOf`

**Comment by BalusC** [comment]
Excellent find. This badly slipped through because there's no TCK test for that.

**Comment by BalusC** [comment]
Reminder/note to self: TCK couldn't be created because currently used GF 7.0.0-M4 hasn't it implemented yet and because newer milestones are not in central yet. We need to wait until GF 7.0.0 is released.
