### ISSUE TITLE
4.0.0: Bean Validation doesn't work in composite components

### ISSUE THREAD

**Issue by NicolaIsotta** [eclipse-ee4j/mojarra#5171]
**Describe the bug**
Bean validation is not called for values of composite components.

**To Reproduce**
myComposite.xhtml:
```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:cc="http://xmlns.jcp.org/jsf/composite"
	  xmlns:h="http://xmlns.jcp.org/jsf/html">

	<cc:interface>
		<cc:attribute name="value"/>
	</cc:interface>

	<cc:implementation>
		<h:inputText id="input" value="#{cc.attrs.value}" rendered="#{cc.rendered}" label="Composite input"/>
	</cc:implementation>
</html>
```
index.xhtml:
```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">
	<h:head/>
	<h:body>
		<h:form id="form1">
			<div>
				<h:outputLabel for="composite" value="Composite"/>
				<ezcomp:myComposite id="composite" value="#{index.string1}"/>
				<h:message for="composite:input"/>
			</div>
			<div>
				<h:outputLabel for="simple" value="Simple"/>
				<h:inputText id="simple" label="Simple input" value="#{index.string2}"/>
				<h:message for="simple"/>
			</div>
			<h:commandButton value="Submit"/>
		</h:form>
	</h:body>
</html>
```
Index.java:
```java
package it.emmeduei.mojarra.error;

import jakarta.enterprise.context.RequestScoped;
import jakarta.inject.Named;
import jakarta.validation.constraints.NotEmpty;

@Named
@RequestScoped
public class Index {

	@NotEmpty
	private String string1;

	@NotEmpty
	private String string2;

	public String getString1() {
		return string1;
	}

	public void setString1(String string1) {
		this.string1 = string1;
	}

	public String getString2() {
		return string2;
	}

	public void setString2(String string2) {
		this.string2 = string2;
	}
}
```
Just press the button to submit the form
NB: I have a reproducer project if needed

**Expected behavior**
For both inputs validation should be performed. Instead, only the simple input is validated.

**Screenshots**
![mojarra-error](https://user-images.githubusercontent.com/18428155/201494139-e8330867-be1b-4797-afea-839bb1459553.jpg)

**Additional context**
This seems to be a 4.0.0 regression, using 3.0.2 the validation is performed correctly.
Tried to debug, I found out that here in BeanValidator.validate valueReference is null:
https://github.com/eclipse-ee4j/mojarra/blob/304a997e7c3a12ad618b492c0582c8a06ef03fa9/impl/src/main/java/jakarta/faces/validator/BeanValidator.java#L304-L308
Maybe the cause is the missing override of `getValueReference()` in [`com.sun.faces.facelets.el.ContextualCompositeValueExpression`](https://github.com/eclipse-ee4j/mojarra/blob/8e87575b15a53b915705897768bd684ae2762500/impl/src/main/java/com/sun/faces/facelets/el/ContextualCompositeValueExpression.java)?

**Comment by NicolaIsotta** [comment]
Overriding getValueReference is not enough, because later it fails in BeanValidator.isResolvable.
I had to bring back ValueExpressionAnalyzer from 3.x to make validation work again.

**Comment by melloware** [comment]
@NicolaIsotta did you want to submit a PR for review?

**Comment by NicolaIsotta** [comment]
Well I'm not sure bringing back ValueExpressionAnalyzer is the right way, guess they cut it from 4.0 for a good reason?
Maybe @BalusC can enlighten us.
Also I think this needs a test, it's a pretty unpleasant regression (we found unvalidated data in the production db...)
I'll share if I discover anything else.

**Comment by BalusC** [comment]
Reproduced. I've added an IT.

**Comment by BalusC** [comment]
OK, TCK failed on faces22/cdiMethodValidation .. I'll have to take a second look later.

**Comment by BalusC** [comment]
Hmm .. it was intermittent .. PRs created nonetheless.

**Comment by BalusC** [comment]
Hmm .. it was intermittent .. PRs created nonetheless.

- fix: https://github.com/eclipse-ee4j/mojarra/pull/5172
- test: https://github.com/jakartaee/faces/pull/1720

**Comment by arjantijms** [comment]
> Well I'm not sure bringing back ValueExpressionAnalyzer is the right way, guess they cut it from 4.0 for a good reason?

Well, to reduce the overhead of maintaining our own code, in 4.0 we have been replacing code with standard alternatives where available.

Maybe we could / should analyse why exactly the standard version doesn't work correctly, and whether that may be a bug in the expression language implementation library or the spec.

**Comment by BalusC** [comment]
@NicolaIsotta has already figured out it. PR has been updated.

**Comment by BalusC** [comment]
Merged now.
