### ISSUE TITLE
doctype component ClassCastException

### ISSUE THREAD

**Issue by eproffit2** [eclipse-ee4j/mojarra#5182]
According to VDL documentation ([4.0](https://jakarta.ee/specifications/faces/4.0/vdldoc/h/doctype.html)), the component type for a doctype tag is "jakarta.faces.HtmlDoctype".
In the com.sun.faces.facelets.tag.faces.html.HtmlLibrary class,  it is defiled as a UIOutput.COMPONENT_TYPE instead of a HtmlDoctype.COMPONENT_TYPE. Which leads to ClassCastException when the tag is rendered.

To reproduce, just add a <h:doctype/> tag to any jsf page, and there will be a ClassCastException.

**Comment by melloware** [comment]
@eproffit2 care to submit a PR to fix?
