### ISSUE TITLE
FacesValidator's managed(): wrong javadoc

### ISSUE THREAD

**Issue by NicolaIsotta** [eclipse-ee4j/mojarra#5196]
https://github.com/eclipse-ee4j/mojarra/blob/674095343ce15281d3855c31b535a696135fa1d6/impl/src/main/java/jakarta/faces/validator/FacesValidator.java#L81-L90
converter -> validator
probably a copy-paste leftover

**Comment by melloware** [comment]
Can you submit a PR please?

**Comment by NicolaIsotta** [comment]
Will do. FacesBehavior needs to be fixed too.
