### ISSUE TITLE
DataTable: Navigation from header facet causes the value EL to be re-evaluated

### ISSUE THREAD

**Issue by mihaiDumea** [eclipse-ee4j/mojarra#5213]
Navigation from header facet causes the value EL to be re-evaluated, recreating the bean referenced by the EL in a new scope. This recreation is unnecessary as is for no use and may cause problems. This doesn't happen for navigation from table rows.

**To Reproduce**

Also reported here [https://github.com/primefaces/primefaces/issues/9793](https://github.com/primefaces/primefaces/issues/9793)

**Comment by mnriem** [comment]
@BalusC What timeframe are you looking for cutting the last 2.3 release?

**Comment by BalusC** [comment]
I wanted to release it as soon as PRs are reviewed+merged.
