### ISSUE TITLE
UIData might save many states of components which are in a default state

### ISSUE THREAD

**Issue by jepsar** [eclipse-ee4j/mojarra#5229]
Sorry for not following the template, but I think I can best describe this issue by referring to issue https://github.com/primefaces/primefaces/issues/7369 and PR https://github.com/primefaces/primefaces/pull/10014 of PrimeFaces. PrimeFaces basically uses a copy of  Mojarra UIData, so the same issue might manifest here.

Some background: we have an application running OOM every now and then. Profiling showed that most of the memory was consumed by `SavedState` objects. After debugging, it turned out that UIData was storing many instances which were in default state. This for example happens when you use a custom filter in a `p:column` tag. For each table row, an instance is saved. The amount of saved entries drops drastically when you check on the default / empty state of components.

![Screenshot_2023-04-03_at_16 20 05](https://user-images.githubusercontent.com/7500178/231748186-1db5c92d-7a7c-4db4-b375-b523268ad026.png)

![image](https://user-images.githubusercontent.com/7500178/231748214-eca10411-5140-4375-b87d-89ec091dd130.png)

**Comment by BalusC** [comment]
> so the same issue might manifest here

I've analyzed this and no, it doesn't manifest. The differenceis that `UIData` in Mojarra has this block in `saveDescendantState(UIComponent, FacesContext)` which is absent in PrimeFaces one:

```
            if (state.hasDeltaState()) {
            	getStateHelper().put(PropertyKeys.saved, clientId, state);
            } else if (saved != null) {
            	getStateHelper().remove(PropertyKeys.saved, clientId);
            }
```

Based on source code revision history it was added during https://github.com/eclipse-ee4j/mojarra/issues/2969.
