### ISSUE TITLE
ui:repeat throw duplicate component id error when set jakarta.faces.PARTIAL_STATE_SAVING=false in web.xml

### ISSUE THREAD

**Issue by Harry3014** [eclipse-ee4j/mojarra#5233]
**jsf-impl version**

I use wildfly27 and jsf-impl version is 4.0.0.SP01

**To Reproduce**

web.xml

```xml
<context-param>
  <param-name>jakarta.faces.PARTIAL_STATE_SAVING</param-name>
  <param-value>false</param-value>
</context-param>
```

view

```xhtml
<h:form id="form">
    <ui:repeat value="#{testBean.lists}" var="list">
        <h:selectOneListbox valueChangeListener="#{test.listener}" size="2">
            <f:selectItems value="#{list}" />
            <f:ajax process="@this" />
        </h:selectOneListbox>
    </ui:repeat>
</h:form>
```

model
```java
@Named
@ViewScoped
public class TestBean {
    private static List<String> list1 = Arrays.asList("1", "2");
    private static List<String> list2 = Arrays.asList("3", "4");
    private static List<List<String>> lists = Arrays.asList(list1, list2);

    public void listener(ValueChangeEvent e) {
        message = (e.getOldValue() + " -> " + e.getNewValue());
    }

    public List<List<String>> getLists() {
      return lists;
    }
}
```

**Exception**

When I click one item then throw JSF1007 (duplicate component id error)

java.lang.IllegalStateException: Component ID form:j_idt4:j_idt6 has already been found in the view.
	at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1167)
	at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1156)
	at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1156)
	at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1156)
	at com.sun.faces.application.view.FaceletFullStateManagementStrategy.saveView(FaceletFullStateManagementStrategy.java:674)
	at jakarta.faces.application.StateManager.getViewState(StateManager.java:243)
	at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:493)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:310)
	.....

**Addition context**
If set `jakarta.faces.PARTIAL_STATE_SAVING=true`, it works correctly.

**Comment by BalusC** [comment]
Apart from the concrete problem, may I ask why exactly you're disabling partial state saving? Full state saving is discommended (de-facto deprecated) and subject to be removed in a future Faces version.

**Comment by BalusC** [comment]
FSS will be deprecated in 4.1. See also https://github.com/jakartaee/faces/issues/1829

**Comment by mnriem** [comment]
@Harry3014 As FSS will be deprecated in 4.1 / 5.0 can we close this out as won't fix and assume you are going to use PSS going forward? Or is there a specific reason for using FSS here?

**Comment by BalusC** [comment]
If you wish to use Mojarra 4.0 with FSS use a minimum of Mojarra 4.0.0-M6. That's the last version on which your use case worked for me. This appears to be another regression of https://github.com/eclipse-ee4j/mojarra/pull/4808 but after debugging for over a hour I still couldn't figure out where it goes wrong. As FSS is going to be deprecated nonetheless I didn't feel like continuing. You're of course open to create a PR on this.

**Comment by BalusC** [comment]
Stale, closing off. Moreover FSS has been deprecated as per 4.1.
