### ISSUE TITLE
Not honoring value of -1 for the jakarta.faces.FACELETS_BUFFER_SIZE application parameter

### ISSUE THREAD

**Issue by jamezp** [eclipse-ee4j/mojarra#5262]
In https://github.com/eclipse-ee4j/mojarra/issues/5164 a change was made to honor the default value of 1024. However, the spec also [states](https://jakarta.ee/specifications/faces/4.0/jakarta-faces-4.0.html#a6088):

> A value of -1 will not assign a buffer size on the response. 

This does not seem to be implemented and is just passed to the `HttpServletResponse`.

**To Reproduce**

1. Set the context parameter of `jakarta.faces.FACELETS_BUFFER_SIZE` to `-1`.

**Expected behavior**

The value should not be set on the `jakarta.servlet.http.HttpServletResponse`.

**Additional context**

This fails on WildFly as it tries to allocate a buffer size of less than 0.

**Comment by jamezp** [comment]
If there is a different PR required to get this into 4.0.x let me know and I can create another one.

**Comment by fjuma** [comment]
@jamezp I think a PR is also needed against the https://github.com/eclipse-ee4j/mojarra/tree/4.0 branch.

**Comment by jamezp** [comment]
> @jamezp I think a PR is also needed against the https://github.com/eclipse-ee4j/mojarra/tree/4.0 branch.

Done #5268
