### ISSUE TITLE
UIData: return static empty data model if value is null

### ISSUE THREAD

**Issue by Rapster** [eclipse-ee4j/mojarra#5296]
Macro optimization:

In `UIData#getDataModel`, if value is null, a new instance of an empty datamodel will be returned, instead reuse a static immutable instance.

For example:

```java
private static final DataModel EMPTY_DATA_MODEL = new ListDataModel(Collections.emptyList());

@Override
protected DataModel getDataModel() {
  if (model != null) {
    return (model);
  }

  Object current = getValue();
  if (current == null) {
    setDataModel(EMPTY_DATA_MODEL);
  }
  // etc.
}
```

**Comment by melloware** [comment]
Original Discussion in PrimeFaces: https://github.com/primefaces/primefaces/pull/10426

**Comment by pizzi80** [comment]
Why you didn't create a PR ?

If you can't I'll create one but it's basically a copy/paste of your code ...

**Comment by pizzi80** [comment]
:smiley:  :+1: :+1:

**Comment by BalusC** [comment]
2.3.21 and 4.0.4 have been released with the improvement.
