### ISSUE TITLE
ClientWindow: Custom PrimeClientWindowFactory not being respected

### ISSUE THREAD

**Issue by melloware** [eclipse-ee4j/mojarra#5297]
**Describe the bug**

PrimeFaces has its own PrimeClientWindow and we are switching it for JSF2.3+ support only by overriding the client window factory like this:

```xml
<client-window-factory>org.primefaces.clientwindow.PrimeClientWindowFactory</client-window-factory>
```

This works fine in MyFaces but in Mojarra it does not pick up.  To turn it on we have to enable in `web.xml`

```xml
    <context-param>
        <param-name>javax.faces.CLIENT_WINDOW_MODE</param-name>
        <param-value>url</param-value>
    </context-param>
```

We do NOT have to do this for MyFaces as it overrides the default ClientWindowFactory with our own.  It seems like in Mojarra it is still loading the default ClientWindowFactory first and then overriding with our custom one thus the need to for the `web.xml` param.

PrimeFaces Issue: https://github.com/primefaces/primefaces/issues/10444

PrimeFaces current PR: https://github.com/primefaces/primefaces/pull/10449

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)

**Comment by melloware** [comment]
Thanks @mnriem I have reproduced and opened a new ticket for 4.0.4: https://github.com/eclipse-ee4j/mojarra/issues/5316
