### ISSUE TITLE
Mark 2.3 as EOL

### ISSUE THREAD

**Issue by mnriem** [eclipse-ee4j/mojarra#5298]
Proposal to update main README to reflect:

1. Faces 5.0 - under development
2. Faces 4.0 - stable release
3. Faces 3.0 - legacy release

And mark 2.3 as EOL

**Comment by pizzi80** [comment]
why not mark / remove also the 3.0 branch? 
At the moment I don't see any reason to use 3.0

**Comment by melloware** [comment]
I guess so. MyFaces is still patching 2.3 though current.

**Comment by arjantijms** [comment]
> At the moment I don't see any reason to use 3.0

Same here. 3.0 was part of the transitional Jakarta 9 release, which we dedicated as a release for tool vendors to prepare their products for the javax -> jakarta change. It was never really targeted to users. Various vendors (specifically the ones pushing for this transitional release) therefor skipped it and never had an official Jakarta 9 supported product out.

Users seem to have gotten the message, as there seems to be almost zero demand for Faces 3.0 / Faces 3.0 compatible products. Almost every request is either about Faces 4 or about Faces 2.3. Faces 3.0 barely exists in the minds of people. I might be proven wrong though, but that's my impression.

**Comment by melloware** [comment]
totally agree we had this same discussion about 3.0 over at MyFaces and there was some disagreement on support because it was an "official" release but I would also like to deprecate and drop support for 3.0 and make it 2.3, 4.0. 4.1 support.

**Comment by stolp** [comment]
> I guess so. MyFaces is still patching 2.3 though current.

This is very much appreciated. My guess is that lot of users will be stuck on version 2.3 for quite a while.

**Comment by BalusC** [comment]
Sorry for late response, I was having vacation.

I fully agree to mark 2.3 EOL. But there are still two PRs pending for 2.3 and I'd like to see them merged rather than to throw away them. 
- https://github.com/eclipse-ee4j/mojarra/pull/5287
- https://github.com/eclipse-ee4j/mojarra/pull/5294

Can we at least release a Mojarra 2.3.21 as last one? Or should I nonetheless retarget these PRs to 3.0?

**Comment by melloware** [comment]
One last 2.3.21!
