### ISSUE TITLE
Feature Request: some examples about Mojarra "Action Framework" and "Rest"

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5372]
I've found only this article of January 2014

https://www.manorrock.com/blog/2014/01/13/jsf_tip_56_using_the_action_based_prototype_in_mojarra.html

It would be nice to understand the capabilities of these 2 modules

1) How to include the action module with maven
2) How to use the action framework to reaplace an empty view with only `f:metadata`
3) Why it is better than a Servlet?
4) Is it possible in the future to include the functionality inside the main FacesServlet
    using an Annotation based action framework

5) How to include the rest module 
6) What capabilities has this module? It's a lite version of jersey?

Thanks

PS
There are no info about these 2 modules inside the book "The definitive guide to Jakarta Faces..." ;)

**Comment by BalusC** [comment]
https://github.com/eclipse-ee4j/mojarra/issues/5374
