### ISSUE TITLE
form with enctype="multipart/form-data" does not support large input data (16425 bytes)

### ISSUE THREAD

**Issue by dyegocarmo** [eclipse-ee4j/mojarra#5377]
Beginning with wildfly 30.0.0 parameter with more than 16425 Bytes input data are ignored if form has enctype "multipart/form-data"

 

BackingBean:
package bug;

 

import java.io.Serializable;

 

import jakarta.enterprise.context.RequestScoped;

import jakarta.inject.Named;

 

@Named

@RequestScoped

public class BackingBean implements Serializable{

private String content;

private String test = "1";

public String getContent() {

return content;

}

public void setContent(String content) {

this.content = content;

}

public String getTest() {

return test;

}

public void setTest(String test) {

this.test = test;

}

public void action() {

test +="AAAAAAAAAAAAAAAAAAAAAAA\n";

System.out.println("Size of test:"+test.length());

}

{color:#000000}}

 

index.xhtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"

xmlns:h="jakarta.faces.html"

lang="de">

<h:head>

 

</h:head>

<h:body>

 

<h:form enctype="multipart/form-data" id="testForm">

<h:inputTextarea value="#{backingBean.test}" cols="20" rows="10"/>

<br/>

<h:commandButton value="Submit" action="#{backingBean.action}" id="btn"/>

</h:form>

<script >

document.getElementById("testForm\:btn").click();

</script>

</h:body>

</html>

**Comment by dyegocarmo** [comment]
A complete example working is inside https://issues.redhat.com/browse/WFLY-18821

**Comment by dyegocarmo** [comment]
Version Mojarra inside Wildfly 30 is 4.0.4

**Comment by dyegocarmo** [comment]
tested with mojarra 4.0.5, same problem occurs

**Comment by BalusC** [comment]
Nothing was changed in Mojarra related to that. Mojarra is in the context of this problem merely the user of the multipart/form-data API not the implementor/provider of it. That's the servletcontainer itself (via jakarta.servlet.* implementations such as HttpServletRequest).

Just try a different server to exclude the one and other.

**Comment by BalusC** [comment]
Not an issue in Mojarra itself, closing off.
