### ISSUE TITLE
Can not eval expression in f:attribute

### ISSUE THREAD

**Issue by rsoika** [eclipse-ee4j/mojarra#5378]
**Describe the bug**

I have a component like this one: 

```xml
	<h:inputText value="#{workitem.item[item.name]}" >
		<f:converter converterId="ImixsDateConverter" />
		<f:attribute name="org.imixs.date.timeZone" value="CET" />
	</h:inputText>
```

It is not possible to set the f:attribute value to a EL expression like this :

```xml
		<f:attribute name="org.imixs.date.timeZone" value="#{message.timeZone}" />
```

where '`timeZone`' is defined in a JSF resource bundle. Also evaluating bean values is not possible. 

The value will not be part of the component attribute map that you can access form the `@FacesConverter`

Example Code:

```java
@FacesConverter("ImixsDateConverter")
public class ImixsDateConverter implements Converter, Serializable {

    @Override
    public Object getAsObject(FacesContext context, UIComponent component, String value) {
            String value = component.getAttributes().get('org.imixs.date.timeZone');
            // map does NOT contain the attribute if the value is provided by a EL expression
            
    }
```

Only pure string values are transferred into the attribute map. 

**To Reproduce**

Run the example tag in a Wildfly 27.0.1.Final-jdk11

**Desktop (please complete the following information):**

 - OS: [debian]
 - Browser [firefox]
 - Version [wildfly 27.0.1.Final-jdk11]

**Additional context**

I am running the official Wildfly Docker immage 27.0.1.Final-jdk11

**Comment by BalusC** [comment]
https://stackoverflow.com/q/7530560/157882

**Comment by BalusC** [comment]
We need more context. This works fine for me on Mojarra 4.0.5.

**Comment by rsoika** [comment]
I wonder which Mojarra Version we have in Wildfly 27.0.1  - If I am not wrong it is 4.0.0.SP01. But this is just guessing 

I reduced my code into a minimal example to reproduce the problem:

TestBean.java

```java 
@Named
@ConversationScoped
public class TestBean implements Serializable {
	String value;
	//Just a simple string provider
	public String getTimeZone() { return "UTC+1"; }
	public String getValue() { return value; }
	public void setValue(String value) {this.value = value;}
	public void submit() {System.out.println(value);}
}
```

The Converter Class which seems to cause the issue:


```java 
import java.io.Serializable;
import java.util.Map;
import jakarta.faces.component.UIComponent;
import jakarta.faces.context.FacesContext;
import jakarta.faces.convert.Converter;
import jakarta.faces.convert.FacesConverter;


@FacesConverter("TestConverter")
public class TestConverter implements Converter, Serializable {

   
    @Override
    public Object getAsObject(FacesContext context, UIComponent component, String value) {

        if (value == null || value.trim().isEmpty()) {
            return ""; // Convert null to empty string
        }

        value = value.trim();
        Map<String, Object> map = component.getAttributes();

        // show all attributes
        for (Map.Entry<String, Object> entry : map.entrySet()) {
            System.out.println("Attribute - " + entry.getKey() + ":" + entry.getValue());
        }

     
        return value;

    }

    @Override
    public String getAsString(FacesContext context, UIComponent component, Object value) {
        if (value == null || "".equals(value)) {
            return ""; // Convert null to empty string
        }
        return value.toString();
    }
}
```

**Comment by BalusC** [comment]
The problem is here
```
        // show all attributes
        for (Map.Entry<String, Object> entry : map.entrySet()) {
            System.out.println("Attribute - " + entry.getKey() + ":" + entry.getValue());
        }
```
The entryset of attributes is indeed empty in case of value expressions.

Use `String value = component.getAttributes().get('org.imixs.date.timeZone')` instead.

See also:
- https://jakarta.ee/specifications/faces/4.0/apidocs/jakarta/faces/component/uicomponent#getAttributes()
- https://stackoverflow.com/questions/7684465/valueexpression-map-of-a-jsf-component
- https://github.com/eclipse-ee4j/mojarra/issues/640

**Comment by rsoika** [comment]
Thanks, yes that works. This wasn't obvious to me and I really spent a lot of time testing it out....
