### ISSUE TITLE
Synchronizing on the session object could be ineffectual due to the servlet implentation not providing reference stability

### ISSUE THREAD

**Issue by VsevolodGolovanov** [eclipse-ee4j/mojarra#5380]
Mojarra synchronizes on the session object in some places, but at least Undertow 2.0.15.Final returns a different instance (wrapper) from `HttpServletRequest#getSession` for every request in the same session.
A simple text search of "synchronized (ses" in mojarra-2.3.21-RELEASE sources yields:
```
\impl\src\main\java\com\sun\faces\application\view\ViewScopeContextManager.java
\impl\src\main\java\com\sun\faces\renderkit\ServerSideStateHelper.java
\test\servlet30-isolated\cactus\src\main\java\com\sun\faces\application\DeprStateManagerImpl.java
```

This is issue is a follow up to [this](https://github.com/eclipse-ee4j/mojarra/issues/3743#issuecomment-1843748056).

**Comment by mnriem** [comment]
Can you create a PR for the suggested changes?

**Comment by BalusC** [comment]
I prepped a PR for 4.0. 

Feel free to backport for 2.3.
