### ISSUE TITLE
Startup error on web app with Mojarra+Prime Faces on Wildfly 26

### ISSUE THREAD

**Issue by gullux** [eclipse-ee4j/mojarra#5392]
**Describe the bug**
I'm migrating an old big web application to Mojarra 2.3.21 and Prime Faces 7.
Th application failed to start for the following exception. **The class SearchExpressionUtils has the pubblic method that Mojarra is searching for. May be that getDeclaredMethod use is better in this situation?**

11:54:17,288 INFO  [javax.enterprise.resource.webcontainer.jsf.application] (ServerService Thread Pool -- 79) JSF1048: PostConstruct/PreDestroy annotations present.  ManagedBeans methods marked with these annotations will have said annotations processed.
11:55:23,563 ERROR [stderr] (ServerService Thread Pool -- 79) java.lang.NoSuchMethodException: org.primefaces.expression.SearchExpressionUtils.resolveClientId(java.lang.String, javax.faces.component.UIComponent)

11:55:23,564 ERROR [stderr] (ServerService Thread Pool -- 79) 	at java.base/java.lang.Class.getMethod(Class.java:2108)

11:55:23,564 ERROR [stderr] (ServerService Thread Pool -- 79) 	at deployment.phoenix-tesoreria-ear-2023.11.24.1.ear//com.sun.faces.config.processor.FaceletTaglibConfigProcessor.createMethod(FaceletTaglibConfigProcessor.java:630)

11:55:23,564 ERROR [stderr] (ServerService Thread Pool -- 79) 	at deployment.phoenix-tesoreria-ear-2023.11.24.1.ear//com.sun.faces.config.processor.FaceletTaglibConfigProcessor.processFunctions(FaceletTaglibConfigProcessor.java:591)

11:55:23,564 ERROR [stderr] (ServerService Thread Pool -- 79) 	at deployment.phoenix-tesoreria-ear-2023.11.24.1.ear//com.sun.faces.config.processor.FaceletTaglibConfigProcessor.processTagLibrary(FaceletTaglibConfigProcessor.java:278)

11:55:23,564 ERROR [stderr] (ServerService Thread Pool -- 79) 	at deployment.phoenix-tesoreria-ear-2023.11.24.1.ear//com.sun.faces.config.processor.FaceletTaglibConfigProcessor.process(FaceletTaglibConfigProcessor.java:232)

**Comment by BalusC** [comment]
You still have the previous version of PrimeFaces somewhere in runtime classpath.

**Comment by melloware** [comment]
Agreed with @BalusC it seems like you have a mismatch of JARs in your classpath.

**Comment by gullux** [comment]
I've spent several days searching another prime faces on my classpath: there is not.
Same problem with Prime Faces 8 and 13. The problem does not appear with MyFaces.
I'm using JDK 11, i've tryed Temurin and Oracle runtime.
During  debugging i can find this methods invoking getDeclaredMethods

[public static javax.faces.component.visit.VisitContext org.primefaces.expression.SearchExpressionUtils.createVisitContext(javax.faces.context.FacesContext,int), public static java.lang.String org.primefaces.expression.SearchExpressionUtils.resolveClientIds(java.lang.String,javax.faces.component.UIComponent),
 public static java.lang.String **org.primefaces.expression.SearchExpressionUtils.resolveClientId(java.lang.String,javax.faces.component.UIComponent),** p
 ublic static java.lang.String org.primefaces.expression.SearchExpressionUtils.resolveWidgetVar(java.lang.String,javax.faces.component.UIComponent), public static boolean org.primefaces.expression.SearchExpressionUtils.isHintSet(int,int), public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException, public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException, public final void java.lang.Object.wait() throws java.lang.InterruptedException, public boolean java.lang.Object.equals(java.lang.Object), public java.lang.String java.lang.Object.toString(), public native int java.lang.Object.hashCode(), public final native java.lang.Class java.lang.Object.getClass(), public final native void java.lang.Object.notify(), public final native void java.lang.Object.notifyAll()]


It seams the correct class is in the class loader but for some reason getMethod can't get it. Here the getMethod javadoc:

_Returns a Method object that reflects the specified publicmember method of the class or interface represented by this Class object. The name parameter is a String specifying the simple name of the desired method. The parameterTypes parameter is an array of Classobjects that identify the method's formal parameter types, in declaredorder. If parameterTypes is null, it istreated as if it were an empty array. 

If this Class object represents an array type, then thismethod finds any public method inherited by the array type from Object except method clone(). 

If this Class object represents an interface then thismethod does not find any implicitly declared method from Object. Therefore, if no methods are explicitly declared inthis interface or any of its superinterfaces, then this method does notfind any method. 

This method does not find any method with name "<init>" or"<clinit>". 

Generally, the method to be reflected is determined by the 4 stepalgorithm that follows.Let C be the class or interface represented by this Class object: 
1. A union of methods is composed of: a. C's declared public instance and static methods as returned by getDeclaredMethods() and filtered to include only publicmethods that match given name and parameterTypes
b. If C is a class other than Object, then include the resultof invoking this algorithm recursively on the superclass of C.
c. Include the results of invoking this algorithm recursively on alldirect superinterfaces of C, but include only instance methods.

2. This union is partitioned into subsets of methods with samereturn type (the selection of methods from step 1 also guarantees thatthey have the same method name and parameter types).
3. Within each such subset only the most specific methods are selected.Let method M be a method from a set of methods with same VMsignature (return type, name, parameter types).M is most specific if there is no such method N != M from the sameset, such that N is more specific than M. N is more specific than Mif: a. N is declared by a class and M is declared by an interface; or
b. N and M are both declared by classes or both by interfaces andN's declaring type is the same as or a subtype of M's declaring type(clearly, if M's and N's declaring types are the same type, thenM and N are the same method).

4. The result of this algorithm is chosen arbitrarily from the methodswith most specific return type among all selected methods from step 3.Let R be a return type of a method M from the set of all selected methodsfrom step 3. M is a method with most specific return type if there isno such method N != M from the same set, having return type S != R,such that S is a subtype of R as determined byR.class.isAssignableFrom(S.class). 
Parameters:name the name of the methodparameterTypes the list of parametersReturns:the Method object that matches the specified name and parameterTypesThrows:NoSuchMethodException - if a matching method is not foundor if the name is "<init>"or "<clinit>".NullPointerException - if name is nullSecurityException - If a security manager, s, is present andthe caller's class loader is not the same as or anancestor of the class loader for the current class andinvocation of s.checkPackageAccess() denies access to the packageof this class.Since:1.1API Note:There may be more than one method with matching name andparameter types in a class because while the Java language forbids aclass to declare multiple methods with the same signature but differentreturn types, the Java virtual machine does not. Thisincreased flexibility in the virtual machine can be used toimplement various language features. For example, covariantreturns can be implemented with bridge methods; the bridgemethod and the overriding method would have the samesignature but different return types. This method would return theoverriding method as it would have a more specific return type.@jls8.2 Class Members@jls8.4 Method Declarations_

**Comment by melloware** [comment]
I use PrimeFaces 11, 12, 13 on Wildfly 26 without issue?

**Comment by BalusC** [comment]
Mojarra 2.3 and PrimeFaces 7 exist for years and are used by thousands by developers and yet you're the first one to face this issue. Surely there's something awful in runtime classpath config. Can you reproduce this using a brand new project like one based on https://github.com/primefaces/primefaces-test?

**Comment by gullux** [comment]
![image](https://github.com/eclipse-ee4j/mojarra/assets/125463608/9f8991f3-05a5-4787-a9ff-e0193b451ab5)

**Comment by gullux** [comment]
Java 11 was released 25th September 2018 and now i'm using the last java 11 release jdk-11.0.22+7.
Wildfly 26 on December 16, 2021

so may be not a lot a people have tryed this combo

**Comment by gullux** [comment]
getMethod accept Class<?> ..., pc is an array of class, may be this an issues for JDK 11?
![image](https://github.com/eclipse-ee4j/mojarra/assets/125463608/9068db23-c5ba-4875-8c69-c8102be830e7)

**Comment by gullux** [comment]
I've wrote this fix (downloading source code) and tested on my environment and it works! Application start and works great!

![image](https://github.com/eclipse-ee4j/mojarra/assets/125463608/9130be9d-0666-4587-a7ec-3047b6bb7da7)

**Comment by melloware** [comment]
So i guess its possible JDK11 removed something in a later release but that would be very odd.

**Comment by BalusC** [comment]
Based code logic visible so far in your screenshot, another probable cause is that there are duplicate occurrences of `UIComponent` class, each loaded by a different classloader. This in turn means that there are duplicate JSF API JAR files in the runtime classpath. Just remove the duplicate API JAR.

**Comment by gullux** [comment]
I haven't added jsf-api jar specifically because Wildfly already provides its own. I've just see that Mojarra has UIComponent too so may be this is the duplication that you think?

**Comment by BalusC** [comment]
WildFly provides Mojarra as well. So your project should be completely free of JSF/Mojarra dependencies.

I just downloaded 26.1.3 and noticed it has Mojarra 2.3.17 not 2.3.21. So you've probably manually updated it. How exactly have you done that?

**Comment by gullux** [comment]
Hi, i haven't updated Mojarra embedded on WF. I'm using last version of Mojarra 2.3.21 that is present inside the ear of the application. The application has isolated classloader policy (<ear-subdeployments-isolated>true</ear-subdeployments-isolated> inside the file jboss-deployment-structure). So my application should not see other Mojarra version (and other ear present jars)

**Comment by BalusC** [comment]
The problem being reported in this issue suggests otherwise. Something's definitely wrong in the runtime classpath. I'm also surprised that this detail was left out in the initial report because it's an unusual approach. Have you at least tried it on a stock WildFly without supplying Mojarra via EAR? Have you also tried upgrading Mojarra in WildFly itself rather than supplying it via EAR?

**Comment by gullux** [comment]
Is for you unusual classloader isolation? this is a very odd affermation. 
This policy is present in all J2EE application server from years and in my opionion because it's widely used to avoid problem with libraries and ensure application server portability.

I wont upgrade a Wildfly distribution, i want have a portable application on Jboss, Wildfly, Websphere etc.

Mojarra 2.3.21 has a bug with that situation. Can you fix that or i should migrate my application to MyFaces?

**Comment by BalusC** [comment]
Sorry, I was just trying to nail down the cause because I haven't been able to reproduce it and the proposed fix is not the correct solution.

**Comment by BalusC** [comment]
Just to exclude the one and other: does everything work fine when you remove Mojarra from WAR? (and thus when you rely on server-provided JSF API/impl)

**Comment by gullux** [comment]
i can try this, just for clear: you are asking to remove the jakarta.faces-2.3.21.jar from ear? only this one?

**Comment by BalusC** [comment]
Okay. So it's not a bug which we can fix from Mojarra side on, sorry.

As to EAR structure, technically speaking you should be placing Mojarra/PrimeFaces in WAR (in WEB-INF/lib folder) not in EAR (in lib folder). Think again, you're not supposed to use any web-related APIs/frameworks such as JSF/Mojarra/PrimeFaces in business service code in EAR such as EJB beans. Retry that way.

**Comment by gullux** [comment]
I'm sorry but putting web libraries inside the war is not always a good idea. We have 8 web application inside the EAR. So we should have 8 times the same libraries in different war.

Bug definition is not clear, but we can assume that it's not possible to use Mojarra in ear with classloader isolation. This can be not a bug but it's an important limitation that people must know.

**Comment by melloware** [comment]
I still don't know why you are including a mojarra jar in your ear when you are deploying to a JeE container which by definition has to have a JSF implementation. I know you mentioned portability but that is what JEE spec is for you program to the spec libraries the container provides and not include it yourself?  In this case WildFly has Mojarra class loaded already. If you were using Apache Tomee it provides MyFaces etc.  

Can you explain why you are including mojarra?

**Comment by gullux** [comment]
I repeat myself: the original choice of including Mojarra inside the distribution was to ensure portability between application server (Jboss, Websphere, etc).
This application is a part of a wider system and the system is a product, so we have different customer. 

I already changed this (because i've no other choice) and now applications has not classloader isolated.
This is an important strategical product character change that i hope our market will approve

**Comment by melloware** [comment]
Right but what you are doing goes **AGAINST JEE** portability not for it.  JEE portability comes in knowing that every EE container MUST have a JPA, JSF, Servlet, etc as part of Weblogic, WildFly, Tomee, et.

Yet you are including your own JSF JAR going against portability makes no sense to me?

**Comment by BalusC** [comment]
> I'm sorry but putting web libraries inside the war is not always a good idea. We have 8 web application inside the EAR. So we should have 8 times the same libraries in different war.

Okay that explains the root cause of the problem. Sorry the size concern is not a valid excuse to use an EAR this way. It's just a technical requirement/expectation. The EAR/lib may not be used for code in WAR. It should only be used for code in EJB, outside WAR. Sure it may sometimes work but that should not be relied upon.
