### ISSUE TITLE
Faces Lifecycle LOGGER log exceptions at WARNING Level

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5404]
**Describe the bug**

Faces internal `LIFECYCLE` `LOGGER` 

log at `WARNING` Level  the exception before re-throw it as `FacesException`

For example inside the class `InvokeApplicationPhase`

```
try {
    root.processApplication(facesContext);
} catch (RuntimeException re) {
    String exceptionMessage = re.getMessage();
    if (null != exceptionMessage) {
        if (LOGGER.isLoggable(Level.WARNING)) {
            LOGGER.log(Level.WARNING, exceptionMessage, re);
        }
    }
    throw new FacesException(exceptionMessage, re);
}
```

**Expected behavior**

do NOT log it  or  log  at FINE(er)? level... ?

**Additional context**

https://stackoverflow.com/questions/46241248/jsf-warning-is-logged-before-custom-exception-handler-is-called-glassfish-payar

**Comment by BalusC** [comment]
Agreed.
