### ISSUE TITLE
Component default required attribute is evaluated differently with xhtml/java implementation

### ISSUE THREAD

**Issue by chaloma1** [eclipse-ee4j/mojarra#5417]
**Describe the bug**

1) Component with required attribute and **default parameter specified in xhtml interface** definition ignores calling java methods in xhtml like #{true} or #{xxxController.isComponentRequired}. If the required attribute is set as **plain string "true", then it works**.

2) Component **with not defined default value** in xhtml works with both #{true}, #{xxxController.isComponentRequired} or plain string "true"

3) Component with overriden isRequired() method using "required" instead PropertyKeys.required string as in UIInput parent class (you can add default value here if attribute is not found or set). Works with #{true} or #{xxxController.isComponentRequired} **but not with plain string like "true"**.

**To Reproduce**

[primefaces-test-git.zip](https://github.com/eclipse-ee4j/mojarra/files/14615081/primefaces-test-git.zip)
See the attached sample. You can execute the sample with mvn jetty:run command and hit http://localhost:8080/primefaces-test to run the page.

**Expected behavior**

Implementation type should not matter (at least the required attribute within xhtml component interface) and all of those values should have the same required result.

In the sample project i also tried using non-component specific attribute for FirstComponent like "styleClass" which is working ok even with default value.

**Environment**

I used primefaces test project to reproduce the issue. Sample is using Mojarra 4.0.5 version.

**Comment by melloware** [comment]
@chaloma1 does the same happen with MyFaces 4?  `mvn clean jetty:run -Pmyfaces40` ?

**Comment by melloware** [comment]
Just to be clear its a bug in MyFaces too?

**Comment by chaloma1** [comment]
Default set in xhtml is fixed in MyFaces -> so this seems like a **bug in Mojarra only**
Default set by overriding isRequired method in Component class works the same in MyFaces as in Mojarra (which means it does not recognize plain string value -> required="true" while inserting component to a page) -> **bug in Mojarra and MyFaces** as well

**Comment by melloware** [comment]
OK can you open a MyFaces ticket too please: https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4655?filter=allopenissues

**Comment by chaloma1** [comment]
Sure, just need few days until new Jira account is created.

**Comment by chaloma1** [comment]
Issue at MyFaces created https://issues.apache.org/jira/browse/MYFACES-4656.

**Comment by BalusC** [comment]
Again the EL literal vs VE matter.

Work around for now, use `default="#{false}"` instead of `default="false"`.

**Comment by BalusC** [comment]
By the way, this`System.out.println` makes no sense:
```
  public FirstComponent() {
    super();
    System.out.println("First component: " + this.getClientId() + " " + this.isRequired());
  }
```
The attributes can't be set before construction.

**Comment by chaloma1** [comment]
> By the way, this`System.out.println` in your test project makes no sense

Tried multiple things because i was not sure how the default parameter was applied at that time. But yes, you are correct, thanks.

**Comment by chaloma1** [comment]
> Work around for now, use `default="#{false}"` instead of `default="false"`.

Works, thanks. 

The ThirdComponent with overriden isRequired method is still a mystery though.

**Comment by chaloma1** [comment]
Third component problem with overriden isRequired method was solved in MyFaces ticket. Fault was on my side, when i was looking at the stateHelper eval function i did not notice that "required" isnt the same as PropertyKeys.required enum. The eval function looks for key.toString() only for the value expressions. So literal value was not found.

If anyone uses 

```
@Override
public boolean isRequired() {
  return (Boolean) getStateHelper().eval("required", false);
}
```
then setRequired is needed as well

```
@Override
public void setRequired(boolean required) {
  getStateHelper().put("required", required );
}
```

**Comment by BalusC** [comment]
The override is unnecessary unless you want to perform additional action but then you should be doing something like:
```
@Override
public boolean isRequired() {
    boolean required = super.isRequired();
    additionalAction(required);
    return required;
}
```

**Comment by pktripathy** [comment]
This fix has broken default value implementation in composite component. InstanceFactory.pushDeclaredDefaultValuesToAttributesMap no longer adds attributes to attrs, so default attributes which is not supplied in call to composite component is not available in attrs.

**Comment by melloware** [comment]
@pktripathy please open a new issue then with your details.

**Comment by BalusC** [comment]
Mentioned regression has been fixed as per https://github.com/eclipse-ee4j/mojarra/issues/5460
