### ISSUE TITLE
is this a typo? and/or a bug?: com.sun.faces.numberOfConcerrentFlashUsers 

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5420]
com.sun.faces.config.WebConfiguration 

line 761

`NumberOfConcurrentFlashUsers("com.sun.faces.numberOfConcerrentFlashUsers", "5000"),`

**Describe the bug**

`com.sun.faces.numberOfConcerrentFlashUsers`

**Expected behavior**

`com.sun.faces.numberOfConcurrentFlashUsers`

**Comment by arjantijms** [comment]
Probably a typo, thanks for reporting :)
