### ISSUE TITLE
Faces API 5.0 and Mojarra master

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5421]
After the split of Faces API  I'm not sure how it's better 
to locally build/install Mojarra snapshot 
and how to contribute with PR to the master

May someone create a release or pre-release or whatever of 4.1 and or 5.0 ?

I've made a lot of changes in my fork and I would like to align 
and make some PR to the master one day, but at the moment I'm stuck
in the middle of nowhere

**Comment by BalusC** [comment]
Yes there were a bunch of things off. We've fixed this in Faces and Mojarra projects.

Procedure:
1. Checkout `5.0` branch of https://github.com/jakartaee/faces
2. CD into `api` module.
3. `mvn clean install -Pstaging`
4. Checkout `master` branch of https://github.com/eclipse-ee4j/mojarra
5. `mvn clean install -Pstaging`
6. GAV are as follows:
    ```xml
    <dependency>
        <groupId>jakarta.faces</groupId>
        <artifactId>jakarta.faces-api</artifactId>
        <version>5.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>org.glassfish.mojarra</groupId>
        <artifactId>mojarra</artifactId>
        <version>5.0.0-SNAPSHOT</version>
    </dependency>
    ```

---

Note that `-Pstaging` is only necessary when the pom happens to reference JEE dependencies not yet in Maven Central. If you don't want to use `-Pstaging` every time, then add this to your `~/.m2/settings.xml`:
```
<repositories>
    <repository>
	    <id>jakarta-staging</id>
	    <snapshots />
	    <url>https://jakarta.oss.sonatype.org/content/repositories/staging</url>
    </repository>
</repositories>
```
