### ISSUE TITLE
jakarta.faces.ViewState as GET parameter

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5444]
**Describe the bug**

The `jakarta.faces.ViewState` value is evaluated from GET parameters

is it a spec requirement?

can we make some check to avoid exceptions and `ViewExpiredException`?

**To Reproduce**

Exception
https://showcase.omnifaces.org/?jakarta.faces.ViewState=1
https://showcase.omnifaces.org/?jakarta.faces.ViewState=-1
https://showcase.omnifaces.org/?jakarta.faces.ViewState=1234

ViewExpired
https://showcase.omnifaces.org/?jakarta.faces.ViewState=
[https://showcase.omnifaces.org/?jakarta.faces.ViewState=1234:](https://showcase.omnifaces.org/?jakarta.faces.ViewState=1234:)

**Expected behavior**

Do not process jakarta.faces.ViewState as GET parameter, Or avoid exceptions ...

**Comment by tandraschko** [comment]
in general RestoreViewPhase should be skipped on a GET request, right?

**Comment by BalusC** [comment]
The spec doesn't restrict it to a particular HTTP request method: https://jakarta.ee/specifications/platform/10/apidocs/jakarta/faces/render/responsestatemanager#isPostback(jakarta.faces.context.FacesContext)

I think this was a smart move and that the observed exceptions on GET needs to be dealt with separately.
