### ISSUE TITLE
FaceletViewHandlingStrategy handleRenderException log exception before rethrow

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5449]
**Describe the bug**

`FaceletViewHandlingStrategy.handleRenderException`  line 944

1) logs the exception at `SEVERE` Level 
2) then rethow with a custom algorithm

**Expected behavior**

1) logs the exception at `FINE` Level
2) rethrow it as a `FacesException`

**Comment by BalusC** [comment]
Related: https://github.com/eclipse-ee4j/mojarra/issues/5404

**Comment by BalusC** [comment]
1. Level is fixed, it indeed caused duplicate logs (as the container by default indeed already deals with it).
2. Rethrow is correct as it is, so nothing changed there.
