### ISSUE TITLE
 class-level bean validation: Array data not copied after bean cloning

### ISSUE THREAD

**Issue by thomaspries** [eclipse-ee4j/mojarra#5450]
**Describe the bug**

After cloning the bean, all scalar values are copied into the new bean for validation, but modified data in array stay at initial value altough the input values are converted an validated correctly. 

**To Reproduce**

1. Follow one of the ubiquitous password-examples for WholeBeanValidation in JSF (e.g. [this one](https://hantsy.gitbook.io/java-ee-8-by-example/jsf/jsf-validatewholebean))
2. make simple Datatype 
```
class TestData{ 
int a; 
int b; 
... }
``` 
4. add 
```
TestData[] data;
```
to Backingbean and initialise the array with some data (to verify, that conversion and validation of `TestData` works, add scalar `TestData x1;`)
6. I'm uncertain, if i have to allocate a new Array in the clone method by hand or not, tried both, same effect
7. add Converter and Validator for TestData-type
8. gather data in facelet via 
```
<ui:repeat value="#{testController.data}" varStatus="status" var="d">
  <h:inputText id="valInput_#{status.index}" value="#{testController.data[status.index]}">
     <f:validator validatorId="testDataFacesValidator"/>
     <f:validateBean validationGroups="ValidationGroup"/>
   </h:inputText>
</ui:repeat>
``` 
9. Validation phase: 
```
public class PasswordValidator implements ConstraintValidator<Password, PasswordHolder> {

  @Override
  public void initialize(Password constraintAnnotation) { }

  @Override
  public boolean isValid(PasswordHolder value, ConstraintValidatorContext context) {
    boolean result;

    // both password strings are visible with new data => ok
    // scalar TestData is visible with new data => ok
    // array still contains initial values => not ok

    return result;
  }
}
```

**Expected behavior**

I would like to see altered data in the array to validate them together with the other data.

**Desktop**

 - Client OS: Win 11
 - Server OS: NetBSD
 - payara-6.2024.2
 - Browser Firefox 126
 -  Mojarra 4.0.0.payara-p2

**Comment by BalusC** [comment]
This is a known limitation. Nested properties aren't supported by `<f:validateWholeBean>`.

Consider using [OmniFaces `<o:validateBean>`](https://showcase.omnifaces.org/validators/validateBean) instead. It will also greatly reduce the boilerplate.

1. Remove all `<f:validateBean>` and `<f:validateWholeBean>` tags.
2. Remove `Cloneable` interface and `clone()` method from backing bean.
3. Put `@jakarta.validation.Valid` annotation on `private TestData[] data;` property of backing bean.
4. In place where the `<f:validateWholeBean>` tag was originally located in XHTML, add the `<o:validateBean>` with exactly the same attributes:

```xml
<o:validateBean value="#{testController}" 
		                         validationGroups="ValidationGroup" />
```

Note that you can further simplify the `<ui:repeat>` on `data` as follows as well:

```xml
<ui:repeat value="#{testController.data}"var="d">
  <h:inputText id="valInput" value="#{d.a}"> <!-- and another one for #{d.b}? -->
     <f:validator validatorId="testDataFacesValidator"/>
   </h:inputText>
</ui:repeat>
```
Also note that using EL in ID attribute of `<h:inputText>` within `<ui:repeat>` has no effect. It has only effect when you use `<c:forEach>` instead but that's not necessary.

**Comment by thomaspries** [comment]
Thank's for your response (I somehow missed that fact in the documentation), OmniFaces looks promising, I will use that.
