### ISSUE TITLE
Remove dependencies on SOAP web servcies

### ISSUE THREAD

**Issue by lprimak** [eclipse-ee4j/mojarra#5451]
**Describe the bug**

Jakarta EE 11 will not support SOAP.
EE 11 API have workaround to remove WS from Faces.
Is it possible just to remove SOAP from Faces for EE 11?

Relates  / Supersedes https://github.com/jakartaee/faces/issues/1913
fixed by #5453

**Comment by lprimak** [comment]
Waiting on 4.1 release

**Comment by lprimak** [comment]
@arjantijms @BalusC Please release new 4.1.x as soon as you can so workarounds in EE API artifacts can be removed.
Thank you!

**Comment by lprimak** [comment]
Hey guys, can we release 4.1.1 please?
Thank you!

**Comment by BalusC** [comment]
Hi,

Yes I made a start the last time you asked me, but TCK didn't work and it
confused me big time. I'll take a second look.

Cheers, B

**Comment by BalusC** [comment]
4.1.1 has been released.
