### ISSUE TITLE
U+FFFE and U+FFFF characters can block JSF applications by rendered as ajax response

### ISSUE THREAD

**Issue by halcsi19790320** [eclipse-ee4j/mojarra#5463]
Theese characters are valid UTF-8 characters, but can cause error, if server send this value to browser as ajax response.
Browser's cannot parse theese characters.

Remove non-xml character from Request with converter, or default validator with RenderResponse patch?

[stackowerflow link](https://stackoverflow.com/questions/78770904/browsers-behavior-utf-8-page-with-extra-character-like-ufffe-error-by-ajax-x/78797369#78797369)

The problem is issued 4 four years ago, but I think there are 2 more characters.

[Old issue](https://github.com/eclipse-ee4j/mojarra/issues/4516)

**Comment by BalusC** [comment]
--> https://github.com/eclipse-ee4j/mojarra/issues/5464
