### ISSUE TITLE
Support new resolvers from Expression Language 6 

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/mojarra#5480]
Expression Language 6 added two new resolvers; the OptionalELResolver for Optional, and the RecordELResolver. These are not automatically used in Faces/Mojarra, since we build our own chain explicitly.

We should support them for 4.1.x, and for 5.0 probably add them as requirement in the spec.

See also https://github.com/eclipse-ee4j/glassfish/issues/25052

**Comment by BalusC** [comment]
Changes already merged into 4.1/5.0, closing off.
