### ISSUE TITLE
cc:attribute elements that have a "default" attribute can not be accessed in FacesComponent

### ISSUE THREAD

**Issue by pktripathy** [eclipse-ee4j/mojarra#5482]
<cc:interface componentType="MyTestComponentType">
<cc:attribute name="ABC" type="boolean" default="true"/>
<cc:implementation>
....
</cc:implementation>

if you call it without supplying attributes ABC
<EXTENSION:COMPNAME>

Then call to get attribute in MyTestComponentType  does not have ABC. Only attribute explicitly defined in call to <EXTENSION:COMPNAME> appears in attribute map.
Map<String, Object> attribMap = this.getAttributes();

This has been introduced in 4.0.7. It works in 4.0.6

InstanceFactory.pushDeclaredDefaultValuesToAttributesMap no longer writes to attrs. Because following code has been removed.

                    if (isLiteralText) {
                        try {
                            if (propertyDescriptors == null) {
                                propertyDescriptors = getBeanInfo(component.getClass()).getPropertyDescriptors();
                            }
                        } catch (IntrospectionException e) {
                            throw new FacesException(e);
                        }

                        defaultValue = convertValueToTypeIfNecessary(key, defaultValue, propertyDescriptors, expressionFactory);
                        attrs.put(key, defaultValue);
                    }

**Comment by pktripathy** [comment]
![image](https://github.com/user-attachments/assets/042ce582-6511-46e8-b3d5-e236be287f17)

**Comment by pktripathy** [comment]
Please look into it. Thanks.

**Comment by BalusC** [comment]
Already reported and fixed via https://github.com/eclipse-ee4j/mojarra/issues/5460
