### ISSUE TITLE
EL: Empty values converted to null in version >= 4.0.7?

### ISSUE THREAD

**Issue by Toru47** [eclipse-ee4j/mojarra#5486]
In version <= 4.0.1 empty values from Facelets eg. an empty parameter are converted to an empty string but not to null:

```html
<f:viewAction action="#{fooBean.onload(param['test'])}" /> <!-- Parameter "test" not set! -->
```

```java
public string onload(String test) { // test is an empty string but not null
}
```
In version >= 4.0.7 this is not the case:
```java
public string onload(String test) { // test is null!!!
}
```
Is there a change? Is there an issue (number)? Tested with Wildfly 28 (4.0.1) and WildFly 33.0.1 (4.0.7). Thx.

**Comment by BalusC** [comment]
This is not Mojarra related. HttpServletRequest#getParameter() must return null when param is unspecified, so the behavior observed in WildFly 33.0.1 is correct. Most probably there was a change/fix in WildFly between 28 and 33. cc: @jasondlee

**Comment by BalusC** [comment]
For more consistent and predictable behavior I recommend to use <f:viewParam> to set the request param as a bean property instead of using EL method argument passing. This way you're not dependent on potential bugs in the EL implementation.

```xml
<f:viewParam name="test" value="#{fooBean.test}" />
<f:viewAction action="#{fooBean.onload}" />
```

**Comment by Toru47** [comment]
@BalusC: Many thanks for that advice.

**Comment by BalusC** [comment]
Closing off as not a Mojarra-caused problem.
