### ISSUE TITLE
Reassess that 'View Protection' feature is working as specified

### ISSUE THREAD

**Issue by BalusC** [eclipse-ee4j/mojarra#5503]
As per https://github.com/jakartaee/faces/issues/1369 the 'View Protection' implementation in Mojarra has at first sight incorrect behavior when virtual URLs are used. We need to reassess if this is as per the spec and create TCK-compatible integration tests and eventually fix the implementation where necessary.

**Comment by BalusC** [comment]
Facts:

1. `<protected-views>` in `faces-config.xml` expects `<url-pattern>` children, hereby implying that those are Servlet-specific "URL patterns" and thus NOT Faces-specific "view IDs".
2. The `web-facesconfig_4_0.xsd` literally says "The "url-pattern" element specifies the collection of views [...]" so hereby implying that those should represent view IDs.
3. The [Faces spec](https://jakarta.ee/specifications/faces/4.0/jakarta-faces-4.0#a4030) explicitly refers to servlet spec when saying "URL pattern" in two places: [11.1.12](https://jakarta.ee/specifications/faces/4.0/jakarta-faces-4.0#a6076) and [11.2.6.2](https://jakarta.ee/specifications/faces/4.0/jakarta-faces-4.0#a6160), both related to `FacesServlet` mapping, but the other two occurrences saying "&lt;url-pattern&gt;" don't explicitly refer to servlet spec: [7.7.2.2](https://jakarta.ee/specifications/faces/4.0/jakarta-faces-4.0#a4030) and [11.3.2.1](https://jakarta.ee/specifications/faces/4.0/jakarta-faces-4.0#a6215), they instead refer to other section saying it should be compared against "view ID". 
4. The `ViewHandler#getProtectedViewsUnmodifiable()` is mentioned in [2.2.1](https://jakarta.ee/specifications/faces/4.0/jakarta-faces-4.0#a404) but no mention of URL pattern is made while the javadoc in turn says *"Compliant implementations must return a <code>Set</code> that is the concatenation of the contents of all the <code>&lt;url-pattern&gt;</code> elements within all the <code>&lt;protected-views&gt;</code> in all of the application configuration resources in the current application."*.
5. The source code of `getActionURL()`, where protected views are checked, is in Mojarra [implemented](https://github.com/eclipse-ee4j/mojarra/blob/4.0.8-RELEASE/impl/src/main/java/com/sun/faces/application/view/MultiViewHandler.java#L267) as follows:
    ```
    // Implement section 12.1 of the Servlet spec.
    if (urlPatterns.contains(viewId)) {
    ```
    Note the the surprising comment. This isn't explicitly requested in the Faces spec but the impl itself actually also doesn't adhere section 12.1 of the Servlet spec (view ID is compared against URL pattern instead of that request URI is compared against URL pattern!)

I'm not sure how we ended up here. But if we listen to the Faces spec literally, then the "URL pattern" / `<url-pattern>` is actually a misnomer for "View ID" / `<view-id>`. In other words, we should be re-interpreting them as view IDs. So we should be specifying `<url-pattern>/foo.xhtml</url-pattern>` when we want to make `foo.xhtml` a protected view, and this is irrespective of the `FacesServlet` mapping on `*.xhtml`, `*.jsf`, `/faces/*`, etc. In retrospect I think this is a smart desicion. This way we don't need to change the protected views config in case we happen to use a different `FacesServlet` mapping or even multiple mappings.

I do admit all of this is confusing to starters. All we can do to improve the Faces spec is one of the following:

1. Deprecate `<url-pattern>` and rename it to `<view-id>` for clarity.
2. Or, explicitly mention that impl must actually support Servlet 12.1 spec on parsing and comparing the `<url-pattern>` values against the view ID.

I think #1 is the way to go.

cc: @netomi

**Comment by netomi** [comment]
ty for taking care of this!
