### ISSUE TITLE
Can't obtain default attribute value for composite component from attributes map

### ISSUE THREAD

**Issue by mnyakushev** [eclipse-ee4j/mojarra#5512]
**Describe the bug**

In latest versions of mojarra the behavior of composite component attributes map (`UIComponent::getAttributes`) was changed.

In Payara server 6.2024.9 and above (Mojarra 4.0.7.payara-p1) I couldn't obtain  literal default attribute value from attributes map.
In Payara server 6.2024.8 and below (Mojarra 4.0.0.payara-p2) I could do this.

Looks like it's because of this changes (https://github.com/eclipse-ee4j/mojarra/commit/273b9eaaa015b1933fa59a76acd31c020ba14cf1)

**To Reproduce**

1. Download reproducer [mojarra-test.zip](https://github.com/user-attachments/files/17361517/mojarra-test.zip)
2. Build it
3. Deploy to latest Payara Server CE (6.2024.10)
4. Open link https://localhost:8080 (you don't see default attribute value on page)
5. Deploy to Payara Server CE 6.2024.8
6. Open link https://localhost:8080 (you will see default attribute value on page)

**Expected behavior**

I need clarification is it a bug or it's a feature?
Is the only correct way to get the attribute value now - via an EL expression like `#{cc.attrs.attributeName}`?

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Browser: chrome
 - Version: 129.0.6668.100

**Comment by BalusC** [comment]
It's indeed a bug which was already reported as https://github.com/eclipse-ee4j/mojarra/issues/5460 and fixed in 4.0.8 which was released at 1 sep 2024.
