### ISSUE TITLE
resetValues=true not working in Mojarra 4.0+

### ISSUE THREAD

**Issue by maqjav** [eclipse-ee4j/mojarra#5513]
**Describe the bug**

This is really a question more than a bug report.

Based on the ticket https://github.com/jakartaee/faces/issues/1936 Primefaces removed the option to resetValues while using JSF 4.0 because this functionality was going to be moved into the JSF implementation.

Right now we are using JSF 4.1 with Primefaces and _as expected_, it doesn't work anymore, because Primefaces doesn't do it, neither Mojarra.

Is this going to be ported to Mojarra 4.0+ at the end? I can see the merge into the 5.0 branch, but not into the 4.0.x.

This is [the ticket](https://github.com/primefaces/primefaces/issues/12710) in the Primefaces github where I reported the issue.

Thanks.

**Comment by melloware** [comment]
I know MyFaces backported it to 4.0 4.1 and 5.0. So I assume Mojarra would do the same.

**Comment by maqjav** [comment]
> I know MyFaces backported it to 4.0 4.1 and 5.0. So I assume Mojarra would do the same.

I saw those changes in myfaces, and also in Mojarra 5, but I cannot find anything in Mojarra 4, I just wanted to clarify this to be sure that the change will be included in a future Mojarra 4.1.x, otherwise this feature won't ever work with the current implementation of Primefaces and future versions of Mojarra 4.x+

**Comment by pizzi80** [comment]
I can see these files:

4.1:
https://github.com/eclipse-ee4j/mojarra/blob/4.1/impl/src/main/java/jakarta/faces/component/UIViewRoot.java#L1025

4.0
https://github.com/eclipse-ee4j/mojarra/blob/4.0/impl/src/main/java/jakarta/faces/component/UIViewRoot.java#L1019

basically what's missing is the recursive call to reset the children, correct?

**Comment by melloware** [comment]
yeah if you look in 5.0 its correct I believe.

**Comment by maqjav** [comment]
Here you can see the change made in 5.0: https://github.com/jakartaee/faces/commit/8a1d8c4b84719300126c996dd767314994f317ae

**Comment by BalusC** [comment]
Backported into 4.0.9 + 4.1.2.
