### ISSUE TITLE
HtmlResponseWriter typo or bug?

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5517]
https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriter.java#L503

At line 503 the actual condition for escaping or not is:

```
if (!withinScript && !withinScript) {
    dontEscape = false;
}
```

which is obviously a typo or a bug...

if it's a typo we could remove the second part,
but reading the code my suspect is that it should be
the same condition of line 421!

```
// always turn escaping back on once an element ends
if (!withinScript && !withinStyle) {
    dontEscape = false;
}
```

**Comment by BalusC** [comment]
Yes it's a typo / copy-paste-error. Feel free to PR/fix it.
